### ISSUE TITLE
Enabling streaming backup causes barman commands to hang waiting for futex

### ISSUE THREAD

**Issue by qdw** [EnterpriseDB/barman#100]
[I apologize in advance for the cross-post to the mailing list. I wasn't sure which would be the better forum for reporting this.]

I've run into a weird situation where WAL archiving works fine, but turning on streaming backup causes barman commands to  hang. I'm wondering if anyone else has seen similar behavior, or even if you have hints on how to proceed. A detailed description follows.

Barman version:

barman@barman-01:~$ barman --version

2.1 Barman by 2ndQuadrant (www.2ndQuadrant.com)

Python version:

barman@barman-01:~$ /usr/bin/python -V
Python 2.7.6

PostgreSQL version (hostname replaced with test.example.com for privacy):

barman@barman-01:~$ psql -U postgres -h test.example.com -c "select version()"
                                                version
-------------------------------------------------------------------------------------------------------
 PostgreSQL 9.3.16 on x86_64-unknown-linux-gnu, compiled by gcc (Ubuntu 4.8.2-19ubuntu1) 4.8.2, 64-bit
(1 row)

Here's my /etc/barman.conf without streaming replication:

[barman]
barman_home = /mnt/barman
barman_user = barman
log_file = /var/log/barman/barman.log
reuse_backup = link
last_backup_maximum_age = 1 WEEKS

[test]
retention_policy_mode = auto
retention_policy = RECOVERY WINDOW OF 1 DAY
archiver = on
ssh_command = ssh postgres@test.example.com
conninfo = host=test.example.com user=postgres

This works fine. WAL files show up in test/incoming, and eventually get moved to test/wals/

To enable streaming replication, I just append this line (to the [test] section):

streaming_archiver = on

I verify that I can connect via psql:

barman@barman-01:~$ psql -U postgres -h test.example.com -c "IDENTIFY_SYSTEM" replication=1
      systemid       | timeline |   xlogpos
---------------------+----------+--------------
 6024565419369553756 |        8 | 508/40F6B610
(1 row)

Then I run 'barman cron', per the docs:

barman@barman-01:~$ barman cron
Starting WAL archiving for server test
Starting streaming archiver for server test

Sure enough, that starts receive-wal:

barman@barman-01:~$ ps -ef | grep receive | grep -v grep
barman   12281     1  0 19:44 ?        00:00:00 /usr/bin/python /usr/bin/barman -c /etc/barman.conf -q receive-wal former-master

After that, I can still see WAL files showing up in test/incoming/ and then getting moved to test/wals/. But I can't see anything showing up in test/streaming/. More to the point, if I run any of the following commands, they hang indefinitely:

barman@barman-01:~$ barman check test
Server test:

barman@barman-01:~$ barman diagnose

barman@barman-01:~$ barman backup test # (takes only 16 minutes with streaming disabled)

In each of these cases, when I run strace on the hanging command, I see it waiting forever on a futex. For example:

root@barman-01:~# ps -ef | grep backup | grep -v grep
barman   19070 18887  0 19:53 pts/9    00:00:00 /usr/bin/python /usr/bin/barman backup test
root@barman-01:~# strace -p 19070
Process 19070 attached
futex(0x7f4c78cd9170, FUTEX_WAIT_PRIVATE, 2, NULL

Kernel version, in case it helps:

barman@barman-01:~$ uname -a
Linux test.example.com 3.13.0-55-generic #92-Ubuntu SMP Sun Jun 14 18:32:20 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Has anyone else seen this behavior? What's going on here? Any tips would be most welcome!

Many thanks,
—Q

**Comment by qdw** [comment]
Oh, and here's my 'barman diagnose' output (when I disable streaming so 'barman diagnose' actually completes):

{
    "global": {
        "config": {
            "barman_home": "/mnt/barman", 
            "barman_user": "barman", 
            "errors_list": [], 
            "last_backup_maximum_age": "1 WEEKS", 
            "log_file": "/var/log/barman/barman.log", 
            "reuse_backup": "link"
        }, 
        "system_info": {
            "barman_ver": "2.1", 
            "kernel_ver": "Linux barman-01.netcecloud.com 3.13.0-55-generic #92-Ubuntu SMP Sun Jun 14 18:32:20 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux", 
            "python_ver": "Python 2.7.6", 
            "release": "Distributor ID:\tUbuntu\nDescription:\tUbuntu 14.04.5 LTS\nRelease:\t14.04\nCodename:\ttrusty", 
            "rsync_ver": "rsync  version 3.1.0  protocol version 31", 
            "ssh_ver": "OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.8, OpenSSL 1.0.1f 6 Jan 2014"
        }
    }, 
    "servers": {
        "test": {
            "backups": {
                "20170406T144628": {
                    "backup_id": "20170406T144628", 
                    "backup_label": null, 
                    "begin_offset": 40, 
                    "begin_time": "Thu Apr  6 14:46:28 2017", 
                    "begin_wal": "000000070000050800000028", 
                    "begin_xlog": "508/28000028", 
                    "config_file": "/etc/postgresql/9.3/main/postgresql.conf", 
                    "deduplicated_size": 75095502227, 
                    "end_offset": 400, 
                    "end_time": "Thu Apr  6 15:03:20 2017", 
                    "end_wal": "000000070000050800000028", 
                    "end_xlog": "508/28000190", 
                    "error": null, 
                    "hba_file": "/etc/postgresql/9.3/main/pg_hba.conf", 
                    "ident_file": "/etc/postgresql/9.3/main/pg_ident.conf", 
                    "included_files": null, 
                    "mode": "rsync-exclusive", 
                    "pgdata": "/mnt/pgdata", 
                    "server_name": "former-master", 
                    "size": 75095502227, 
                    "status": "DONE", 
                    "tablespaces": null, 
                    "timeline": 7, 
                    "version": 90316
                }
            }, 
            "config": {
                "active": true, 
                "archiver": true, 
                "archiver_batch_size": 0, 
                "backup_directory": "/mnt/barman/former-master", 
                "backup_method": "rsync", 
                "backup_options": "exclusive_backup", 
                "bandwidth_limit": null, 
                "barman_home": "/mnt/barman", 
                "barman_lock_directory": "/mnt/barman", 
                "basebackup_retry_sleep": 30, 
                "basebackup_retry_times": 0, 
                "basebackups_directory": "/mnt/barman/former-master/base", 
                "check_timeout": 30, 
                "compression": null, 
                "conninfo": "host=db-02.netcecloud.com user=postgres", 
                "custom_compression_filter": null, 
                "custom_decompression_filter": null, 
                "description": null, 
                "disabled": false, 
                "errors_directory": "/mnt/barman/former-master/errors", 
                "immediate_checkpoint": false, 
                "incoming_wals_directory": "/mnt/barman/former-master/incoming", 
                "last_backup_maximum_age": "7 days", 
                "minimum_redundancy": 0, 
                "msg_list": [], 
                "name": "former-master", 
                "network_compression": false, 
                "path_prefix": null, 
                "post_archive_retry_script": null, 
                "post_archive_script": null, 
                "post_backup_retry_script": null, 
                "post_backup_script": null, 
                "pre_archive_retry_script": null, 
                "pre_archive_script": null, 
                "pre_backup_retry_script": null, 
                "pre_backup_script": null, 
                "recovery_options": "", 
                "retention_policy": "window 1 d", 
                "retention_policy_mode": "auto", 
                "reuse_backup": "link", 
                "slot_name": null, 
                "ssh_command": "ssh postgres@db-02.netcecloud.com", 
                "streaming_archiver": false, 
                "streaming_archiver_batch_size": 0, 
                "streaming_archiver_name": "barman_receive_wal", 
                "streaming_backup_name": "barman_streaming_backup", 
                "streaming_conninfo": "host=db-02.netcecloud.com user=postgres", 
                "streaming_wals_directory": "/mnt/barman/former-master/streaming", 
                "tablespace_bandwidth_limit": null, 
                "wal_retention_policy": "simple-wal 1 d", 
                "wals_directory": "/mnt/barman/former-master/wals"
            }, 
            "status": {
                "archive_command": "rsync -a %p barman@10.0.1.17:/mnt/barman/former-master/incoming/%f", 
                "archive_mode": "on", 
                "config_file": "/etc/postgresql/9.3/main/postgresql.conf", 
                "current_size": 70835870572.0, 
                "current_xlog": "000000080000050800000040", 
                "data_directory": "/mnt/pgdata", 
                "hba_file": "/etc/postgresql/9.3/main/pg_hba.conf", 
                "ident_file": "/etc/postgresql/9.3/main/pg_ident.conf", 
                "is_superuser": true, 
                "last_archived_wal": "00000008000005080000003F", 
                "pgespresso_installed": false, 
                "replication_slot": null, 
                "replication_slot_support": false, 
                "server_txt_version": "9.3.16", 
                "synchronous_standby_names": [
                    ""
                ], 
                "wal_level": "hot_standby"
            }, 
            "system_info": {
                "kernel_ver": "Linux db-02.netcecloud.com 3.13.0-58-generic #97-Ubuntu SMP Wed Jul 8 02:56:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux", 
                "python_ver": "Python 2.7.6", 
                "release": "Distributor ID:\tUbuntu\nDescription:\tUbuntu 14.04.5 LTS\nRelease:\t14.04\nCodename:\ttrusty", 
                "rsync_ver": "rsync  version 3.1.0  protocol version 31", 
                "ssh_ver": "OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.8, OpenSSL 1.0.1f 6 Jan 2014"
            }, 
            "wals": {
                "last_archived_wal_per_timeline": {
                    "00000007": {
                        "compression": null, 
                        "name": "000000070000050800000029", 
                        "size": 16777216, 
                        "time": 1491517389.5516706
                    }, 
                    "00000008": {
                        "compression": null, 
                        "name": "00000008000005080000003F", 
                        "size": 16777216, 
                        "time": 1491965132.6775682
                    }
                }
            }
        }
    }
}

**Comment by jjsantam** [comment]
Hello,
I have the same issue, or at least the same symptoms, but I also see and error in the DB log:

```
log_line_prefix = '%t [%p]: [%l-1] db=%d,user=%u,app=%a,client=%h '

Nov 15 18:51:17 test.example.com postgres[1892]: [6-1] db=[unknown],user=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
Nov 15 18:51:17 test.example.com postgres[1892]: [7-1] db=[unknown],user=streaming_barman,app=[unknown],client=[local] LOG:  replication connection authorized: user=streaming_barman
Nov 15 18:51:17 test.example.com postgres[1892]: [8-1] db=[unknown],user=streaming_barman,app=[unknown],client=[local] ERROR:  syntax error
Nov 15 18:55:11 test.example.com postgres[1892]: [9-1] db=[unknown],user=streaming_barman,app=[unknown],client=[local] LOG:  disconnection: session time: 0:03:54.278 user=streaming_barman database= host=[local]
```

My setup is a little different:

```
-bash-4.2$ barman --version
2.3

Barman by 2ndQuadrant (www.2ndQuadrant.com)

-bash-4.2$ tail -7 /etc/barman.conf
[streaming-pg]
description =  "Backup of PostgreSQL Database (Streaming-Only)"
conninfo = host=/tmp port=5444 user=barman dbname=postgres
streaming_conninfo = host=/tmp port=5444 user=streaming_barman
backup_method = postgres
streaming_archiver = on
slot_name = barman

-bash-4.2$ psql --version
psql (EnterpriseDB) 9.6.2.7
```

Regards

**Comment by alexeyoganezov** [comment]
I had the same issue. In my case turned out the problem originated from nonworking connection between Barman and PostgreSQL. Try to check and your firewall/network settings for possible misconfiguration.

**Comment by gbartolini** [comment]
Hi @qdw, can you please confirm that the problem persists with the latest Barman version? Thank you.

**Comment by amenonsen** [comment]
As part of an effort to pick up maintenance of Barman, I'm closing this and many other old open issues in this repository.

**Comment by elhananjair** [comment]
> As part of an effort to pick up maintenance of Barman, I'm closing this and many other old open issues in this repository.

Hello @amenonsen instead of opening a new issue I thought it would be better to say it here, I am having a problem testing the streaming connection with a barman. I am following the documentation and created a user named streaming_barman, and tried to test it with, 

> psql -U streaming_barman -h pg -c "IDENTIFY_SYSTEM"   replication=1 -d postgres

and here is an error am facing

> ERROR:  syntax error at or near "IDENTIFY_SYSTEM"
LINE 1: IDENTIFY_SYSTEM
        ^

**Comment by mikewallace1979** [comment]
The `-d postgres` option is overriding the connection string and preventing psql making a replication connection. Try removing the `-d postgres` option:

    psql -U streaming_barman -h pg -c "IDENTIFY_SYSTEM" replication=1

Or alternatively specify the replication option in the connection string:

    psql -U streaming_barman -h pg -c "IDENTIFY_SYSTEM" -d 'dbname=postgres replication=database'
