### ISSUE TITLE
FAQ about streaming replication

### ISSUE THREAD

**Issue by flibustenet** [EnterpriseDB/barman#101]
In the FAQ we can read:
> **Does barman support streaming replication protocol available from PostgreSQL 9?**
Currently, no. However, we would love to extend barman so that it can perform both the client and the server roles for streaming replication. It is certainly feasible and this would allow to implement cascading backup, as well as synchronous backup (for “0 recovery point objective”).

I use an old version of barman and look at upgrading it. If i understand correctly, the last version can work with streaming replication only and the faq should be upgraded isn'it ?

**Comment by amenonsen** [comment]
As part of an effort to pick up maintenance of Barman, I'm closing this and many other old open issues in this repository.
