### ISSUE TITLE
Terminology enhancement

### ISSUE THREAD

**Issue by kvaikla** [EnterpriseDB/barman#1011]
Two terminology enhancements.
**barman.conf**
Current:
Barman configuration file section `[servername] `
Could be:
Renamed to something like `[backup_spetsification]`
Why: you can in one pg server(name)  setup multiple barman backups.

**Restore end output**
Current: 
```
Recovery completed (start time: 2024-09-07 01:00:14.790065+03:00, elapsed time: 29 minutes, 52 seconds)
Your PostgreSQL server has been successfully prepared for recovery!
```
Could be:
```
Restore completed (start time: 2024-09-07 01:00:14.790065+03:00, elapsed time: 29 minutes, 52 seconds)
Your PostgreSQL server has been successfully prepared for recovery!
```
Why: Recovery completed ...  prepared for recovery!  :D And database is not yet recovered, but restored.

I have managed 25+ years oracle, pg backup integrations (HP Dataprotector,  Veritas NetBackup), so that's why I dare to make such suggsessions.

br
Kaido

**Comment by martinmarques** [comment]
Point two was addressed in Barman's last release. That was a good catch that I had not thought of before.
I can't make sense of point one. I understand what you mean, but it really doesn't have a use case what you explained in the "why". I'm closing this now
