### ISSUE TITLE
Could it be any problem restore related to other s3 providers like hetzners?

### ISSUE THREAD

**Issue by bbetters** [EnterpriseDB/barman#1036]
im trying to restore db from s3, i just need to know if maybe s3 storage like hetzner's is not supported yet so i can drop it
Im getting no target backup found even though the backup is there.
In the dev environment im backing up like this:
  backup:
    retentionPolicy: "1d"
    barmanObjectStore:
      destinationPath: s3://pg-dev.nbg1/deleteme/
      endpointURL: https://pg-dev.nbg1.your-objectstorage.com/
      s3Credentials:
        accessKeyId:
          name: kaktu-dev-auth-secrets
          key: s3-access-key
        secretAccessKey:
          name: kaktu-dev-auth-secrets
          key: s3-secret-key
      wal:
        maxParallel: 8
        
    at precisly this path /pg-dev.nbg1/deleteme/pg-dev.nbg1/deleteme/kaktu-pg-cluster/ I can see the base and wal folders 
    
    
    In the prod environment i want to bootrap like this:

 bootstrap:
      recovery:
        source: kaktu-pg-cluster
  externalClusters:
    - name: kaktu-pg-cluster
      barmanObjectStore:
        destinationPath: s3://pg-dev.nbg1/deleteme/
        endpointURL: https://pg-dev.nbg1.your-objectstorage.com/
        #serverName: 'kaktu-pg-cluster'
        s3Credentials:
          accessKeyId:
            name: kaktu-prod-auth-secrets
            key: s3-access-key
          secretAccessKey:
            name: kaktu-prod-auth-secrets
            key: s3-secret-key
        wal:
          maxParallel: 8

**Comment by bbetters** [comment]
Nevermind, problems with hetzners new s3 bucket!

**Comment by psavva** [comment]
Your endpointURL should not contain the bucket name.
Your destinationPath should be bucket+folder

destinationPath: s3://pg-dev/backups/
endpointURL: https://nbg1.your-objectstorage.com/

assuming you want to place the backups in 'backups' folder...

I've managed to get backups working, but restoration has a problem
