### ISSUE TITLE
post_backup_retry_script hook to barman-cloud-backup not running

### ISSUE THREAD

**Issue by kcslb92** [EnterpriseDB/barman#1043]
Hi Guys,

I've got barman 3.12 installed and am having issues with trying to use `barman-cloud-backup` in the `post_backup_retry_script` directive.

I've specified this as part of my server configuration file, ie `/etc/barman.d/server.conf`:

```
[server]
...

post_backup_retry_script = barman-cloud-backup --endpoint-url https://<internal-s3-endpoint> --cloud-provider aws-s3 s3://<bucket>/barman server
...
```

Looking at the `barman.log` I do not see it run at all when I specify `--wait` with the backup command. I am doing WAL streaming (no archiving) so I set the `--wait` parameter as suggested in the doco for the cloud hook.

If I run the backup without the `--wait` I can see that the hook runs but it fails w/ a rc63.

It _feels_ like I'm hitting a timeout when it's waiting for the xlogs at the very end before eventually closing. Any idea if this would contribute to why I can't see the hook being run?

**Comment by martinmarques** [comment]
What is the state of the backup in the barman server? Does it have status DONE or WAITING FOR WALS? Have you tried executing `barman-cloud-backup` manually to see if it works as expected?

**Comment by kcslb92** [comment]
Nevermind, this was a case of PEBCAK... It would be great to see some more documentation for making use of the cloud hook scripts, especially for the sync of backups to s3 and then pruning (delete) of the local backup so that it's all in S3 only, etc.

**Comment by martinmarques** [comment]
The whole cloud support has to be re-thought. The current state of things related with barman's cloud support is less than ideal, and documenting is good, but not enough IMO.
