### ISSUE TITLE
Is there ability to wipe barman replication slot?

### ISSUE THREAD

**Issue by Nefilime** [EnterpriseDB/barman#1045]
Hello. Could you please explain what I should do?
backup from patroni leader via repl slot. Using postgres user.

```
barman@barman:~$ barman receive-wal --reset patroni 
ERROR: ArchiverFailure:replication slot 'barman' is already in use

barman@barman:~$ barman receive-wal --drop-slot patroni 
Dropping physical replication slot 'barman' on server 'patroni'
ERROR: Cannot drop replication slot 'barman' on server 'patroni' because it is in use.
```

Can I recreate or wipe slot via barman?

**Comment by martinmarques** [comment]
If a slot is in use, it can't be dropped, not with the barman user, and not even with the postgres user. You need to kill the session.

See if this works for you:

```
barman receive-wal --stop patroni
barman receive-wal --drop-slot patroni
```

**Comment by Nefilime** [comment]
Thanks for answer.
Previous barman server was deleted and old repl slot stuck on Active state.
I did this quires to stop replication on Postgres.

`SELECT pid, application_name, state, client_addr 
FROM pg_stat_replication;

SELECT pg_terminate_backend(<pid>);`

After this quires barman start to use it.

I manage my infrastructure via ansible and I plan to execute some command on Barman layer to wipe slot.
