### ISSUE TITLE
Add support for non-default ssh port in barman-wal-restore

### ISSUE THREAD

**Issue by sasavilic** [EnterpriseDB/barman#120]
Hi,

it would nice if we had an option to specify ssh port in barman-wal-restore and other commands that use ssh.

I have patched barman-wal-restore and can provide you with PR if you like, but I am not sure if there are other tools where ssh is used.

**Comment by japsu** [comment]
Have you tried using an SSH configuration file to provide this?

Eg. `~/.ssh/config`:

```
Host alias-for-the-host
    Hostname real-hostname
    User barman
    Port 10022
```

Then use `alias-for-the-host` as the hostname for `barman-wal-restore` instead of `real-hostname`.

**Comment by amenonsen** [comment]
As part of an effort to pick up maintenance of Barman, I'm closing this and many other old open issues in this repository.
