### ISSUE TITLE
Ability to store long term backups.

### ISSUE THREAD

**Issue by andyzasl** [EnterpriseDB/barman#121]
Hi! 
My backup plan is to store 2 backups per week for 1 month with WAL, and store 1 backup per month for 1 year without WAL.  
Is there any way to realize that way with barman?  (the first part is ok, but what about second? :) )

**Comment by amenonsen** [comment]
This use case is something we intend to address in future.

As part of an effort to pick up maintenance of Barman, I'm closing this and many other old open issues in this repository.
