### ISSUE TITLE
Suggestion: casync support

### ISSUE THREAD

**Issue by lavidd** [EnterpriseDB/barman#132]
Hi guys,

there is a new tool available that appears to be superior to rsync as data synchronization tool:
https://github.com/systemd/casync

In particular:
- more data efficient than rsync
- faster than rsync
- friendly to CDNs
- other

I suggest that rsync in barman to be replaced by casync.

Any thoughts on this?

Best, 

lavidd

**Comment by stardude900** [comment]
Personally, the environment I manage which is primarily RHEL 5-7 it wouldn't be a good fit for us partly because it's not in the standard repos.  It is a neat piece of software and once it's a little more mature probably would be a good thing to have as an additional option.

**Comment by ShalbafZadeh** [comment]
@lavidd  hi casync seems a good piece of software 
but it's not mainstream yet and will add headache to adopt barman in some environments(old servers , tight security policy about installing additional package etc.) maybe after a greater adoption it might worth a shot!

**Comment by martinmarques** [comment]
casync hasn't had a release in 7 years, and the last commit is 9 months old, and nothing major sin 2022.
