### ISSUE TITLE
barman check all processes inactive servers

### ISSUE THREAD

**Issue by alexyuscott** [EnterpriseDB/barman#139]
We have 2 inactive server config files.  1 of those DB servers is not configured at all for barman, but may well be at some future date.

When I run barman check --nagios all, I get the following

> barman check --nagios all
BARMAN CRITICAL - 1 server out of 4 have issues * hq-pgs01 FAILED: WAL archive, wal_level, archive_mode, archive_command
hq-pgs01.WAL archive: FAILED (please make sure WAL shipping is setup)
hq-pgs01.wal_level: FAILED (please set it to a higher level than 'minimal')
hq-pgs01.archive_mode: FAILED (please set it to 'on')
hq-pgs01.archive_command: FAILED (please set it accordingly to documentation)

Should check be "checking" inactive servers?  Might it not be better to add a parameter to check such servers (--inactive or something).  Alternatively, a parameter to disable checking inactive servers?

**Comment by gbartolini** [comment]
Hello, can you please share the output of `barman diagnose`?

**Comment by alexyuscott** [comment]
[barman-diagnose.txt](https://github.com/2ndquadrant-it/barman/files/2072545/barman-diagnose.txt)

barman check --nagios all produces:

BARMAN CRITICAL - 1 server out of 3 have issues * host03 FAILED: backup maximum age, minimum redundancy requirements
host03.backup maximum age: FAILED (interval provided: 7 days, latest backup age: No available backups)
host03.minimum redundancy requirements: FAILED (have 0 backups, expected at least 1)

host03 is the inactive server.

Sorry for the delay in responding

**Comment by amenonsen** [comment]
As part of an effort to pick up maintenance of Barman, I'm closing this and many other old open issues in this repository.
