### ISSUE TITLE
barman backup Issue rsync

### ISSUE THREAD

**Issue by pstuewe** [EnterpriseDB/barman#140]
Hi I'm building my first barman test env.  Latest version 231.
barman and DB are on the same host.
The backup keeps failing; currently I'm not able to figure out what the error message is about.

barman backup i4ref
Starting backup using rsync-exclusive method for server i4ref in /var/lib/barman/i4ref/base/20180201T142334
i4ref: pg_receivexlog: finished segment at 0/39000000 (timeline 1)
Backup start at LSN: 0/39000028 (000000010000000000000039, 00000028)
This is the first backup for server i4ref
WAL segments preceding the current backup have been found:
 000000010000000000000035 from server i4ref has been removed
 000000010000000000000036 from server i4ref has been removed
 000000010000000000000037 from server i4ref has been removed
Starting backup copy via rsync/SSH for 20180201T142334
ERROR: The backup has failed copying files
Asking PostgreSQL server to finalize the backup.
i4ref: pg_receivexlog: finished segment at 0/3A000000 (timeline 1)
ERROR: Backup failed copying files.
DETAILS: data transfer failure
rsync error:
unexpected end of filter rule: P_
rsync error: syntax or usage error (code 1) at exclude.c(901) [client=3.0.9]
Processing xlog segments from file archival for i4ref
 000000010000000000000038
 000000010000000000000039
 000000010000000000000039.00000028.backup
Processing xlog segments from streaming for i4ref
 000000010000000000000038

rsync command is:
rsync -avh %p barman@axn-db01-i4ref:/var/lib/barman/i4ref/incoming/%f

thank you for your support
P

**Comment by gbartolini** [comment]
Hi, please share output of `barman diagnose`. Thanks.

**Comment by amenonsen** [comment]
As part of an effort to pick up maintenance of Barman, I'm closing this and many other old open issues in this repository.
