### ISSUE TITLE
barman - failure issuing stop backup command 

### ISSUE THREAD

**Issue by alessandroG77** [EnterpriseDB/barman#148]
Hi, we have a problem with Barman.
When barman backup does full backup we have this problem:

Errors:
failure issuing stop backup command (Cannot terminate exclusive backup  You might have to manually execute pg_stop_backup on your PostgreSQL server)

We don't have any external job on remote postgres (like crontab or other operation)

Can you help us?

**Comment by alessandroG77** [comment]
Anyone can help me?

**Comment by mnencia** [comment]
It is impossible to help you with the information you have provided.

Please attach the diagnose output and as much information as you can on your architecture.

**Comment by alessandroG77** [comment]
Hi Marco,
we have a barman (ver barman-2.0-1) installed on one VM.
We backup about 8 postgres (on different vm's) and all working well.

But when i try to backup one server, backup starting (about 250gb)
and after 1/2 hour failed with this error:

**failure issuing stop backup command (Cannot terminate exclusive backup You might have to manually execute pg_stop_backup on your PostgreSQL server)**

On my barman machine this the output:
 barman check server1
Server server1:
        PostgreSQL: OK
        superuser: OK
        wal_level: OK
        directories: OK
        retention policy settings: OK
        backup maximum age: OK (no last_backup_maximum_age provided)
        compression settings: OK
        failed backups: FAILED (there are 2 failed backups)
        minimum redundancy requirements: FAILED (have 0 backups, expected at least 2)
        ssh: OK (PostgreSQL server)
        not in recovery: OK
        archive_mode: OK
        archive_command: OK
        continuous archiving: OK
        archiver errors: OK

I've tried to stop backup on remote server with pg_stop_backup e retry to backup
with barman backup but nothing change.

On log on remote postgres nothing appear.
We haven't other job on remote postgres while backupping.

It's very strange.
I' ve also try to incerase checkpoints_segments but nothing.

Thanks for your help, Marco.

**Comment by alessandroG77** [comment]
remote Postgres: postgresql-9.4.5

**Comment by alessandroG77** [comment]
With barman diagnose we have:
"servers": {
        "smart-license": {
            "backups": {
                "20180407T061348": {
                    "backup_id": "20180407T061348",
                    "backup_label": null,
                    "begin_offset": 40,
                    "begin_time": "Sat Apr  7 04:13:47 2018",
                    "begin_wal": "0000000100000A6A000000C6",
                    "begin_xlog": "A6A/C6000028",
                    "config_file": "/methode/methbi/cfg/postgresql.conf",
                    "deduplicated_size": null,
                    "end_offset": null,
                    "end_time": null,
                    "end_wal": null,
                    "end_xlog": null,
                    "error": "failure issuing stop backup command (Cannot terminate exclusive backup. You might have to manually execute pg_stop_backup on your PostgreSQL server)",
                    "hba_file": "/methode/methbi/cfg/pg_hba.conf",
                    "ident_file": "/methode/methbi/cfg/pg_ident.conf",
                    "included_files": null,
                    "mode": "rsync-exclusive",
                    "pgdata": "/methode/methbi/mnt/pgsql",
                    "server_name": "smart-license",
                    "size": null,
                    "status": "FAILED",
                    "tablespaces": null,
                    "timeline": 1,
                    "version": 90405
                },
                "20180421T061358": {
                    "backup_id": "20180421T061358",
                    "backup_label": null,
                    "begin_offset": 40,
                    "begin_time": "Sat Apr 21 04:13:57 2018",
                    "begin_wal": "0000000100000A92000000DD",
                    "begin_xlog": "A92/DD000028",
                    "config_file": "/methode/methbi/cfg/postgresql.conf",
                    "deduplicated_size": null,
                    "end_offset": null,
                    "end_time": null,
                    "end_wal": null,
                    "end_xlog": null,
                    "error": "failure issuing stop backup command (Cannot terminate exclusive backup. You might have to manually execute pg_stop_backup on your PostgreSQL server)",
                    "hba_file": "/methode/methbi/cfg/pg_hba.conf",
                    "ident_file": "/methode/methbi/cfg/pg_ident.conf",
                    "included_files": null,
                    "mode": "rsync-exclusive",
                    "pgdata": "/methode/methbi/mnt/pgsql",
                    "server_name": "smart-license",
                    "size": null,
                    "status": "FAILED",
                    "tablespaces": null,
                    "timeline": 1,
                    "version": 90405
                }

**Comment by gbartolini** [comment]
Hi @alessandroG77, thanks for using Barman. Please repeat the operations with the latest Barman version (currently 2.3), as many bug fixes have been applied since 2.0.

Our trunk based development policy is to allow our users to perform in place upgrades without breaking compatibility with past versions. Therefore we do not support older versions, as our response is 'update Barman'.

**Comment by alessandroG77** [comment]
Hi Gabriele,
all seem to work with upgrade to 2.3.

Thanks a lot.
