### ISSUE TITLE
 ERROR: ArchiverFailure:replication slot 'barman' is already in use

### ISSUE THREAD

**Issue by pmpetit** [EnterpriseDB/barman#175]
Hello,
i have upgraded to 2.4 thinking the pb was solved, but i stil get this error : 
 ERROR: ArchiverFailure:replication slot 'barman' is already in use
for your information, this is a test server with 2 pgsql version (9.5 & 10)
with pgbench running on background onthe 3 clusters, using both system "streaming archiver" and "wal archiving" ....
backups are launch every hours ...
my config is : pgsql version 10
join, the diagnose result...

[barman_diagnose.zip](https://github.com/2ndquadrant-it/barman/files/2061394/barman_diagnose.zip)

here is an log extract : 
1/40000000 (timeline 1)
2018-06-01 08:58:34,605 [29547] barman.server ERROR: Check 'receive-wal running' failed for server 'infrz1pgs11_temboard'
2018-06-01 08:58:34,625 [29547] barman.server ERROR: Impossible to start the backup. Check the log for more details, or run 'barman check infrz1pgs11_temboard'

and when i try to restart the receive_wal process : 
[barman@infrz1pgs11 ~]$ barman receive-wal infrz1pgs11_temboard
Starting receive-wal for server infrz1pgs11_temboard
ERROR: ArchiverFailure:replication slot 'barman' is already in use
[barman@infrz1pgs11 ~]$

**Comment by jwashington104** [comment]
I'm also receiving this same issue. However I'm backing up 9 servers with barman - I'd also like to point out, that running barman with --retry-times and --retry-sleep options set are completely sidelined by this problem resulting in no backups being attempted after the first fail.

**Comment by amenonsen** [comment]
As part of an effort to pick up maintenance of Barman, I'm closing this and many other old open issues in this repository.

**Comment by Nefilime** [comment]
Hello. Could you please explain what I should do?
backup from patroni leader. Using postgres user.
```
barman@barman:~$ barman receive-wal --reset patroni 
ERROR: ArchiverFailure:replication slot 'barman' is already in use

barman@barman:~$ barman receive-wal --drop-slot patroni 
Dropping physical replication slot 'barman' on server 'patroni'
ERROR: Cannot drop replication slot 'barman' on server 'patroni' because it is in use.

``` 
Can I recreate or wipe slot via barman?

P.S. I didn't find issues with this error explanation.
