### ISSUE TITLE
KeyboardInterrupt

### ISSUE THREAD

**Issue by pmpetit** [EnterpriseDB/barman#176]
Hello,
sometimes, i can find this kind of error in the barman.log file, (Once a week )
My conf is  : rhel 7.4, barman 2.3
2018-06-04 20:30:01,991 [28258] barman.cli ERROR: Process interrupted by user (KeyboardInterrupt)
of course @20:30:01,991 nobody interrupted the backup using a [ctrl-c] command.....

For your information, the backup command is executed at 20h30m00s
the error is raised 2 sec later....

Thanks

**Comment by amenonsen** [comment]
As part of an effort to pick up maintenance of Barman, I'm closing this and many other old open issues in this repository.
