### ISSUE TITLE
FATAL: the configuration file barman.conf contains a not empty [barman] section

### ISSUE THREAD

**Issue by dkgnim** [EnterpriseDB/barman#177]
barman show-server main-db-server

/etc/barman.d/barman.conf 
[barman]

barman_home = /var/lib/barman
barman_user = root
log_file = /var/log/barman/barman.log
compression = gzip
reuse_backup = link
immediate_checkpoint = true
basebackup_retry_times = 3
basebackup_retry_sleep = 30
last_backup_maximum_age = 1 DAYS

[main-db-server]

description = "Main DB Server"
ssh_command = ssh root@xxx.xxx.xxx.xxx
conninfo = host=xxx.xxx.xxx.xxx user=postgres
retention_policy_mode = auto
retention_policy = RECOVERY WINDOW OF 7 days
wal_retention_policy = main

**Comment by ShalbafZadeh** [comment]
is it fixed ? @dkgnim 
can you add full stacktrace of barman ?

**Comment by amenonsen** [comment]
As part of an effort to pick up maintenance of Barman, I'm closing this and many other old open issues in this repository.
