### ISSUE TITLE
Retention delete

### ISSUE THREAD

**Issue by mendris** [EnterpriseDB/barman#180]
Hi,
before deleting backup files and wal files, I would like to copy all the backup files to the TAPE library.
Unfortunately barman haven't relation between Tape Library logic and backup processing.
Before deleting backup files all the backup files must be saved to the library!
It is possible check when the backup has been finished and wait the deletion processes of wals files?

Regards.

**Comment by slavniyteo** [comment]
I do not know why nobody's answered yet, but I'll try. I'm not from barman dev-team.

Hook scripts should be what you want: http://docs.pgbarman.org/release/2.5/#hook-scripts

**Comment by amenonsen** [comment]
As part of an effort to pick up maintenance of Barman, I'm closing this and many other old open issues in this repository.
