### ISSUE TITLE
Parallel WAL compression feature

### ISSUE THREAD

**Issue by yum-install-brains** [EnterpriseDB/barman#181]
Hello!

I use PostgreSQL 10.4 and Barman 2.4 with WAL compression. Everything works fine except when PostgreSQL generates extra WAL due to some heavy write load on database cluster. In this case incoming_wals_directory starts to fill up, waiting pigz compression to finish. In worst case we had about 200k WALs waiting in queue.

Could you, please, add parallel WAL compression feature in future Barman versions? 

P.S. I found a [patch](https://groups.google.com/forum/#!topic/pgbarman/D-rFIa0Oays), but it seems to be rejected.

**Comment by hobgoblinsmaster** [comment]
pigz is already parallel, running multiple barman command will not speed up compression. What I am doing to avoid waiting to much is limiting the batch size:

archiver_batch_size = 5000
max_incoming_wals_queue = 5000

First one is to compress only 5000 wal at each run (my barman cron is scheduled every 5 minutes).
Second is to trigger an alert when running barman check all --nagios via NRPE.

Next you will have to add more CPU cores and be able to do more I/O on disk if you want to be able to process more wals in less time.

**Comment by dswarbrick** [comment]
Perhaps also consider switching to a faster compressor with similar compression ratio, such as zstd.

**Comment by amenonsen** [comment]
As part of an effort to pick up maintenance of Barman, I'm closing this and many other old open issues in this repository.
