### ISSUE TITLE
recovery until specific timestamp in a specific timeline is not possible

### ISSUE THREAD

**Issue by ThomasPoty** [EnterpriseDB/barman#185]
Hello,

Here is the context : 
A backup was made at 1:00 am (B1), the timeline was 3.
A new backup was made the same day at 4:00 pm (B2), the timeline was still 3
A recover has been made from B1 until 1:00 pm, the timeline was 4 at this moment
A backup  was made at 17:00 pmam (B3), the timeline was 4

My need is recover from B1 until 3:30 pm this day in the timeline 3

I want to recover at the RX point
timeline 3 ----B1-----+----RX----B2------#
                                  \
timeline 4                     --------------------B3-------------    (current timeline)

Here is the command I have tried : 
```
barman recover --jobs 4 --remote-ssh-command "ssh postgres@my_test_server" --target-time "2018-09-28 15:30:00.000" --target-action pause --target-tli 3 my_barman_alias 20180928T012312 /var/lib/data
ERROR: You cannot specify multiple targets for the recovery operation
```

workaround : 
* you need to remove the option "--target-tli" and execute the command
* once the barman command has been executed, you need to add/set in the recovery.conf the parameter `recovery_target_timeline`
* start PostgreSQL

**Comment by ich199** [comment]
This still appears to be an issue. Specifying `recovery_target_timeline`, along with other `recovery_target_` options is a valid combination https://www.postgresql.org/docs/13/runtime-config-wal.html#RUNTIME-CONFIG-WAL-RECOVERY-TARGET
