### ISSUE TITLE
Streaming vs .pgpass

### ISSUE THREAD

**Issue by jesperpedersen** [EnterpriseDB/barman#193]
Hi,

I'm using `/home/barman/.pgpass` as the way to provide the password. However, it isn't working for the streaming part of the configuration:

```
	PostgreSQL: OK
	is_superuser: OK
	PostgreSQL streaming: FAILED (fe_sendauth: no password supplied)
```

Adding the password explicit in `/etc/barman.conf`, in `conninfo` of course helps:

```
	PostgreSQL: OK
	is_superuser: OK
	PostgreSQL streaming: OK
```

Using barman 2.5.

**Comment by deric** [comment]
@jesperpedersen The issue is the barman [overrides `coninfo` string](https://github.com/2ndquadrant-it/barman/blob/937d9ce8a4ff4b851134391238cf0ae6a6ba6f44/barman/postgres.py#L286).

Which isn't logged even in `DEBUG` level. Your `.pgpass` should include rule for `replication` DB, e.g.:
```
pg.example.com:5432:replication:barman:s3cr3tP2ssw0rd
```

**Comment by jesperpedersen** [comment]
@deric Thanks for the hint !

However, adding a `replication` entry to `.pgpass` and removing the `password=xyz` from `conninfo` makes `barman switch-wal` unhappy. So, not resolved as of yet.

**Comment by deric** [comment]
You should have 2 records in your `.pgpass`, the second one is for fictive DB:
```
pg.example.com:5432:postgres:barman:s3cr3tP2ssw0rd
pg.example.com:5432:replication:barman:s3cr3tP2ssw0rd
```
`barman check {dbserver}` or `barman diagnose` doesn't show anything suspicious?

**Comment by gbartolini** [comment]
I could not reproduce it.

**Comment by amenonsen** [comment]
Yep, this configuration works fine for me as well, so I'm closing this.
