### ISSUE TITLE
hook: post_backup_script

### ISSUE THREAD

**Issue by yerrysherry** [EnterpriseDB/barman#212]
Hallo,

We use a post_backup_script hook but we think that it is not always executed.

* In one terminal, we start a backup, after a 10 seconds we doing in an other terminal a pkill barman We don't see anything in de log file.

* After a backup is finished, the status is always: WAITING_FOR_WALS. For our custom tools it's difficult to check if the backup is 100% ok or not. Now in our production scripts we write something as:

/bin/barman check-backup $SERVER $BACKUP_ID
if [ $? -ne 0 ]

Is it possble to give an extra option to the "barman backup $server", so we know that the backup in 100% consistent?

* When the postgres daemon is down and we start a backup, the hook is also not executed. 

Is it not a good idea to always execute the hook?

===

post_backup_script = /var/lib/barman/scripts/barman_post_hook.sh
#!/bin/bash

LOGFILE="/tmp/barman.log"

exec >> ${LOGFILE} 2>&1

barman check-backup $BARMAN_SERVER latest

echo "date: $(date)"
echo "server: $BARMAN_SERVER"
echo "status: $BARMAN_STATUS"
echo "error: $BARMAN_ERROR"

if [[ -z "$BARMAN_ERROR" && "$BARMAN_STATUS" == "WAITING_FOR_WALS" ]]; then
  echo "No error"
fi

=====

Regards,
Gerrit

**Comment by amenonsen** [comment]
> Is it possble to give an extra option to the "barman backup $server", so we know that the backup in 100% consistent?

I think the `barman backup … --wait` option is what you need:

```
              --wait, -w
                     wait for all required WAL files by the base backup to be archived

              --wait-timeout
                     the time, in seconds, spent waiting for the required WAL files to be archived before timing out
```

(This is an old issue, so I'm closing it now.)
