### ISSUE TITLE
About synchronous commit problem

### ISSUE THREAD

**Issue by zard14** [EnterpriseDB/barman#214]
Recently I test  synchronous commit  function, and  I met something strange.

Maste: U123 -> Slave U456 (Barman also install on this node)  

IF I set  synchronous_standby_names in Master Node config and reload,  DB will be lock.

But it is just locked by ap connection(C# with Npgsql  2.2.5),  not by function call 
(Like execute db function() )

synchronous_standby_names = 'barman_receive_wal'
or
synchronous_standby_names = '*'

But if I change to Node Slave, everything is OK.
synchronous_standby_names = 'U456'

I also checked barman log.
Event if DB was be locked,  it didn't  have any other error logs.
Postgresql log neither.

barman check [master node] is also all green.

Because I don't know about C sharp, so  any idea or suggestions are welcomed,   
                                                                                                                      Thank you !

**Comment by amenonsen** [comment]
As part of an effort to pick up maintenance of Barman, I'm closing this and many other old open issues in this repository.

**Comment by amenonsen** [comment]
(Please open a new issue with details if this is still a problem for you.)
