### ISSUE TITLE
Unable to list/delete backups for inactive server

### ISSUE THREAD

**Issue by SpComb** [EnterpriseDB/barman#227]
As part of upgrading a server from PostgreSQL 9.5 -> 11 using `pg_dumpall | psql`, I had to configure a new barman backup server to replace the old barman backup server. I now have two barman servers configured: `xyz-pgsql-dev1` (`active = false`) and `xyz-pgsql-dev1@11`. I would like to gradually cleanup the backups for the old server to make space for the new backups, but I am unable to use the `barman` command to do this:

```
$ sudo barman list-server
xyz-pgsql-dev1 - xyz-pgsql-dev1 @ PostgreSQL 9.5 (inactive)
xyz-pgsql-dev1@11 - xyz-pgsql-dev1 @ PostgreSQL 11
$ sudo barman list-backup xyz-pgsql-dev1
Skipping inactive server 'xyz-pgsql-dev1'
$ sudo barman delete xyz-pgsql-dev1 20190521T031702
Skipping inactive server 'xyz-pgsql-dev1'
```

Would it be possible to allow such maintenance commands for inactive servers, when using `active = false` to decomission a server?

**Comment by amenonsen** [comment]
As part of an effort to pick up maintenance of Barman, I'm closing this and many other old open issues in this repository.
