### ISSUE TITLE
Installing/updating Barman 2.8.1 on CentOS 6 fails due to unknown dependencies

### ISSUE THREAD

**Issue by alexyuscott** [EnterpriseDB/barman#230]
I am uncertain if this is a Barman, PGDG or even EPEL issue (or a combination of the 3!)

On Centos 6.10, when trying to update Barman from 2.6.1 to 2.8.1, yum fails as follows:

> yum update barman
Resolving Dependencies
--> Running transaction check
---> Package barman.noarch 0:2.6-1.rhel6 will be updated
---> Package barman.noarch 0:2.8-1.rhel6 will be an update
--> Processing Dependency: python2-barman = 2.8 for package: barman-2.8-1.rhel6.noarch
--> Running transaction check
---> Package python2-barman.noarch 0:2.8-1.rhel6 will be installed
--> Processing Dependency: python2-psycopg2 >= 2.4.2 for package: python2-barman-2.8-1.rhel6.noarch
--> Processing Dependency: python2-argh >= 0.21.2 for package: python2-barman-2.8-1.rhel6.noarch
--> Processing Dependency: python2-setuptools for package: python2-barman-2.8-1.rhel6.noarch
--> Processing Dependency: python2-dateutil for package: python2-barman-2.8-1.rhel6.noarch
--> Processing Dependency: python2-argcomplete for package: python2-barman-2.8-1.rhel6.noarch
--> Running transaction check
---> Package python2-barman.noarch 0:2.8-1.rhel6 will be installed
--> Processing Dependency: python2-psycopg2 >= 2.4.2 for package: python2-barman-2.8-1.rhel6.noarch
--> Processing Dependency: python2-argh >= 0.21.2 for package: python2-barman-2.8-1.rhel6.noarch
--> Processing Dependency: python2-argcomplete for package: python2-barman-2.8-1.rhel6.noarch
---> Package python2-dateutil.noarch 0:1.4.1-0.el6 will be installed
---> Package python2-setuptools.noarch 0:0.6.10-0.el6 will be installed
--> Finished Dependency Resolution
Error: Package: python2-barman-2.8-1.rhel6.noarch (CentOS-6-pgdg10)
           Requires: python2-argcomplete
Error: Package: python2-barman-2.8-1.rhel6.noarch (CentOS-6-pgdg10)
           Requires: python2-argh >= 0.21.2
Error: Package: python2-barman-2.8-1.rhel6.noarch (CentOS-6-pgdg10)
           Requires: python2-psycopg2 >= 2.4.2
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

Looking through the PGDG10 repo, for Centos7, python2-psycopg2 exists, but not for Centos 6
python2-argcomplete and python2-argh both come from EPEL and again, exist in the repo for Centos7 but not for Centos 6

Thanks

**Comment by asser** [comment]
I am having the same issue on Centos 6.10.

It looks like a PGDG issue; the packages are actually named python-psycopg2 (rather than python2-psycopg2) etc. in the rhel-6.10 repo so I guess python2-barman should depend on these instead.

I'm not sure where to go to have it fixed though, I guess the PGDG issue tracker?

**Comment by asser** [comment]
Opened an issue with the Postgresql Yum Repository issue tracker:

https://redmine.postgresql.org/issues/4767

**Comment by asser** [comment]
This has now been resolved by Devrim over at the Postgresql RPM Building project, see above issue link.
