### ISSUE TITLE
Procedure to decommission a server from BARMAN

### ISSUE THREAD

**Issue by gboscarino** [EnterpriseDB/barman#247]
Hello,

What is the procedure to decommission a server from BARMAN?

After having removed a given server configuration file (e.g. dev_common_102_rdb-qaf1-5-pg-1.conf) from the /etc/barman.d directory, BARMAN has stopped the associated wal-receiver process as expected. However, barman is still writing the following error log messages in the /var/log/barman/barman.log file:

2019-10-31 18:41:08,913 [91069] barman.cli ERROR: Unknown server 'dev_common_102_rdb-qaf1-5-pg-1'
2019-10-31 18:41:09,494 [91216] barman.cli ERROR: Unknown server 'dev_common_102_rdb-qaf1-5-pg-1'

It looks like that each message is generated by a new process.

In order to isolate the problem, I have stopped all the remaining wal receiver processes and also disabled the cron command from /etc/cron.d/barman. However, the messages are still generated with a frequency of a few seconds.

The output of the command 'barman diagnose' does not show anything related to the decommissioned server.

What is that I am missing to let barman know that a given server has been removed? 

Note:  BARMAN v 2.3.

Thank you.

Gaspare

**Comment by jonathon2nd** [comment]
Wondering the same.

**Comment by jonathon2nd** [comment]
I was wondering the same. 
Turns out it was the Zabbix monitoring that kept trying to check up on a removed system.

**Comment by amenonsen** [comment]
As part of an effort to pick up maintenance of Barman, I'm closing this and many other old open issues in this repository.

**Comment by phoffmannsva** [comment]
Just for documentation: I got the same error message. In my case the archive_command was not changed to the new server: "barman-wal-archive <barman server> <postgres server> %p"
