### ISSUE TITLE
Feature Request: Support Cloud Object Storage

### ISSUE THREAD

**Issue by jorsol** [EnterpriseDB/barman#248]
Object Storage (S3, GCS...) is a common requirement of many backup solutions, since there are many Object Storage platform, an ideal approach is to use something like:

https://libcloud.apache.org/

With this, it can be supported many providers: https://libcloud.readthedocs.io/en/latest/storage/supported_providers.html

**Comment by amenonsen** [comment]
This is something that we've begun to address through the release of barman-cloud, and will continue to improve.

As part of an effort to pick up maintenance of Barman, I'm closing this and many other old open issues in this repository.
