### ISSUE TITLE
No valid backup

### ISSUE THREAD

**Issue by alexey1607** [EnterpriseDB/barman#255]
Hello,
I have:
postgresql 11
barman 2.9

Not consistent backup after restored, about 10 tables are missing.
barman config 
`
[s-t-fd-db-01]

description =  "backup PostgreSQL Database (via SSH)"

; ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; SSH options (mandatory)
; ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
ssh_command = ssh postgres@db-01.t-global.bcs

; ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; PostgreSQL connection string (mandatory)
; ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
conninfo = host=172.18.8.35 user=postgres port=5432

; ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Backup settings (via rsync over SSH)
; ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
backup_method = rsync
; Incremental backup support: possible values are None (default), link or copy
;reuse_backup = link
; Identify the standard behavior for backup operations: possible values are
; exclusive_backup (default), concurrent_backup
; concurrent_backup is the preferred method with PostgreSQL >= 9.6
backup_options = exclusive_backup
; Number of parallel workers to perform file copy during backup and recover
;parallel_jobs = 1
reuse_backup = link
; ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Continuous WAL archiving (via 'archive_command')
; ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
archiver = on
;archiver_batch_size = 50
minimum_redundancy = 10
immediate_checkpoint = true
compression = bzip2
retention_policy = RECOVERY WINDOW OF 1 MONTHS
immediate_checkpoint = true
; PATH setting for this server
;path_prefix = "/usr/pgsql-9.6/bin"
`

barman list-backup db-01

`
db-01 20191217T010001 - Tue Dec 17 01:00:04 2019 - Size: 278.2 MiB - WAL Size: 2.3 MiB
db-01 20191216T010002 - Mon Dec 16 01:00:04 2019 - Size: 278.2 MiB - WAL Size: 695.2 KiB
db-01 20191215T010001 - Sun Dec 15 01:00:03 2019 - Size: 278.2 MiB - WAL Size: 9.2 KiB
`
barman show-backup db-01 20191217T010001

`
Backup 20191217T010001:
  Server Name            : db-01
  Status                 : DONE
  PostgreSQL Version     : 110002
  PGDATA directory       : /var/lib/pgsql/11/data

  Base backup information:
    Disk usage           : 278.2 MiB (278.2 MiB with WALs)
    Incremental size     : 46.4 MiB (-83.32%)
    Timeline             : 1
    Begin WAL            : 000000010000000200000005
    End WAL              : 000000010000000200000005
    WAL number           : 1
    WAL compression ratio: 100.00%
    Begin time           : 2019-12-17 01:00:01.971152+03:00
    End time             : 2019-12-17 01:00:04.499144+03:00
    Copy time            : 1 second + 1 second startup
    Estimated throughput : 44.3 MiB/s
    Begin Offset         : 40
    End Offset           : 304
    Begin LSN           : 2/5000028
    End LSN             : 2/5000130

  WAL information:
    No of files          : 1
    Disk usage           : 2.3 MiB
    WAL rate             : 0.12/hour
    Compression ratio    : 85.53%
    Last available       : 000000010000000200000006

  Catalog information:
    Retention Policy     : VALID
    Previous Backup      : 20191216T010002
    Next Backup          : - (this is the latest base backup)
`
in the logs  records

`
2019-12-17 20:26:02,273 [27056] barman.wal_archiver INFO: No xlog segments found from file archival for db-01.
2019-12-17 20:27:01,492 [27169] barman.wal_archiver INFO: No xlog segments found from file archival for db-01.
2019-12-17 20:28:01,728 [27284] barman.wal_archiver INFO: No xlog segments found from file archival for db-01.
2019-12-17 20:29:01,947 [27428] barman.wal_archiver INFO: No xlog segments found from file archival for db-01.
2019-12-17 20:30:02,181 [27584] barman.wal_archiver INFO: No xlog segments found from file archival for db-01.
2019-12-17 20:31:01,395 [27769] barman.wal_archiver INFO: No xlog segments found from file archival for db-01.
`

**Comment by amenonsen** [comment]
As part of an effort to pick up maintenance of Barman, I'm closing this and many other old open issues in this repository. Please open a new issue with details if this is still a problem for you.
