### ISSUE TITLE
[Feature request] support --max-rate param for postgres backup type

### ISSUE THREAD

**Issue by shamil** [EnterpriseDB/barman#263]
`pg_basebackup` supports transfer rate limit by using `--max-rate` param, afaik it's not supported by barman. Is it possible to add the support for this param?

More info: https://www.postgresql.org/docs/11/app-pgbasebackup.html

**Comment by shamil** [comment]
I see in the codebase barman does have support for `max--rate`, but the documentation crealrly state that it's not supported with `postgres` backup method

> IMPORTANT: the `bandwidth_limit` and the `tablespace_bandwidth_limit` options are not supported with the `postgres` backup method

Am I missing something?

**Comment by adrianlzt** [comment]
I have tested with ``--bwlimit 99999`` and it was passed as ``--max-rate=99999`` to the ``pg_basebackup``.
The doc is confusing between old-style backups and new ones with streaming

**Comment by amenonsen** [comment]
Thanks, I have rephrased the documentation to make this clear:

```
+> **IMPORTANT:** the `bandwidth_limit` option is supported with the
+> `postgres` backup method for Postgres 9.4 and above, but the
+> `tablespace_bandwidth_limit` option is available only if you use
+> `rsync`
```
