### ISSUE TITLE
scripts/barman-wal-restore script is missing from source ?

### ISSUE THREAD

**Issue by pvbiesen** [EnterpriseDB/barman#275]
This file is referenced from following blogpost : 

https://www.2ndquadrant.com/en/blog/speed-up-getting-wal-files-from-barman/

But it seems to missing from the repository. Documentation pages are available, but the script itself, is not.

Is it obsoleted / replaced ?

**Comment by pvbiesen** [comment]
in a more recent blogpost, barman-cli package is still referenced for the barman-wal-restore file :

https://www.2ndquadrant.com/en/blog/barman-2-10-recovery-of-partial-wal-files/

**Comment by amenonsen** [comment]
The file is no longer present as `scripts/barman-wal-restore`, but instead generated from `barman/clients/walrestore.py`:

```
setup.py
84:                "doc/barman-wal-restore.1",
98:            "barman-wal-restore=barman.clients.walrestore:main",
```
