### ISSUE TITLE
barman-wal-archive --test and barman receive-wal --reset return exit code 0 even on failure

### ISSUE THREAD

**Issue by loop-evgeny** [EnterpriseDB/barman#279]
barman 2.10, PostgreSQL 12, Ubuntu 18.04

As recommended in the barman documentation I run `barman-wal-archive --test` to check if WAL archiving works before setting archive_command in the PostgreSQL configuration. I'd like to automate this and check that `barman-wal-archive` succeeded, but this is difficult, because it returns exit code 0 even if the server is inactive or does not exist at all, e.g.

```
$ barman-wal-archive --test HOSTNAME nosuchserver DUMMY && echo Success?
ERROR: Unknown server 'nosuchserver'
b''
Success?
```

Please make it return exit code 0 only on success.

**Comment by loop-evgeny** [comment]
Similar issue with `barman receive-wal --reset`:

> $ barman receive-wal --reset MYSERVER
> Unable to reset the status of receive-wal for server settings-pg12. Process is still running
> $ echo $?
> 0

**Comment by richyen** [comment]
Kind of makes me wonder if we should consolidate some items into a library so we're not duplicating code (see `barman/clients/walrestore.py`)

**Comment by mikewallace1979** [comment]
Filed https://github.com/EnterpriseDB/barman/issues/539 for the `barman receive-wal` part of this issue.
