### ISSUE TITLE
huge amount of lock files

### ISSUE THREAD

**Issue by jordiprats** [EnterpriseDB/barman#289]
Hi,
I'm currenly using barman 2.8. I've found that  there is a huge amount of "lock" files on the barman directory:

```
[root@barman barman]# ls -la | grep lock | wc -l
980
```

All of them look the same:

.SERVERBANE-xlogdb.lock

Containing some numbers, for example 32448. I guess this is a position

I can understand that it might be necessary but there are just too many and those files are no longer relevant for the backups we currently have. We have a 5 days retention but I can see files almost a year old (most likely when we set up the barman server

Could you please give me some insight of the prurpose of these files an whether can be removed?

kind regards,

**Comment by fluca1978** [comment]
The number within the file is the PID of the backup process.
The behavior seems to be confirmed also here <https://groups.google.com/forum/#!topic/pgbarman/gZXlr0ly6uk>

**Comment by jordiprats** [comment]
So, this is expected? Is something that I need to cleanup regularly? Is there a setting to delete the file once the backup is completed?

thanks,

**Comment by fluca1978** [comment]
I don't think it is expected, or at least I don't understand why this could be useful.
I think barman should clean up pid files as any service does, but in the meantime you can clean the directory pruning files that contain pids no more running. 
By the way, I don't think those files are requiring much disk space, after all 6-7 bytes per file, so it's not something that can run you out of disk space.

**Comment by amenonsen** [comment]
We're making some changes that could address this, so I've added this to the next release milestone.

**Comment by pct-cclausen** [comment]
I am also seeing this

**Comment by rfkarpinski** [comment]
Me too. Still exists in barman version:

[root@barman ~]# barman -v
3.7.0 Barman by EnterpriseDB (www.enterprisedb.com)

**Comment by shamil** [comment]
Happens to me as well Barman 3.9
