### ISSUE TITLE
identify_compression is unable to identify custom compression

### ISSUE THREAD

**Issue by Thoro** [EnterpriseDB/barman#292]
I was looking through the code for #291 and saw that identify_compression (https://github.com/2ndquadrant-it/barman/blob/1bcdd6bcbaed9bd0b5882bc9543036e967ff3368/barman/compression.py#L97) does not support the magic for the custom command.

By implementing this any algorithm could be used to actually compress on the postgres server side and send the compressed file via put-wal.

I was thinking about a "custom_compression_magic" that is provided as a hex key and is then set for the CustomCompressor.

```
custom_compression_magic = 0x425a68   # Bzip2
custom_compression_magic = 0x28b52ffd   # Zstd
custom_compression_magic = 0x377abcaf271c   # 7za
```

**Comment by Thoro** [comment]
I added a PR for this, not totally happy, since identify_compression is currently a class method, and I didn't want to rewrite all uses of it.

**Comment by mikewallace1979** [comment]
Thanks for making the PR @Thoro - I mentioned in a comment over on the PR but in the interests of visibility: The way barman currently "detects" custom compressed files is to try and match the magic for all supported compressions and default to the custom compression if no match is found (and a custom compression filter is configured). Using a `custom_compression_magic` config as suggested here would be an improvement on the current method.

**Comment by mikewallace1979** [comment]
> Using a custom_compression_magic config as suggested here would be an improvement on the current method.
Specifically, it allows us to detect pre-compressed WALs which have been compressed with the custom compression and therefore avoid compressing them a second time during archive.
