### ISSUE TITLE
Replication status shows own connection.

### ISSUE THREAD

**Issue by StormTide** [EnterpriseDB/barman#297]
After upgrading to 2.11-1.pgdg18.04+1 I noticed an extra Async WAL Streamer in my "barman replication-status all" output. 

  2. Async WAL streamer
     Application name: 
     Sync stage      : 1/3 1-safe
     Communication   : TCP/IP
     IP Address      : <ip> / Port: 52700 / Host: -
     User name       : streaming_barman
     Current state   : startup (async)
     WAL sender PID  : 8210
     Started at      : 2020-08-05 15:56:35.321601-04:00

It was behaving weird as the pid and port would change with every status check and the started time would be the time I called the command. Took me a while to figure out what was going on but I think there might be a regression in this cli output that its showing its own connection that it uses to get the replication status from pg_stat_replication/pg_replication_slots on the remote server.

**Comment by amenonsen** [comment]
As part of an effort to pick up maintenance of Barman, I'm closing this and many other old open issues in this repository.
