### ISSUE TITLE
ConsoleOutputWriter Error on barman list-server

### ISSUE THREAD

**Issue by maximumwoltage** [EnterpriseDB/barman#301]
EXCEPTION: The ConsoleOutputWriter writer does not support the "list_server" command
EXCEPTION: The ConsoleOutputWriter writer does not support the "status" command
EXCEPTION: The ConsoleOutputWriter writer does not support the "show_server" command
etc, etc, etc
Barman v 2.10
CentOS Linux 7 3.10.0-862.14.4.el7.x86_64

**Comment by gbartolini** [comment]
Hi,

It is quite difficult to help here due to lack of information and context. Also, given that 2.11 is already out, can you please update first and then allow us to reproduce the issue? For example, what are the commands you are executing?

Thanks,
Gabriele

**Comment by maximumwoltage** [comment]
When i run `yum --showduplicates list barman`, i only see 2.10-5.el7 available.

Also, here are some of the commands that i have run:
-bash-4.2$ barman list-server
EXCEPTION: The ConsoleOutputWriter writer does not support the "list_server" command

-bash-4.2$ barman show-server nt_prod
Server nt_prod:
	active: True
	archive_command: None
	archive_mode: None
	archiver: True
	archiver_batch_size: 0
	backup_directory: /pgbackup/barman/nate_prod
	backup_method: rsync
	backup_options: BackupOptions(['concurrent_backup'])
	bandwidth_limit: None
	barman_home: /pgbackup/barman
	barman_lock_directory: /pgbackup/barman
	basebackup_retry_sleep: 30
	basebackup_retry_times: 0
	basebackups_directory: /pgbackup/barman/nate_prod/base
	check_timeout: 30
	compression: gzip
	conninfo: host=ntprod user=postgres port=5432
	create_slot: manual
	current_xlog: None
	custom_compression_filter: None
	custom_decompression_filter: None
	data_directory: None
EXCEPTION: The ConsoleOutputWriter writer does not support the "show_server" command

**Comment by amenonsen** [comment]
I wasn't able to reproduce this (or rather, I wasn't able to find any obvious explanation). Please reopen with more details if you can reproduce this with Barman 2.13, which is out now.
