### ISSUE TITLE
wal_keep_segments breaking change to wal_keep_size in PG 13

### ISSUE THREAD

**Issue by kapouer** [EnterpriseDB/barman#302]
Hi,

i gave a shot to postgres 13 with barman 2.11, and got

```
2020-09-26 01:24:13.343 CEST [604692] barman@postgres ERROR:  unrecognized configuration parameter "wal_keep_segments"
2020-09-26 01:24:13.343 CEST [604692] barman@postgres STATEMENT:  SHOW "wal_keep_segments"
2020-09-26 01:24:13.344 CEST [604692] barman@postgres ERROR:  current transaction is aborted, commands ignored until end of transaction block
2020-09-26 01:24:13.344 CEST [604692] barman@postgres STATEMENT:  SELECT 1
```
Cheers !

**Comment by albertosrocha** [comment]
I have the same issue using barman v2.12 and PostgreSQL 13.

`
barman@postgres ERROR:  unrecognized configuration parameter "wal_keep_segments"
barman@postgres STATEMENT:  SHOW "wal_keep_segments"
barman@postgres ERROR:  current transaction is aborted, commands ignored until end of transaction block
barman@postgres STATEMENT:  SELECT 1
`

**Comment by mrechte** [comment]
Hello. Why is this issue still not fixed, it generates hundreds of errors in the PG log file ?

**Comment by kapouer** [comment]
Ping ? i just realized i forgot to force-push a fix for the small typo in that commit.

**Comment by daamien** [comment]
Hi @mnencia ! 

Any news on this bug ? The MR #303 looks good to me !

**Comment by amenonsen** [comment]
I've fixed this recently. It will be included in the next Barman release.

**Comment by daamien** [comment]
Thanks ! Is there a timeline for the next release ?

**Comment by amenonsen** [comment]
I'm still going through open issues and putting together a list of things to do for the release. I can't make any promises about the timeline yet, but I hope to do it in the next couple of weeks.

**Comment by amari-at4** [comment]
Is there a workaroun to avoid this?

**Comment by dstoyanovi** [comment]
Today I upgraded one of our PostgreSQL DB to 13, and hit the same issue.  PG13 is more thant half year old, when we could be expect a new version with fix.

**Comment by mikewallace1979** [comment]
This fix is going out in 2.12.1 which should be available this week.

**Comment by shamil** [comment]
@mikewallace1979 

I see that `2.12.1` released but not available in the postgres apt repo. Before acquired by EDB all barman releases also pushed to https://apt.postgresql.org. Is this still will be the case?

**Comment by kapouer** [comment]
@shamil you just need to wait a bit i guess. However github issues are not made to discuss everything in one single thread...

**Comment by mikewallace1979** [comment]
@shamil The intention is that barman releases will continue to be made available in all the usual places.

**Comment by dstoyanovi** [comment]
Fixed, 10x
