### ISSUE TITLE
barman-cloud-backup does not provide a database argument

### ISSUE THREAD

**Issue by vtoupet** [EnterpriseDB/barman#307]
I am running a dockerize image of postgresql. I would like to perform the backup from the host machine and therefore PG database is reachable through IP

I am running the following command:
`PGPASSWORD=mypassword barman-cloud-backup -P barman-cloud -h 127.0.0.1 -U my_user  -e AES256 -j --immediate-checkpoint -J 4 s3://remote_s3_path/ pg12`

but I get this error: `ERROR: Cannot connect to postgres: FATAL:  database "django" does not exist`

Unfortunately there is no way to select a database in the command line

I am stuck and I cannot perform a backup

**Comment by bdoublet91** [comment]
Any updates on this ?
Actually I use the postgres account to perform backup because by default, when you don't specify database, it used the username as postgres db name so postgres database but I would use a service account without create the associated database so a -d option would be appreciate :)

**Comment by pguser4ever** [comment]
this worked for me 
 
barman-cloud-backup -e AES256 -j --immediate-checkpoint -v --host <hostname> -p 50047 -U whusr s3://barman-s3-backup/ whdb
2021-07-06 09:32:31,127 [10754] INFO: Found credentials in shared credentials file: ~/.aws/credentials
2021-07-06 09:32:31,395 [10754] INFO: Starting backup '20210706T093231'
2021-07-06 09:32:31,413 [10754] INFO:   16385, tswhdb01, /pg/pgdata/whdb/data/tswhdb01
2021-07-06 09:32:31,413 [10754] INFO:   16386, tsuserspace, /pg/pgdata/whdb/data/tsuserspace1
2021-07-06 09:32:31,413 [10754] INFO:   16387, tempspace1, /pg/pgtemp/whdb/data
......

"localhost" and "portnr" working as well
barman-cloud-backup -e AES256 -j --immediate-checkpoint -v --host localhost -p 50047 -U whusr s3://barman-s3-backup/ whdb

**Comment by mikewallace1979** [comment]
If we add `-d` to the argument parser and then add `dbname` to [build_conninfo](https://github.com/EnterpriseDB/barman/blob/f99ab593f290151403cfdbdb623d3f123dc4e425/barman/clients/cloud_backup.py#L53-L64) then that is about all that is needed for this one.

**Comment by mikewallace1979** [comment]
If `-d` is not provided we should default to the `postgres` database
