### ISSUE TITLE
Possible documentation issues

### ISSUE THREAD

**Issue by x-yuri** [EnterpriseDB/barman#312]
[The documentation][1] says:

> ```
> restore_command = 'sudo -u barman barman get-wal SERVER %f > %p'
> ```
> Please note that the `get-wal` command should always be invoked as `barman` user, and that it requires the correct permission to read the WAL files from the catalog. This is the reason why we are using `sudo -u barman` in the example.

But I can see that `barman` [drops privileges][2] supposedly every time it gets invoked. Shouldn't the documentation be corrected?

[1]: https://github.com/2ndquadrant-it/barman/blob/6397ca4/doc/manual/42-server-commands.en.md#get-wal
[2]: https://github.com/2ndquadrant-it/barman/blob/a577cb3/barman/cli.py#L1029

**Comment by x-yuri** [comment]
I think I'll post here other possible documentation issues.

> The WAL archive is contained in the `xlog.db` file and every server managed by Barman has its own copy.

https://github.com/2ndquadrant-it/barman/blob/6397ca4/doc/manual/42-server-commands.en.md#rebuild-xlogdb

From what I can see, it's rather "every Barman instance," or "every server running Barman." "Every server managed by Barman" makes me think of the PostgreSQL servers, that are backed up by Barman (think `barman list-server`).

**Comment by x-yuri** [comment]
> Setting active=false is a good practice when adding a new node to Barman. Server.

https://github.com/2ndquadrant-it/barman/blob/509cde7/doc/barman.5.d/50-active.md

Why exactly?

**Comment by x-yuri** [comment]
> Normally, during backup operations, Barman uses PostgreSQL native functions pg_start_backup and pg_stop_backup for exclusive backup.

https://github.com/2ndquadrant-it/barman/blob/2621864/doc/manual/50-feature-details.en.md#concurrent-backup-and-backup-from-a-standby

That only holds when [`backup_method = rsync`][2]. When `backup_method = postgres` though the only option is a [concurrent backup][1].

It should be stated that the this section addresses only `backup_method = rsync`. Some minor corrections might also be in order.

[1]: https://github.com/2ndquadrant-it/barman/blob/2621864/barman/backup_executor.py#L233-L247
[2]: https://github.com/2ndquadrant-it/barman/blob/2621864/barman/backup_executor.py#L698-L706

**Comment by amenonsen** [comment]
> [The documentation](https://github.com/2ndquadrant-it/barman/blob/6397ca4/doc/manual/42-server-commands.en.md#get-wal) says:
> 
> > ```
> > restore_command = 'sudo -u barman barman get-wal SERVER %f > %p'
> > ```

Yes, this is correct in case of a local recovery (i.e., where Barman is running on the same server as Postgres).

> But I can see that `barman` [drops privileges](https://github.com/2ndquadrant-it/barman/blob/a577cb3/barman/cli.py#L1029) supposedly every time it gets invoked. Shouldn't the documentation be corrected?

No. Running `barman get-wal` from `restore_command` would by default run it as the postgres user, and no amount of dropping privileges would cause it to run as the barman user. Therefore sudo is required in this case.

**Comment by amenonsen** [comment]
> > Setting active=false is a good practice when adding a new node to Barman. Server.
> 
> Why exactly?

I've reworded this to "When adding a new server to Barman, we suggest setting `active=false` at first, making sure that `barman check` shows no problems, and only then activating the server. This will avoid spamming the Barman logs with errors during the initial setup."

**Comment by amenonsen** [comment]
> > Normally, during backup operations, Barman uses PostgreSQL native functions pg_start_backup and pg_stop_backup for exclusive backup. […]
> 
> That only holds when [`backup_method = rsync`]

Yes, and that is currently the default mode of operation, so "Normally, … Barman uses … pg_start_backup" is true by way of explanation of what concurrent backups are for (which is the section you're quoting from).

However, now that 9.5 is EOL, we will be changing the default at some point, as mentioned a few lines further down:

```
> **IMPORTANT:** When PostgreSQL 9.5 is declared EOL by the Community,
> Barman will by default set `backup_options` to `concurrent_backup`.
> Support for `pgespresso` will be ceased then.
```

So for now, I'm not making any changes here. When we change the default, I'll go through the docs and make sure the text is consistent. Thanks for the report.
