### ISSUE TITLE
barman switch-wal <server> as regular user results in: EXCEPTION:  See log file for more details.

### ISSUE THREAD

**Issue by epolkerman** [EnterpriseDB/barman#319]
barman 2.12
postgresql 13.1

Following configuration for server:
```
[ssh-pg-master]
description =  "Master PostgreSQL Database (via ssh)"
ssh_command = ssh postgres@<ip-address>
conninfo = host=<ip-address> user=barman dbname=postgres

backup_method = rsync
backup_options = exclusive_backup
reuse_backup = link
archiver = on

streaming_archiver = on
slot_name = barman
```
User barman is a regular user with the required set of privileges.

Run following command:
`barman --log-level DEBUG switch-wal --force ssh-pg-master`
As expected  and described in the documentation this will fail because the --force option requires superuser attritbute:
ERROR: Barman switch-wal requires superuser rights

Run command without --force:
`barman --log-level DEBUG switch-wal ssh-pg-master`

It is expected that the command runs correctly, but in stead it returns an exception:
EXCEPTION: 
See log file for more details.

Checking the postgresql logfile it can be seen that the same wrong query is used to check if user has all needed privileges as described in issue #318 

From barman logfile a python exception can be seen in stead of a more user friendly error message. 
Proposal:
Catch current exception and give a correct warning message (when conditions aren't met) like:
Privileges for PostgreSQL backup functions are required (see documentation)

[barman2.log](https://github.com/2ndquadrant-it/barman/files/5848791/barman2.log)
[postgres2.log](https://github.com/2ndquadrant-it/barman/files/5848793/postgres2.log)

**Comment by epolkerman** [comment]
Also barman replication-status <server> fails with: EXCEPTION: See logfile for more details.

Probably all command requireing a check on needed privileges will fail using wrong query an poor exception handling

**Comment by amenonsen** [comment]
Thanks for the report. Since this is related to #318, I've added it to the next release milestone as well.
