### ISSUE TITLE
Stop logging for Barman diagnose command

### ISSUE THREAD

**Issue by NivedithaD** [EnterpriseDB/barman#320]
We are using "barman diagnose" command for monitoring purposes, this command is logging the output to the log file.  It's cluttering the logs and bloating the logfiles.

Adding a log=False here: https://github.com/2ndquadrant-it/barman/blob/master/barman/diagnose.py#L91 should fix this issue.

**Comment by amenonsen** [comment]
Thanks for the suggestion, I've added this to the next milestone.
