### ISSUE TITLE
restore of postgresql 13 backup fails with : cannot stat 'barman_wal/<xyz>.history': No such file or directory

### ISSUE THREAD

**Issue by thomasreinecke** [EnterpriseDB/barman#323]
barman: v2.11
postgresql: 13
setup: dedicated `barman` server (ubuntu: 20.10), `database-1` server with postgresql 13 (ubuntu: 20.04)

Backup can be taken properly, restored as `barman` user with following command from `backup` server
```
barman recover \
  --target-time "2021-02-11 10:46:54.279284+00:00" \
  --remote-ssh-command "ssh postgres@database-1" \
 database-1 20210211T104650 /var/lib/postgresql/13/main
```

attempt to start postgres on the `database-1` host with `/usr/lib/postgresql/13/bin/pg_ctl -D /var/lib/postgresql/13/main start` produces the following log:

```
postgres@database-1:~$ /usr/lib/postgresql/13/bin/pg_ctl -D /var/lib/postgresql/13/main start
waiting for server to start....2021-02-11 10:53:20.986 UTC [4425] LOG:  starting PostgreSQL 13.1 (Ubuntu 13.1-1.pgdg20.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0, 64-bit
2021-02-11 10:53:20.987 UTC [4425] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2021-02-11 10:53:20.987 UTC [4425] LOG:  listening on IPv6 address "::", port 5432
2021-02-11 10:53:20.989 UTC [4425] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2021-02-11 10:53:20.993 UTC [4427] LOG:  database system was interrupted; last known up at 2021-02-11 10:46:50 UTC
2021-02-11 10:53:20.993 UTC [4427] LOG:  creating missing WAL directory "pg_wal/archive_status"
cp: cannot stat 'barman_wal/00000002.history': No such file or directory
2021-02-11 10:53:21.017 UTC [4427] LOG:  starting point-in-time recovery to 2021-02-11 10:46:54.279284+00
2021-02-11 10:53:21.020 UTC [4427] LOG:  restored log file "000000010000000000000009" from archive
2021-02-11 10:53:21.025 UTC [4427] LOG:  redo starts at 0/9000028
2021-02-11 10:53:21.026 UTC [4427] LOG:  consistent recovery state reached at 0/9000138
2021-02-11 10:53:21.026 UTC [4425] LOG:  database system is ready to accept read only connections
cp: cannot stat 'barman_wal/00000001000000000000000A': No such file or directory
2021-02-11 10:53:21.027 UTC [4427] LOG:  redo done at 0/9000138
2021-02-11 10:53:21.027 UTC [4427] FATAL:  recovery ended before configured recovery target was reached
2021-02-11 10:53:21.028 UTC [4425] LOG:  startup process (PID 4427) exited with exit code 1
2021-02-11 10:53:21.028 UTC [4425] LOG:  terminating any other active server processes
2021-02-11 10:53:21.030 UTC [4425] LOG:  database system is shut down
 stopped waiting
pg_ctl: could not start server
```

`backup` server `/etc/barman.conf` contents:
```
[barman]
barman_home = /backup/barman
barman_user = barman
log_file = /backup/barman/barman.log
compression = gzip
reuse_backup = link
backup_method = rsync
archiver = on
immediate_checkpoint = true
basebackup_retry_times = 3
basebackup_retry_sleep = 30
last_backup_maximum_age = 1 DAYS

[database-1]
description = “database-1”
ssh_command = ssh postgres@database-1
conninfo = host=database-1 user=postgres port=5432
retention_policy_mode = auto
retention_policy = RECOVERY WINDOW OF 7 days
wal_retention_policy = main
backup_options = exclusive_backup
```

The described setup works well with postgresql 12. I also tried ubuntu 20.10 for the db server, this doesn't seem to have relevance.

**Comment by tumbl3w33d** [comment]
I want to confirm this bug as it keeps me busy for a while already. I've done recovery tests several times by completely purging postgres (incl. its data folder) from the machine and reinstalling everything using ansible (i.e., reproducible setup).

Fun fact - I have noticed several times that executing the exact same recovery command twice in a row yields a different result. I've checked the postgres data folder hash using `find . -type f -print0 | sort -z | xargs -0 sha1sum | sha1sum` and on the second recovery I get a different result than after first recovery. But from then on it's stable, i.e., further recoveries result in the same folder hash and the postgres process starts with succeeding recovery.

Unfortunately, I couldn't find a stable, reliable way to recover yet.

OS: Debian 10
Postgres: 13.3-1.pgdg100+1
Barman: 2.12.1-1.buster+1

**Comment by tumbl3w33d** [comment]
I did it. Finally managed to automate all the way through recovering my master and a standby from a barman backup. I'm not 100% sure, but I think what avoided the error described here was adding `--get-wal` to the recover command, which essentially changes the `restore_command` in `postgresql.auto.conf` to something like `restore_command = 'barman-wal-restore -P -U <user> <barman host> <server as configured in barman> %f %p'`. This allows to restore from partial WAL files. You might give it a try, maybe it avoids this error for you as well.

**Comment by tumbl3w33d** [comment]
After passing on my recovery playbooks to my colleague for testing together we noticed, this bug is still there. The workaround that works for us is choosing a slightly (e.g., 5 min) earlier timestamp to recover from. A recently created (for the recovery test) base backup didn't work in that case so we needed to choose an earlier backup id to be able to shift the timestamp back to the past.

Long story short - you get around it somehow, but it seems broken for a reason I can't explain.

**Comment by amenonsen** [comment]
Using `barman recover … --get-wal` is the right thing to do, so that Postgres requests WAL automatically from Barman as required.

However, the earliest recovery target time you can use for a backup started at time X is not X, but the _end_ time of the backup. This is nothing to do with Barman, but just how Postgres works. In the first message above, the backup id is 20210211T104650 (which should be very close to the start time of the backup). This makes it very unlikely that `--target-time "2021-02-11 10:46:54.279284+00:00"` could possibly work (unless the entire backup finished in <4s).

So I don't think there is a problem here, and I'm closing this issue now.
