### ISSUE TITLE
barman cloud and remote dedicated server

### ISSUE THREAD

**Issue by bdoublet91** [EnterpriseDB/barman#326]
Hi.
I have tested barman with remote server and wal streaming replication of my postgresql server.
I have also tested barman cloud to push on a s3 bucket in a dedicated server but something went wrong.
the file pg_control is not found when I did the backup

barman-cloud-backup -e AES256 -j --immediate-checkpoint -J 4 -h ***  -U ***-P barman-cloud s3://***
2021-03-03 20:00:22,135 [346] ERROR: Backup failed uploading data ([Errno 2] No such file or directory: '/var/lib/postgresql/11/main/global/pg_control')
Exception ignored in: <bound method _Stream.__del__ of <tarfile._Stream object at 0x7f2aa2ace550>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/tarfile.py", line 419, in __del__
    self.close()
  File "/usr/lib/python3.6/tarfile.py", line 467, in close
    self.fileobj.write(self.buf)
  File "/usr/lib/python3/dist-packages/barman/cloud.py", line 195, in write
    self.buffer = self._buffer()
  File "/usr/lib/python3.6/tempfile.py", line 690, in NamedTemporaryFile
    (fd, name) = _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "/usr/lib/python3.6/tempfile.py", line 401, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/barman-cloud-backup-400haj93/barman-upload-_ff81kov.part'

Does it mean I can't use barman cloud on a remote dedicated  server to backup postgres data with barman cloud ?
If yes, why ? I mean, it better to make the dedicated server working instead of the postgres server to avoid any over workloads ?

Second question is: barman-cloud doesnt support database param, that means I have to connect with a postgresql account with already created database. In my case, I have an account replication which doesnt have database so is there a way to connect with an account and specify postgres database for example like barman conninfo ?

Thanks

**Comment by amenonsen** [comment]
> Does it mean I can't use barman cloud on a remote dedicated server to backup postgres data with barman cloud ?
> If yes, why ? I mean, it better to make the dedicated server working instead of the postgres server to avoid any over workloads ?

I'm not sure I understand the question, but if you are trying to run `barman-cloud-backup` on machine a to take a backup from postgres on machine b, then no, that won't work. However, in Barman 2.13, you can use barman-cloud-backup and barman-cloud-wal-archive as hook scripts on a Barman server to upload a backup to cloud storage.

> Second question is: barman-cloud doesnt support database param, that means I have to connect with a postgresql account with already created database. In my case, I have an account replication which doesnt have database so is there a way to connect with an account and specify postgres database for example like barman conninfo ?

barman-cloud-backup from the 2.13 release supports a `-d dbname` option.
