### ISSUE TITLE
barman-cloud-backup Does not preserve pg_wal folder if it is a symbolic link / `barman-wal-restore` does not create empty pg_wal folder

### ISSUE THREAD

**Issue by bonesmoses** [EnterpriseDB/barman#327]
The `barman-cloud-backup` utility does not preserve the `pg_wal / pg_xlog` folder when storing cloud objects, if the folder is a symbolic link. This is a fairly common configuration in Postgres clusters, and causes `barman-cloud-restore` to fail when attempting to restore WAL files, as the directory does not exist.

While it is understandable for `barman-cloud-backup` not to follow symbolic links, it should either create an empty stub folder in the backup if such a link exists, or `barman-cloud-restore` should ensure a `pg_wal / pg_xlog` folder exists for restored WAL files to reside in. If one was not restored from the backup itself, Barman should create it.

**Comment by Kamal-Villupuram** [comment]
Any update on this issue?

**Comment by amenonsen** [comment]
I have a fix for this, which will be included in the 2.13 release.

**Comment by Kamalbharath** [comment]
Thanks for the update. when 2.13 will be released?

**Comment by amenonsen** [comment]
Next week.

**Comment by Kamalbharath** [comment]
Thanks.  We opended also at the same time for same kind link issue.  is this covered on this release?
https://github.com/EnterpriseDB/barman/issues/325

**Comment by amenonsen** [comment]
> Thanks. We opended also at the same time for same kind link issue. is this covered on this release?
> #325

Yes, it's WIP.
