### ISSUE TITLE
barman-cloud-restore and missing links for tablespaces 

### ISSUE THREAD

**Issue by pguser4ever** [EnterpriseDB/barman#343]
Hello
We like Barman and use multiple Barman servers in our production envionment, but to start using the barman-cloud stuff there are several things that causes problems for us. Most of the problems have been reported earlier but not sure about missing links for tablespaces after barman-cloud-wal-restore 

1/
barman-cloud-backup seems to be working but we need support for pg_wal and symbolic link 
 agree with case #327  it is very common to use like we do 
(barman-cloud-backup -e AES256 -j  -v  -J 4 s3://barman-s3-backup/ whdb)

2/ 
barman-cloud-restore seems to working as well and used recover param. 
restore_command = 'barman-cloud-wal-restore s3://barman-s3-backup whdb %f %p'
recovery_target_timeline = 'latest'  
But also got  ERROR: Barman cloud WAL restore exception: coercing to Unicode: need string or buffer, StreamingBody found 
same as #325 ? 
(barman-cloud-restore -e AES256 -v s3://barman-s3-backup whdb 20210702T121955 /pg/pgcluster/whdb/data)

3/ 
Copy all the  wal files to local disk  
(aws s3 cp s3://barman-s3-backup/whdb/wals/0000018F00000006/  restore_dir --recursive)

changed  restore_command 
restore_command = 'cp /pg/pglog/whdb/restore_dir/%f "%p"'

4/ 
started recovery and it worked, instance started up 
but connect failed what ?? 
psql: error: could not connect to server: FATAL:  database "whdb" does not exist
DETAIL:  The database subdirectory "pg_tblspc/16386/PG_12_201909212/16388" is missing

Same case as  #330 ?  maybe 
But creating links to tablepaces solved the problem 

 ln -s /pg/pgdata/whdb/data/tswhdb01 /pg/pgcluster/whdb/data/pg_tblspc/16385
 ln -s /pg/pgdata/whdb/data/tsuserspace1  /pg/pgcluster/whdb/data/pg_tblspc/16386
 ln -s  /pg/pgtemp/whdb/data /pg/pgcluster/whdb/data/16387

psql (12.4)
Type "help" for help.
whdb=#

**Comment by amenonsen** [comment]
About (1), I have a fix for #327 now.

About (2), I'm not sure if it's the same as #325, but we're looking into that. Please provide the complete backtrace if you can.

I'll investigate the tablespace thing now.

**Comment by amenonsen** [comment]
@pguser4ever #355 should address both (1) and (4) above. Comments welcome.

(2) still under investigation.
