### ISSUE TITLE
Implement barman-cloud-backup-delete

### ISSUE THREAD

**Issue by amenonsen** [EnterpriseDB/barman#368]
Right now, there's no way to delete the cloud backups shown by `barman-cloud-backup-list`.

The new `barman-cloud-backup-delete` command should (a) allow specific backup ids to be deleted, just like `barman delete`, and (b) also allow expiration policies to be applied to cloud backups (using the expiration code that is already in Barman).

**Comment by alexscottthatcham** [comment]
If it can also clean up unneeded WAL files, that would also be appreciated!
