### ISSUE TITLE
Backup failed: No such file or directory

### ISSUE THREAD

**Issue by cjchang1688** [EnterpriseDB/barman#372]
Barman version: 2.11

ERROR: Backup failed calculating backup size. 
DETAILS: [Errno 2] No such file or directory:
'/backups/postgres-05/base/20210803T065001/data/pg_tblspc/771814060'

I went to the database server and found the tablespace link is there.

postgres@postgres-05:~/10/main/pg_tblspc$ ls -l 771814060
lrwxrwxrwx 1 postgres postgres 35 Aug  3 11:03 771814060 -> /data1/xxxxx_1627945382_d

Did the backup fail because the tablespace was created while Barman was backing up the database?

**Comment by martinmarques** [comment]
I'm closing this as there aren't enough details to assess, and it's been a long time since it happened. Please do come back if you see this again, or send it to the Barman google group
