### ISSUE TITLE
Copy barman backup to another barman machine

### ISSUE THREAD

**Issue by mbartlomiejczyk** [EnterpriseDB/barman#375]
Is there any option to copy backup created by barman to another barman machine?

**Comment by mikewallace1979** [comment]
It is possible to configure barman as a passive node such that the source of the backups is another barman server - take a look at the docs for the [Geographical redundancy](https://docs.pgbarman.org/release/2.13/#geographical-redundancy) feature.

**Comment by mikewallace1979** [comment]
@mbartlomiejczyk I'm closing this for now however feel free to reopen if you have a requirement which isn't covered by my previous comment
