### ISSUE TITLE
pg_receivexlog -> pg_receivewal

### ISSUE THREAD

**Issue by devrimgunduz-edb** [EnterpriseDB/barman#379]
Hi,

Attached patch changes pg_receivexlog to pg_receivewal where needed.

Regards, Devrim

[barman-pg_receivexlog-pg_receivewal.patch.txt](https://github.com/EnterpriseDB/barman/files/7014393/barman-pg_receivexlog-pg_receivewal.patch.txt)

**Comment by amenonsen** [comment]
Thanks for the patch. We'll look into the changes.
