### ISSUE TITLE
can barman automatic backup when the postgresql server is down?

### ISSUE THREAD

**Issue by xilu0** [EnterpriseDB/barman#381]
hi, thank you for developing barman!
I find that the data lose when the PostgreSQL server is down, because I can't execute the backup command.
so can barman automatic backup when the PostgreSQL server is down?
I use streaming replication.

have a good day.

**Comment by mikewallace1979** [comment]
hi @xilu0 - barman needs to be able to communicate with PostgreSQL in order to co-ordinate the backup so `barman backup` is not going to work while PostgreSQL is down.
