### ISSUE TITLE
argh dependency is unmaintained

### ISSUE THREAD

**Issue by stratakis** [EnterpriseDB/barman#398]
Hello,

The argh dependency for barman is unmaintained since 2016: https://github.com/neithere/argh/

Would you consider migrating to something else, such python's stdlib argparse?

**Comment by amenonsen** [comment]
Hi. Thanks for letting us know (I had no idea it was unmaintained). I agree with you that it would be good to get rid of the extra dependency, but right now I don't have any sense of how much work that would involve. I'll have a look.

**Comment by stratakis** [comment]
An example of a migrating project: https://github.com/gorakhargosh/watchdog/pull/836/

**Comment by amenonsen** [comment]
Thanks for the link. That's a bit more work than I'd imagined, but for the most part it's fairly straightforward and the result seems good. So I think we would like to do this at some point, but no specific ETA. (However, if anyone wants to work on this and open a PR, we'd welcome the effort.)
