### ISSUE TITLE
More a recommendation than an issue...

### ISSUE THREAD

**Issue by DaleBetts** [EnterpriseDB/barman#41]
I've noticed that within the "barman check <server>" output you have a "failed backups" check. However this doesn't seem to calculate correctly, but i think that the problem stems from the barman list-backup <server> and the fact that a backup that loses it PID, never fails.

See backup: 
[barman@em-vus-pgbuilder ~]$ barman list-backup ros_management
ros_management 20160531T165506 - STARTED

Even though i deliberately killed the PID here (I'm trying to write some backup failure alerts), the barman backup status remains as "started" indefinite and never turns to a "failed" state. I assume that this is because there's no longer the communication, but I'd expect a timeout or perhaps some kind of PID failure detection?

Thanks and keep up the great work

**Comment by amenonsen** [comment]
Thanks for the suggestion—improved detection of dead/stalled processes is something we do intend to work on in future.

As part of an effort to pick up maintenance of Barman, I'm closing this and many other old open issues in this repository.
