### ISSUE TITLE
 barman.cli ERROR: local variable 'line' referenced before assignment

### ISSUE THREAD

**Issue by sebasmannem** [EnterpriseDB/barman#458]
I ran into this error while running a restore.
Command:
   `barman -c ~/barman-restore.conf recover --get-wal --remote-ssh-command 'ssh postgres@server' server 20211122T010151 /postgres/12/recover`
Error in the logfile:

> 2021-11-24 12:13:10,614 [1418729] barman.cli ERROR: local variable 'line' referenced before assignment
> See log file for more details.
> Traceback (most recent call last):
>   File "/usr/lib/python3.6/site-packages/barman/cli.py", line 1640, in main
>     p.dispatch(pre_call=global_config)
>   File "/usr/lib/python3.6/site-packages/argh/helpers.py", line 55, in dispatch
>     return dispatch(self, *args, **kwargs)
>   File "/usr/lib/python3.6/site-packages/argh/dispatching.py", line 174, in dispatch
>     for line in lines:
>   File "/usr/lib/python3.6/site-packages/argh/dispatching.py", line 277, in _execute_command
>     for line in result:
>   File "/usr/lib/python3.6/site-packages/argh/dispatching.py", line 231, in _call
>     result = function(namespace_obj)
>   File "/usr/lib/python3.6/site-packages/barman/cli.py", line 647, in recover
>     standby_mode=getattr(args, "standby_mode", None),
>   File "/usr/lib/python3.6/site-packages/barman/server.py", line 1679, in recover
>     backup_info, dest, tablespaces, remote_command, **kwargs
>   File "/usr/lib/python3.6/site-packages/barman/backup.py", line 754, in recover
>     **kwargs
>   File "/usr/lib/python3.6/site-packages/barman/recovery_executor.py", line 342, in recover
>     self._analyse_temporary_config_files(recovery_info)
>   File "/usr/lib/python3.6/site-packages/barman/recovery_executor.py", line 1191, in _analyse_temporary_config_files
>     conf_file, self.MANGLE_OPTIONS, "%s.origin" % conf_file, append_lines
>   File "/usr/lib/python3.6/site-packages/barman/recovery_executor.py", line 1281, in _pg_config_mangle
>     if line[-1] != "\n".encode("utf-8"):
> UnboundLocalError: local variable 'line' referenced before assignment

I backtracked it to [these 2 lines in the code](https://github.com/EnterpriseDB/barman/blob/d33b484045d08855cbbbd57296b1cea838cf8432/barman/recovery_executor.py#L1281).

If I place hem after [this line](https://github.com/EnterpriseDB/barman/blob/d33b484045d08855cbbbd57296b1cea838cf8432/barman/recovery_executor.py#L1278) everything works as expected.

If you want me to I can issue a tiny Pull Request...

**Comment by sebasmannem** [comment]
Diff:

> diff --git a/barman/recovery_executor.py b/barman/recovery_executor.py
> index 0f532a8..c849240 100644
> --- a/barman/recovery_executor.py
> +++ b/barman/recovery_executor.py
> @@ -1276,10 +1276,10 @@ class RecoveryExecutor(object):
>                          )
>                          continue
>                  f.write(line)
> -            # Append content of append_lises array
> -            if append_lines:
>                  if line[-1] != "\n".encode("utf-8"):
>                      f.write("\n".encode("utf-8"))
> +            # Append content of append_lises array
> +            if append_lines:
>                  f.write(("\n".join(append_lines) + "\n").encode("utf-8"))
> 
>          # Restore original permissions

**Comment by sebasmannem** [comment]
By the way, I now noticed that my postgresql.conf file has double \n's (empty lines between every line).
After removing the lines it works better. We probably should leave them out entirely...

**Comment by didiermichel** [comment]
Hi @sebasmannem, 
I had  a look at the issue.
It seems you encountered specific conditions:
_empty auto configuration file_ and _append_lines defined_

I have pushed a first proposition. It still have to be tested.
