### ISSUE TITLE
can you provide checksums for tar archives?

### ISSUE THREAD

**Issue by vrms** [EnterpriseDB/barman#460]
I assume this is the barman repository and source of truth startgin with version 2.13.

would it be possible to provide downloadable checksums for the .tar.gz archives on your [download page](https://github.com/EnterpriseDB/barman/releases)?

That would add an extra layer of trustworthyness to the project

**Comment by didiermichel** [comment]
Hello @vrms.  It seems a good Idea. I will add it from 2.13

**Comment by vrms** [comment]
there is an error with the 2.15 md5. It points to 2.13.md5
