### ISSUE TITLE
rsync backup fails when rsync return code is `23` and rsync process is `sender`

### ISSUE THREAD

**Issue by barthisrael** [EnterpriseDB/barman#463]
Currently barman has the regex `VANISHED_RE` defined at [barman.copy_controller.RsyncCopyController](https://github.com/EnterpriseDB/barman/blob/master/barman/copy_controller.py#L262) which is in charge of filtering some rsync error messages out when its return code is `23` (Partial transfer due to error), and allowing the backup to finish successfully.

The last piece of the regex in is charge of filtering out messages like this:

```
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1178) [sender=3.1.2]
```

But at the moment it covers only the `generator` and `receiver` rsync processes, so the above message is not matched. In order to do so, we should also cover the `sender` process.

**Comment by mikewallace1979** [comment]
This looks like it was fixed but the issue got left open - will close and assign to the relevant release milestone.
