### ISSUE TITLE
Speed up barman cloud WAL archiving

### ISSUE THREAD

**Issue by mikewallace1979** [EnterpriseDB/barman#472]
`barman-cloud-wal-archive` can take around 120s to upload a 16MB WAL. This is not amazing performance and can lead to WALs backing up under modest workloads.

The goal of this ticket is to:

1. Understand why WAL upload is taking so long, and:
2. Speed up the WAL upload either by making better/aternative use of the cloud provider API.

**Comment by theadamwright** [comment]
On testing archiving a WAL file on Postgres pod running in AKS to Azure Blob Storage, the time was ~2 seconds (not 120s) to upload a single 16MB WAL.

**Comment by mikewallace1979** [comment]
I did some experiments using barman cloud on an Azure VM to archive WALs to Azure storage container in different regions. While I was not able to reproduce any long archive times within an Azure region, I did find that the archive times between different Azure regions are quite variable with many WAL archive operations taking over 10 seconds and some outliers taking up to 200 seconds.

After taking a closer look at the Azure Python SDK it is possible to reduce the 64MB minimum required to use the concurrent chunked uploader via the `max_single_put_size` option when creating a container client. Reducing this to a value less than the size of a WAL segment ensures the concurrent uploader is used which means we can set `max_concurrency` on the upload request. The final parameter to worry about is `max_block_size` which defines the chunk size - this should be set based on the WAL segment size so that the number of chunks >= `max_concurrency`.

If we do all these things then the Azure client will upload chunks *in parallel*. When transferring within an Azure region this has little effect on the overall upload time however when transferring to remote regions we see a significant improvement in the distribution of request times and a reduction in the number and severity of outliers.

The following histograms show archive times for a 32MB WAL from an Azure VM in eu-west to storage containers in us-east and us-west with concurrency values of 1, 2, 4, 8 and 16:

| eu-west to us-east | eu-west to us-west |
|--------------------|---------------------|
|![](https://gist.githubusercontent.com/mikewallace1979/2100dca8c1986d55c5b85c924288f872/raw/7ae7a2621f6b7a1774fba91f867a360b3bd11957/32mb_eu_us-east_.png)|![](https://gist.githubusercontent.com/mikewallace1979/2100dca8c1986d55c5b85c924288f872/raw/7ae7a2621f6b7a1774fba91f867a360b3bd11957/32mb_eu_us-west_.png)|

More details can be found on the [barman wiki](https://github.com/EnterpriseDB/barman/wiki/Barman-cloud-WAL-archive-performance-in-Azure).

Based on this it seems sensible to expose some ability to configure WAL upload concurrency in barman cloud. We could do this either by exposing the Azure parameters directly or by choosing some default chunk vs concurrency ratio and just having a `--concurrency` or `--jobs` (to match `barman-cloud-backup`) parameter.

**Comment by mikewallace1979** [comment]
@ba-edb Tests repeated with 16MB and 64MB WAL sizes. I changed to a fixed block size rather than adjusting it such that the number of chunks uploaded would always equal the concurrency. Instead the block size is fixed at the size which yields `number of blocks == concurrency` at the highest tested concurrency.

|16MB WAL|64MB WAL|
|-----------|-----------|
|![](https://gist.githubusercontent.com/mikewallace1979/2100dca8c1986d55c5b85c924288f872/raw/1ad875eb3bc22bc63a7fe986aef8e04a6e2ada11/16mb_eu_us-east_1.png)|![](https://gist.githubusercontent.com/mikewallace1979/2100dca8c1986d55c5b85c924288f872/raw/1ad875eb3bc22bc63a7fe986aef8e04a6e2ada11/64mb_eu_us-east_4.png)|
|![](https://gist.githubusercontent.com/mikewallace1979/2100dca8c1986d55c5b85c924288f872/raw/1ad875eb3bc22bc63a7fe986aef8e04a6e2ada11/16mb_eu_us-west_1.png)|![](https://gist.githubusercontent.com/mikewallace1979/2100dca8c1986d55c5b85c924288f872/raw/9299c90a84e94880b6f67445ad6fe4928b7c12a8/64mb_eu_us-west_4.png)|

The results aren't particularly surprising aside from a concurrency of 2 being notably worse than concurrency 1 for eu to us-east WAL archives. I suspect this is due to fixing the block size - the single concurrency upload does not chunk the upload so will just be uploading the whole blob, whereas for concurrency 2 the 16MB WAL gets broken into 1MB chunks and the overhead is greater than the benefit of any parallelism due to the shorter transfer time.

**Comment by ba-edb** [comment]
@mikewallace1979: The scales are a little difficult to read - is it accurate to say that throughput is roughly doubled on the 64MB segments? And does this hold true for in-region uploads?

**Comment by mikewallace1979** [comment]
Looking at the percentiles I'd say throughput is more than double.

For eu to us-east:

|WAL size|Block size|Concurrency|p50|p75|p90|max|
|--------|----------|-----------|---|---|---|---|
|64MB|N/A|1|7672|14524|27150|48780|
|64MB|4|2|7457|10749|16744|24220|
|64MB|4|4|4600|6211|8474|11435|
|64MB|4|8|3068|3766|5429|9328|
|64MB|4|16|2970|4180|6600|9132|

For eu to us-west

|WAL size|Block size|Concurrency|p50|p75|p90|max|
|--------|----------|-----------|---|---|---|---|
|64MB|N/A|1|42101|59164|75958|217950|
|64MB|4|2|19303|30350|41020|63597|
|64MB|4|4|13732|18170|22770|49072|
|64MB|4|8|9419|12753|16104|28679|
|64MB|4|16|8466|12448|15171|46244|

In-region is a different story - not much of a gain with 64MB segment sizes and slightly worse with 16MB:

|16MB WAL | 64MB WAL|
|-- | --|
|![](https://gist.githubusercontent.com/mikewallace1979/2100dca8c1986d55c5b85c924288f872/raw/9299c90a84e94880b6f67445ad6fe4928b7c12a8/16mb_eu_eu_1.png)|![](https://gist.githubusercontent.com/mikewallace1979/2100dca8c1986d55c5b85c924288f872/raw/9299c90a84e94880b6f67445ad6fe4928b7c12a8/64mb_eu_eu_4.png)|

In-region histogram summary:

|WAL size|Block size|Concurrency|p50|p75|p90|max|
|--------|----------|-----------|---|---|---|---|
|64MB|N/A|1|1468|1585|1703|2342|
|64MB|4|2|1656|1745|1840|2583|
|64MB|4|4|1276|1336|1406|1788|
|64MB|4|8|1218|1268|1347|1922|
|64MB|4|16|1243|1306|1379|1982|

---

For completeness, here are the 16MB and 32MB histogram summaries:

### In-region

|WAL size|Block size|Concurrency|p50|p75|p90|max|
|--------|----------|-----------|---|---|---|---|
|16MB|N/A|1|766|816|893|1892|
|16MB|1|2|960|1004|1094|1348|
|16MB|1|4|788|824|873|1424|
|16MB|1|8|781|808|847|1482|
|16MB|1|16|816|863|950|1622|

|WAL size|Block size|Concurrency|p50|p75|p90|max|
|--------|----------|-----------|---|---|---|---|
|32MB|N/A|1|937|1004|1078|1232|
|32MB|16|2|872|921|962|1411|
|32MB|8|4|870|900|926|1133|
|32MB|4|8|894|938|989|1733|
|32MB|2|16|894|934|968|8213|

### eu-west to us-east

|WAL size|Block size|Concurrency|p50|p75|p90|max|
|--------|----------|-----------|---|---|---|---|
|16MB|N/A|1|2846|3144|3675|7496|
|16MB|1|2|3396|3501|3600|5104|
|16MB|1|4|2580|2660|2882|4772|
|16MB|1|8|2174|2223|2474|4919|
|16MB|1|16|2008|2090|2713|5280|

|WAL size|Block size|Concurrency|p50|p75|p90|max|
|--------|----------|-----------|---|---|---|---|
|32MB|N/A|1|4843|9454|13288|34252|
|32MB|16|2|3734|8176|11494|21020|
|32MB|8|4|3012|4700|11031|15308|
|32MB|4|8|2581|3350|6425|11054|
|32MB|2|16|2488|3286|4704|6803|

### eu-west to us-west

|WAL size|Block size|Concurrency|p50|p75|p90|max|
|--------|----------|-----------|---|---|---|---|
|16MB|N/A|1|13584|22140|34650|71616|
|16MB|1|2|9826|12580|14476|29958|
|16MB|1|4|6400|8204|10659|17787|
|16MB|1|8|4634|5540|7451|11690|
|16MB|1|16|4053|5354|7549|9707|

|WAL size|Block size|Concurrency|p50|p75|p90|max|
|--------|----------|-----------|---|---|---|---|
|32MB|N/A|1|16282|28553|60150|158601|
|32MB|16|2|15785|23857|37599|85841|
|32MB|8|4|9847|16121|23607|48476|
|32MB|4|8|6366|9453|13267|42172|
|32MB|2|16|4720|6898|9962|16590|
