### ISSUE TITLE
Source of Compatibility Matrix pgbarman vs postgresql

### ISSUE THREAD

**Issue by PawelCzerwonka** [EnterpriseDB/barman#478]
Hello,
I'm trying to figure out "If pgbarman 2.15-1 is fully supported with Postgresql 14?". I have a doubt because website http://docs.pgbarman.org/release/2.15/#feature-matrix shows that "not" but when I use yum (see below commands) I can install version 2.15. Why this version is available on "2ndquadrant-dl-default-release-pg14" OL8 repository? Or maybe on http://docs.pgbarman.org is mistake? What is the the best method to check compatibility between pgbarman and postgresql?

[root@hostname~]# yum --showduplicates list available barman|grep "2ndquadrant-dl-default-release-pg14"
barman.noarch          2.15-1.el8            2ndquadrant-dl-default-release-pg14
barman.noarch          2.16-1.el8            2ndquadrant-dl-default-release-pg14
barman.noarch          2.17-1.el8            2ndquadrant-dl-default-release-pg14

Pawel

**Comment by didiermichel** [comment]
Hi @PawelCzerwonka 
Barman 2.15 does support pg 14.  
Feature matrix was not updated (forgotten) at the time we published 2.15 and updated only after. 

Didier

**Comment by PawelCzerwonka** [comment]
Thanks
