### ISSUE TITLE
Checking pg_receivewal compatibility

### ISSUE THREAD

**Issue by mclei-asw** [EnterpriseDB/barman#479]
I am trying to use barman with streaming wal backup, but I get error:
`ERROR: ArchiverFailure:pg_receivexlog version not compatible with PostgreSQL server version`

The barman check returns this:
`pg_receivexlog compatible: FAILED (PostgreSQL version: 13.0, pg_receivexlog version: 1:13.0-1.pgdg100+1custom4))`

Of course, when I run pg_receivewal manually, it works.

As you can see, I use custom packaged PostgreSQL with epoch added to the version number "1:". The bug completely prevents me from using barman in this mode.

So the problem is, that this additional version check prevents using the version with epoch added, even when the binaries are compatible.

I would appreciate a way how to disable this check.

**Comment by mikewallace1979** [comment]
@mclei-asw I'm having difficulty reproducing the error you're seeing with `barman check` - can you paste the full output from your `pg_receivewal --version` command?

**Comment by OsamaED** [comment]
The issue as below

$ barman check vmpostgresdb01
Server vmpostgresdb01:
	WAL archive: FAILED (please make sure WAL shipping is setup)
	PostgreSQL: OK
	superuser or standard user with backup privileges: OK
	PostgreSQL streaming: OK
	wal_level: OK
	replication slot: FAILED (slot 'barman' not initialised: is 'receive-wal' running?)
	directories: OK
	retention policy settings: OK
	backup maximum age: FAILED (interval provided: 1 day, latest backup age: No available backups)
	backup minimum size: OK (0 B)
	wal maximum age: OK (no last_wal_maximum_age provided)
	wal size: OK (0 B)
	compression settings: OK
	failed backups: OK (there are 0 failed backups)
	minimum redundancy requirements: OK (have 0 backups, expected at least 0)
	pg_basebackup: OK
	pg_basebackup compatible: FAILED (PostgreSQL version: 14.1, pg_basebackup version: 12.9)
	pg_basebackup supports tablespaces mapping: OK
	systemid coherence: OK (no system Id stored on disk)
	pg_receivexlog: OK
	pg_receivexlog compatible: FAILED (PostgreSQL version: 14.1, pg_receivexlog version: 12.9)
	receive-wal running: FAILED (See the Barman log file for more details)
	archiver errors: OK

$ barman receive-wal vmpostgresdb01

|OUTPUT|
Starting receive-wal for server vmpostgresdb01
ERROR: ArchiverFailure:pg_receivewal version not compatible with PostgreSQL server version

$ pg_receivewal --version
pg_receivewal (PostgreSQL) 12.9 (Ubuntu 12.9-0ubuntu0.20.04.1)



<<The solution>>
On Barman Backup Server as "root" user type:
$ apt-get install postgresql-client-14
to be compatible with PostgreSQL version: 14.1



$ pg_receivewal --version
pg_receivewal (PostgreSQL) 14.1 (Ubuntu 14.1-2.pgdg20.04+1)

$ barman check vmpostgresdb01
Server vmpostgresdb01:
	PostgreSQL: OK
	superuser or standard user with backup privileges: OK
	PostgreSQL streaming: OK
	wal_level: OK
	replication slot: OK
	directories: OK
	retention policy settings: OK
	backup maximum age: FAILED (interval provided: 1 day, latest backup age: No available backups)
	backup minimum size: OK (0 B)
	wal maximum age: OK (no last_wal_maximum_age provided)
	wal size: OK (0 B)
	compression settings: OK
	failed backups: OK (there are 0 failed backups)
	minimum redundancy requirements: OK (have 0 backups, expected at least 0)
	pg_basebackup: OK
	pg_basebackup compatible: OK
	pg_basebackup supports tablespaces mapping: OK
	systemid coherence: OK (no system Id stored on disk)
	pg_receivexlog: OK
	pg_receivexlog compatible: OK
	receive-wal running: OK
	archiver errors: OK

$ barman receive-wal vmpostgresdb01
Starting receive-wal for server vmpostgresdb01
Another receive-wal process is already running for server vmpostgresdb01.

**Comment by richyen** [comment]
> I am trying to use barman with streaming wal backup, but I get error: `ERROR: ArchiverFailure:pg_receivexlog version not compatible with PostgreSQL server version`
> 
> The barman check returns this: `pg_receivexlog compatible: FAILED (PostgreSQL version: 13.0, pg_receivexlog version: 1:13.0-1.pgdg100+1custom4))`
> 
> Of course, when I run pg_receivewal manually, it works.
> 
> As you can see, I use custom packaged PostgreSQL with epoch added to the version number "1:". The bug completely prevents me from using barman in this mode.
> 
> So the problem is, that this additional version check prevents using the version with epoch added, even when the binaries are compatible.
> 
> I would appreciate a way how to disable this check.

Hi @mclei-asw we have been reviewing this issue and it seems that you're using an older version of barman (v. 2.10 or earlier).  In v. 2.12 onwards, there are some regex changes that would allow your epoch-prefixed version output to succeed.  Could you please try using the latest version of barman and see if that resolves the issue?

If the issue persists, please:
- Provide barman version
- Provide `pg_receivewal ---version` output
- Provide `barman check` output
