### ISSUE TITLE
replace `T` with `_` in the backup_id

### ISSUE THREAD

**Issue by dulhaver** [EnterpriseDB/barman#481]
backups in barman are identified by a combination of the pg-server name and a timestamp (i.e. `barman list-backup [pg-server]`). The logic is completely fine but it is very hard to identify a particular backupID due to the format `yyyymmddThhmmss`. I guess the `T` stands for TIME or TIMESTAMP of something along that line but I would suggest to replace it with an underscore so it gets readable somewhat to the eye (I am aware that scripts are fine with the status quo). 

`server_name 20211225_123455` instead of `server_name 20211225T123455`

`server_name 20211225_123455` is somewhat identifiable for the eye where `20211225T123455` is just gibberish (to the eye).

**Comment by mikewallace1979** [comment]
The backup ID is based on the [ISO 8601 basic format](https://www.iso.org/iso-8601-date-and-time-format.html) and that's where the `T` comes from - that being the case we'd rather keep them as they are.
