### ISSUE TITLE
Update timestamp format in barman diagnose output

### ISSUE THREAD

**Issue by mikewallace1979** [EnterpriseDB/barman#510]
Currently `barman diagnose` provides timestamps as [ctime](https://docs.python.org/3/library/datetime.html#datetime.date.ctime) strings which (crucially) lack timezone information.

As a minimum we need to include timezone information (and confirm whether the timezone is of the PostgreSQL server or the Barman server) but we should also consider using something other than ctime (ISO8601 or epoch time for example). If we're going to use epoch time then that should probably be a separate field so that we still have human-friendly timestamps in the output.

**Comment by didiermichel** [comment]
I had some thoughts about it, I like the idea of using ISO8601 date format. But Displaying local server time can be an issue with DST. 
This output will also be used by pg_backup_api, so it is both a system interface and a human interface.

Here are concerned fields with current values:

```
global.system_info.timestamp = "Thu Feb 17 10:53:47 2022"
global.servers.xxx.backups.yyy.begin_time = 'Thu Feb 17 10:45:11 2022'
global.servers.xxx.backups.yyy.end_time = "Thu Feb 17 10:45:21 2022"
global.servers.xxx.status.last_archived_time = "Thu Feb 17 10:45:22 2022"
global.servers.xxx.status. last_failed_time = "Thu Feb 17 10:45:22 2022"
global.servers.xxx.status.stats_reset = "Thu Feb 17 09:11:54 2022",
```

What I suggest is to output UTC time for all fields so there is no data loss. And to keep the knowledge of server timezone 

Have two fields in global.system_info: 
timestamp in local server time
utc_time in UTC

Ex:
```
global.system_info.timestamp = "2022-02-17T11:53:47.944515+01:00"
global.system_info.utc_time = "2022-02-17T10:53:47.944515+00:00"
global.servers.xxx.backups.yyy.begin_time = '2022-02-17T10:45:11.672345+00:00'
global.servers.xxx.backups.yyy.end_time = "2022-02-17T10:45:21.664855+00:00"
global.servers.xxx.status.last_archived_time = "2022-02-17T10:45:22.331255+00:00"
global.servers.xxx.status. last_failed_time = "2022-02-17T10:45:22.644879+00:00"
global.servers.xxx.status.stats_reset = "2022-02-17T09:11:54.156842+00:00",
```
