### ISSUE TITLE
Backup of tablespace data is duplicated on the passive barman host

### ISSUE THREAD

**Issue by hzetters** [EnterpriseDB/barman#516]
When backing up a database having its data in tablespaces other than pg_default the backups on the passive barman host consume twice the diskspace compared to the active host.
The backup of the tablespace data is stored both in /var/lib/barman/<host>/base/<backupid>/pg_tblspc and in the actual tablespace catalog itself, instead of pg_tblspc containing a link to the tablespace directory (as it does on the active barman host).

barman list-backups does not show the actual disk space the backup is consuming on the passive host.

[barman@barman02]$ barman list-backup nike_12
nike_12 20220207T112326 - Mon Feb  7 11:24:30 2022 - Size: 22.4 GiB - WAL Size: 4.5 MiB (tablespaces: xx_uat:/var/lib/pgsql/12/data/xx_uat, yy_uat_scratch:/var/lib/pgsql/12/data/yy_uat_scratch)
nike_12 20220205T170045 - Sat Feb  5 17:02:25 2022 - Size: 22.4 GiB - WAL Size: 104.9 MiB (tablespaces: xx_uat:/var/lib/pgsql/12/data/xx_uat, yy_uat_scratch:/var/lib/pgsql/12/data/yy_uat_scratch)
nike_12 20220204T154454 - Fri Feb  4 15:48:49 2022 - Size: 22.4 GiB - WAL Size: 65.8 MiB (tablespaces: xx_uat:/var/lib/pgsql/12/data/xx_uat, yy_uat_scratch:/var/lib/pgsql/12/data/yy_uat_scratch)

[barman@barman02 base]$ du -sh *
45G     20220204T154454
45G     20220205T170045
45G     20220207T112326

It would be great if this could be corrected to avoid that the backups on the passive host consume twice the storage space if you are using tablespaces other than pg_default.
It seems this issue has been reported as early as in Oct 2020 (#309) but the problem still remains.
Any plans to fix this?

**Comment by mikewallace1979** [comment]
Merged in https://github.com/EnterpriseDB/barman/pull/517
