### ISSUE TITLE
streaming-server.conf-template - do not use 'streaming' as postgres config name

### ISSUE THREAD

**Issue by vrms** [EnterpriseDB/barman#532]
the default config in `streaming-server.conf-template` is named `[streaming]` 

Many people will copy and edit this file for setting up a real/testing barman instance and often use the same wording `[streaming]` for the configuration name. this leads to log entries like

`2022-03-06 04:22:02,256 [1260] barman.wal_archiver INFO: Found 2 xlog segments from streaming for streaming. Archive all segments in one run.`

this is a fairly unhealthy situation for troubleshooting because you have the term `streaming` in once line meaning different things. So I suggest to change the config name `[streaming]` to `[streaming-backups]` (actually anything but `streaming`). 

It is far from easy to get Barman running for someone who is not super experienced and at least it would be nice to not make troubleshooting (which very likely with be necessary) even harder due to this.

**Comment by didiermichel** [comment]
I agree the user experience can be improved for barman. We should rename this configuration to mitigate the situation.

**Comment by didiermichel** [comment]
After second though, we will rename `streaming` to `streaming-server` to keep it more meaningful.
