### ISSUE TITLE
export and import feature.

### ISSUE THREAD

**Issue by csawyerYumaed** [EnterpriseDB/barman#54]
I know barman has list-files, which sort of almost works for exporting (it doesn't list empty dirs, so they don't get exported).  But there is no way to import a backup back into barman.

It would be awesome if there was an easy way to export and import backups in/out of barman.
WHY?
  Maybe we want to keep yearly backups, or for some business purpose we need a snapshot of the DB as of some particular day.  Currently to do that you have to turn off all the retention policy stuff and manually delete backups.  

it would be awesome if aside from retention policy you can either mark a backup 'special'(so it won't be auto-deleted from retention policy) or a much more generic solution, is just allow export and import of backups (and then you could dump them into S3 or Amazon Glacier or whatever and keep them forever if desired).

**Comment by amenonsen** [comment]
As part of an effort to pick up maintenance of Barman, I'm closing this and many other old open issues in this repository.
