### ISSUE TITLE
Compress base backups with pg_basebackup (backup_method = postgres)

### ISSUE THREAD

**Issue by theadamwright** [EnterpriseDB/barman#555]
**What?** 

1. Support the compression of base backups when using the `pg_basebackup` method in Barman e.g., `--gzip` 
2. Expose the gzip compression of tar file output by being able to configure the compression level(0 through 9) e.g.,`--compress=level`
3. Support recovery of compressed backups: simple implementation that unzips on the Barman server and copies or preferably decompresses on the fly like `barman-cloud`. 

**Why?** 

Reduce the storage footprint of Postgres backups when using Barman.

**Comment by snailxr** [comment]
Or can send the compressed backups to the target server and decompress them.
