### ISSUE TITLE
MAGIC_MAX_LENGTH not increased for custom_compression_magic

### ISSUE THREAD

**Issue by dsmoljanovic** [EnterpriseDB/barman#567]
When using `custom_compression_magic` with more then 3 bytes (ZSTD has magic of 4 bytes for example) barman fails to detect the compression.

`MAGIC_MAX_LENGTH` used in `CompressionManager.identify_compression` remains 3; while `CustomCompressor` does show MAGIC of 4 and does set `sys.modules[__name__].MAGIC_MAX_LENGTH` to 4; but for some reason when calling `barman-wal-restore` which invokes `CompressionManager.identify_compression`, it sees max as 3.

Debugged this fast using additional logging calls to see what `MAGIC_MAX_LENGTH` is set in which part of the code; didn't get the chance to dive more deeper into it.
Reference here:
MAGIC_MAX_LENGTH is 3 in this code block:
https://github.com/EnterpriseDB/barman/blob/21f5e5adb105edc0b91fa158be9512bf2ebe8314/barman/compression.py#L112
MAGIC_MAX_LENGTH is 4 in this code block:
https://github.com/EnterpriseDB/barman/blob/21f5e5adb105edc0b91fa158be9512bf2ebe8314/barman/compression.py#L373

I did workaround by setting custom_compression_magic to only 3 out of its 4 bytes for ZSTD; but this is bad workaround.

This is on RHEL7; using Python 2.7.

**Comment by mikewallace1979** [comment]
Thanks for another detailed bug report @dsmoljanovic - I'll do some digging and see if I can figure out why `sys.modules[__name__].MAGIC_MAX_LENGTH` doesn't take effect.

**Comment by dsmoljanovic** [comment]
This is actually an interesting story that happened to us. I feel i need to share this just as trivia. 

Because of this bug, barman didn't manage to detect ZSTD compresed files.
BUT! Because of that other issue (566) it defaulted to using ZSTD for files with unknown magic so it decompressed it anyway (unless it was in streaming directory) :D
