### ISSUE TITLE
barman recover Failure copying base backup: data transfer failure

### ISSUE THREAD

**Issue by ahmetmelihbasbug** [EnterpriseDB/barman#577]
Hello.
I have problem when i use `barman recover` command.
I delete all files and folders from recovery target area. In de target area; DATA Directory is empty or not existing. 
However during recover process tablespaces and directories was created in target, and they're tried to recreate again. Then gives errror.

In target area, I did:
`-bash-4.2$ cd data/`
`-bash-4.2$ ls`
`tablespace1_tbl  tablespace2_tbl  tablespace3_tbl  PG_13_202205021  tablespace4_tbl`
`-bash-4.2$ rm -rf *`
`-bash-4.2$ ls -alh`
`total 0`
`drwx------. 2 postgres postgres  6 May 26 09:35 .`
`drwxr-xr-x. 4 postgres postgres 38 May 26 09:34 ..`

then my command  `barman recover` is started to work in barman server:
`-bash-4.2$ barman recover --target-time="2022-05-23 16:01:00" mydb 20220519T023001 /data/ --remote-ssh-command "ssh postgres@192.168.95.130"`
`Starting remote restore for server mydb using backup 20220519T023001`
`Destination directory: /data/`
`Remote command: ssh postgres@192.168.95.130`
`Doing PITR. Recovery target time: '2022-05-23 16:01:00+03:00'`
`       12375, tablespace1_tbl, /data/tablespace1_tbl`
`       12376, tablespace2_tbl, /data/tablespace2_tbl`
`       12377, tablespace3_tbl, /data/tablespace3_tbl`
`Copying the base backup.`
`ERROR: Failure copying base backup: data transfer failure`
`rsync error:`
`rsync: mkdir "/data/tablespace2_tbl" failed: File exists (17)`
`rsync error: error in file IO (code 11) at main.c(657) [Receiver=3.1.2]`

To bypass this error, during the recovery, when i see 'Copying the base backup.' result, i delete tablespace1_tbl   from recovery area and bypassed, continue to recover. However, i can not understand why i should delete it during recover. Moreover, after recover, i can not see any links on pg_tblspc folder in DATA. I have to link them by myself...
Is there any way to declare like 'append' or 'replace' and link tablespaces in pg_tblspc automatically? Thanks

**Comment by mikewallace1979** [comment]
@ahmetmelihbasbug Thanks for reporting the issue - can you please confirm the version of barman you are using?

It would be helpful if you could also run `barman show-backup mydb 20220519T023001` and include the response.

**Comment by ahmetmelihbasbug** [comment]
@mikewallace1979  I use barman version 2.19
```
barman show-backup mydb 20220519T023001
Backup 20220519T023001:
  Server Name            : mydb
  System Id              : 6934664555285501
  Status                 : DONE
  PostgreSQL Version     : 130002
  PGDATA directory       : /data/pgdata/13.2/csgbdata
  Tablespaces:
    tablespace1_tbl: /data/tablespace1_tbl (oid: 12375)
    tablespace2_tbl: /data/tablespace2_tbl (oid: 12376)
    tablespace3_tbl: /data/tablespace3_tbl (oid: 12377)
  Base backup information:
    Disk usage           : 107.0 GiB (107.0 GiB with WALs)
    Incremental size     : 107.0 GiB (-0.00%)
    Timeline             : 1
    Begin WAL            : 000000010000003C000000AE
    End WAL              : 000000010000003C000000AF
    WAL number           : 2
    WAL compression ratio: 99.71%
    Begin time           : 2022-05-19 02:30:07.884680+03:00
    End time             : 2022-05-19 02:52:19.693983+03:00
    Copy time            : 22 minutes, 11 seconds
    Estimated throughput : 82.3 MiB/s
    Begin Offset         : 40
    End Offset           : 96
    Begin LSN           : 3C/AE000028
    End LSN             : 3C/AF000060
  WAL information:
    No of files          : 379
    Disk usage           : 3.2 GiB
    WAL rate             : 2.27/hour
    Compression ratio    : 45.82%
    Last available       : 000000010000003E0000002A
  Catalog information:
    Retention Policy     : VALID
    Previous Backup      : 20220512T023001
    Next Backup          : 20220526T023002

```

**Comment by mikewallace1979** [comment]
Thanks @ahmetmelihbasbug - I have tried to reproduce the behaviour you are seeing but with no success.

What barman is supposed to do in this scenario is exactly what you suggest - it should avoid trying to recreate the tablespace dir once it has already created it and it should create the symlinks in `pg_tblspc`. I tried reproducing this with a similar configuration (three tablespaces located in `/data` and restoring into `/data` after deleting the contents) and barman was able to recover successfully and create the symlinks in `pg_tblspc`.

So there must be one or more things I'm missing in my attempt to reproduce. To help narrow things down I have a few more questions:

1. Was the backup taken using the rsync backup_method or the postgres backup_method?
2. What does the content of the base backup directory and the pg_tblspc directory look like on the Barman server? The output of `ls -l ~/mydb/base/20220519T023001`, `ls -l ~/mydb/base/20220519T023001/data` and `ls -l ~/mydb/base/20220519T023001/data/pg_tblspc` should be enough information.
3. Are you restoring from a passive barman server which syncs the backups from another barman server, or directly from the barman server which took the backup?

**Comment by ahmetmelihbasbug** [comment]
For 1: i use postgres backup_method.
For 2: 
```
-bash-4.2$ ls -l /arsiv1/barman/csgb/base/20220519T023001
total 8
drwx------.  3 barman barman   29 May 19 02:30 12375
drwx------.  3 barman barman   29 May 19 02:30 12376
drwx------.  3 barman barman   29 May 19 02:30 12377
-rw-r--r--.  1 barman barman 1748 May 19 02:52 backup.info
drwx------. 31 barman barman 4096 May 19 02:52 data

-bash-4.2$ ls -l /arsiv1/barman/csgb/base/20220519T023001/data/
total 1684
-rw-------.  1 barman barman     228 May 19 02:35 backup_label
-rw-------.  1 barman barman 1532802 May 19 02:52 backup_manifest
drwx------. 17 barman barman    4096 May 19 02:52 base
-rw-------.  1 barman barman      45 May 19 02:52 current_logfiles
drwx------.  2 barman barman    4096 May 19 02:52 global
drwxrwx---.  2 barman barman    4096 May 19 02:52 log
drwx------.  3 barman barman      21 May 19 02:52 PG_13_202205021 
drwx------.  2 barman barman       6 May 19 02:35 pg_commit_ts
drwx------.  2 barman barman       6 May 19 02:35 pg_dynshmem
-rw-------.  1 barman barman   13772 May 19 02:52 pg_hba.conf
-rw-------.  1 barman barman    4621 May 19 02:52 pg_hba.conf_orj_as_installed
-rw-------.  1 barman barman    1636 May 19 02:52 pg_ident.conf
drwx------.  4 barman barman      68 May 19 02:52 pg_logical
drwx------.  4 barman barman      36 May 19 02:35 pg_multixact
drwx------.  2 barman barman       6 May 19 02:35 pg_notify
drwx------.  2 barman barman       6 May 19 02:52 pg_replslot
drwx------.  2 barman barman       6 May 19 02:35 pg_serial
drwx------.  2 barman barman       6 May 19 02:35 pg_snapshots
drwx------.  2 barman barman       6 May 19 02:52 pg_stat
drwx------.  2 barman barman       6 May 19 02:52 pg_stat_tmp
drwx------.  2 barman barman       6 May 19 02:35 pg_subtrans
drwx------.  2 barman barman    4096 May 19 02:52 pg_tblspc
drwx------.  2 barman barman       6 May 19 02:35 pg_twophase
-rw-------.  1 barman barman       3 May 19 02:52 PG_VERSION
drwx------.  3 barman barman      28 May 19 02:35 pg_wal
drwx------.  2 barman barman    4096 May 19 02:52 pg_xact
-rw-------.  1 barman barman     554 May 19 02:52 postgresql.auto.conf
-rw-------.  1 barman barman   28223 May 19 02:52 postgresql.conf
-rw-r--r--.  1 barman barman       0 May 19 02:52 sonuc.txt
drwx------.  2 barman barman       6 May 19 02:52 tablespace1_tbl
drwx------.  2 barman barman       6 May 19 02:52 tablespace2_tbl

-bash-4.2$ ls /mydb/base/20220519T023001/data/pg_tblspc/
12375  12376  12377 
```
For 3: I recover empty passive server which is on same server with barman. I have barman and postgres users on server and i recover on another user with remote command.

I editted PGDATA directory  on previous message. I tried to mark words of db. All tablespaces have been created in PGDATA directory on prod database

**Comment by mikewallace1979** [comment]
Thanks @ahmetmelihbasbug - it's not recommended to put tablespaces within the PGDATA directory however barman *should* still be able to deal with it, so this is still puzzling.

When you say "I recover empty passive server which is on same server with barman. I have barman and postgres users on server and i recover on another user with remote command." do you mean:

* You have an empty PostgreSQL server installation on the Barman server.
* You are using remote-ssh-command to recover to the PGDATA directory on the Barman server, so the SSH connection is from the barman user to the postgres user on the same host?

Also, on what filesystem is your PGDATA directory located?

**Comment by ahmetmelihbasbug** [comment]
Both of them are true. For now; I have empty PostgreSQL service on the Barman server, in future i will have another server.
Same server; disks of backup and recover are different.
I am doing SSH connection is from the barman user to the postgres user on the same host.

All filesystems on PROD server, barman server recovery area and backup area  are xfs type.

**Comment by mikewallace1979** [comment]
Hi @ahmetmelihbasbug - I've switched to a VM with an XFS filesystem but I'm still unable to reproduce the issue.

I do have a couple of suggestions you could try:

* Avoid locating tablespace3_tbl in the base PGDATA directory. While I can't reproduce this issue exactly I do get a problem at the same stage of the recovery if the tablespace3_tbl location *is* the PGDATA directory:

```
$ barman recover pg13 20220527T104212 --target-time="2022-05-27 14:00:00" /mnt/xfs/postgresql/13/main --remote-ssh-command 'ssh postgres@localhost'
Starting remote restore for server pg13 using backup 20220527T104212
Destination directory: /mnt/xfs/postgresql/13/main
Remote command: ssh postgres@localhost
Doing PITR. Recovery target time: '2022-05-27 14:00:00+00:00'
Using safe horizon time for smart rsync copy: 2022-05-27 10:42:12.166011+00:00
	16386, tablespace1_tbl, /mnt/xfs/postgresql/13/main/tablespace1_tbl
	16387, tablespace2_tbl, /mnt/xfs/postgresql/13/main/tablespace2_tbl
        16388, tablespace3_tbl, /mnt/xfs/postgresql/13/main
Copying the base backup.
ERROR: Failure copying base backup: data transfer failure
rsync error:
unexpected end of filter rule: P_
rsync error: syntax or usage error (code 1) at exclude.c(1011) [client=3.1.2]
```

* Try using the `--tablespace NAME:LOCATION` option to restore the tablespaces to a different location. You can use the option multiple times, e.g. to restore them to a dir named`/tbs_data`:

``` 
`barman recover --target-time="2022-05-23 16:01:00" mydb 20220519T023001 /data --remote-ssh-command "ssh postgres@192.168.95.130" --tablespace tablespace1_tbl:/tbs_data/tablespace1_tbl --tablespace tablespace2_tbl:/tbs_data/tablespace2_tbl --tablespace tablespace3_tbl:/tbs_data/tablespace3_tbl`
```

This should restore your tablespaces to new locations outside of PGDATA and create the necessary symlinks in `PGDATA/pg_tblspc`.

**Comment by ahmetmelihbasbug** [comment]
thanks @mikewallace1979  I am testing with --tablespace  command. During the recovery, i am tracing pg_tblc

in barman output of recover command
```
Doing PITR. Recovery target time: '2022-05-24 16:01:00+03:00'
	12375, tablespace1_tbl, /data/tablespace1_tbl
	12376, tablespace2_tbl, /data/tablespace2_tbl
```
and in PGDATA at recovery area:
```
-bash-4.2$ ls -lrth pg_tblspc/
total 0
lrwxrwxrwx. 1 postgres postgres 40 May 27 15:46 16386 -> /data/tablespace1_tbl
lrwxrwxrwx. 1 postgres postgres 42 May 27 15:46 16387 -> /data/tablespace2_tbl
```

after one second in barman output of recover command
```
Doing PITR. Recovery target time: '2022-05-24 16:01:00+03:00'
	12375, tablespace1_tbl, /data/tablespace1_tbl
	12376, tablespace2_tbl, /data/tablespace2_tbl
        12377, tablespace3_tbl, /data/
```

and in PGDATA at recovery area:

```
-bash-4.2$ ls -lrth pg_tblspc/

lrwxrwxrwx. 1 postgres postgres 40 May 27 15:46 16460 -> /data/pgdata/13.2/csgbdata/ibys_prod_tbl
lrwxrwxrwx. 1 postgres postgres 42 May 27 15:46 16461 -> /data/pgdata/13.2/csgbdata/bumhep_prod_tbl
lrwxrwxrwx. 1 postgres postgres 36 May 27 15:46 16462 -> /data/pgdata/13.2/csgbdata/diyih_tbl
```

Everything looks ok. However when "Copying the base backup." occurs in barman output of recover command

```
Doing PITR. Recovery target time: '2022-05-24 16:01:00+03:00'
	12375, tablespace1_tbl, /data/tablespace1_tbl
	12376, tablespace2_tbl, /data/tablespace2_tbl
        12377, tablespace3_tbl, /data/
Copying the base backup.
```
and in PGDATA at recovery area:
```
-bash-4.2$ ls -lrth pg_tblspc/
total 0
```
recovery gives `rsync: mkdir error`. 
Is it possible to bypass "mkdir" command or change rsync to append in barman codes? I could not find main.c

Probably same location of tablespace and PGDATA could make problem.

**Comment by elhananjair** [comment]
hello, @mikewallace1979 am sorry to raise this question here, but it's related to recovery.
I executed `barman recover my-server mydb-id /var/lib/pgsql/data/ --remote-ssh-command "ssh postgres@IP"`
It says: **Your PostgreSQL server has been successfully prepared for recovery!** 
**First question:** I didn't get it, I thought the recovery is finished with just that. what does it mean "successfully prepared for recovery"? is there any other steps to be done, to finish recovering processes. 
**Second question:**  On remote pc I tried to start postgresql.service after the recovery is finished, but it's not starting because of this error, any ideas on this... 

> invalid value for parameter "lc_messages": "en_US.UTF-8"
9796] LOG:  invalid value for parameter "lc_monetary": "en_US.UTF-8"
9796] LOG:  invalid value for parameter "lc_numeric": "en_US.UTF-8"
9796] LOG:  invalid value for parameter "lc_time": "en_US.UTF-8"
9796] FATAL:  configuration file "/var/lib/pgsql/data/postgresql.conf" contains errors

Thanks.

**Comment by ahmetmelihbasbug** [comment]
@elhananjair You need to use pg_ctl start command too to start PostgreSQL service in remote PostgreSQL server where you're recovered.

**Comment by elhananjair** [comment]
> @elhananjair You need to use `pg_ctl start $PGDATA` command too to start PostgreSQL service in remote PostgreSQL server where you're recovered.

@ahmetmelihbasbug thanks for replying, I just used to start the postgresql service through `systemctl start postgresql.service` and things are working fine. I just didn't understand this part, "prepared for recovery". It seems like there is another step to do, but am already running my web app with the state I have backup up my db through barman.

**Comment by ahmetmelihbasbug** [comment]
> @ahmetmelihbasbug thanks for replying, I just used to start the postgresql service through `systemctl start postgresql.service` and things are working fine. I just didn't understand this part, "prepared for recovery". It seems like there is another step to do, but am already running my web app with the state I have backup up my db through barman.

When you start postgresql service after barman recover command, it put on your log file of postgresql
```
< user= db= host= pid=28741 time=2022-05-30 10:35:47.090 +03 app= > LOG:  redo starts at 3E/29000028
< user= db= host= pid=28741 time=2022-05-30 10:35:47.092 +03 app= > LOG:  consistent recovery state reached at 3E/29000138
< user= db= host= pid=28741 time=2022-05-30 10:36:05.079 +03 app= > LOG:  redo done at 3E/C7FFF8F8
```
it makes consistent recovery in starting. another step postgreSQL does. you also do not need pg_ctl command if your postgresql.service or postgresql-version.service sevice file shows PGDATA=recoveredarea 
Shortly, barman gives that message as success message.
