### ISSUE TITLE
Passive backup  -  lack of post / pre script hooks  - use case example - is a patch welcomed ?

### ISSUE THREAD

**Issue by gplv2** [EnterpriseDB/barman#593]
Hi,

Checking the code it looks like the passive backup feature does not support any pre/post backup hooks as it's located in a function which is not called ( nice inline comments btw, appreciate that ! ) .  Before I start writing a patch to be able to trigger actions after a successful copy I like to know what the general stance is concerning this.

I feel like the passive backup feature is undervalued and it's possible applications are viewed too narrow.   In the documentation this feature is considered primarily as geo-redundancy  but I believe it's a limiting view.  Passive backups have more use cases than just 2 distant servers.  But even in that case, the lack of any post/pre hooks makes it hard to have warmed up backup backup servers ready.

Besides that, passive backups are also very useful for the following scenario's:

- offloading the primary backup server so it can keep up with archiving walls so the database servers don't have disks filling up in case of an outage.
- making an environment copy (from production to development , test, staging)  between barman servers in an isolated env where only barman servers are able to (using ssh) communicate directly.   I think the need for those environments shouldn't be explained.
- for CICD purposes in general.
- restoring multiple server/database instances while making sure the production barman installation does not overload depending on the number of restores (might overlap with my first argument a bit but this is the restore POV, the first I tend to consider the backup POV)

The case I tried to build recently only to discover that I've should have read the barman source before trying it:

Using production data on a development database by passive copy from PROD barman to DEV barman , from DEV barman restoring this every night from backup to a number of development database machines .  

The use case is quite common:  developers needing to make code hotfixes due to bugs that only popup in the production instance, so where the only variable in play is the data itself that is different from the dev database.   Having development databases ready at all times is a huge timesaver, the bigger they are the more time is gained waiting for a restore for bughunting.

The need for post/pre script hooks is a bit essential here:
- need to anonimize some data and/or adapt a few small (config) tables (hooks needed to launch SQL scripts)
- need to wait for actions for the PROD barman backup to finished, in 2nd order, the need to wait for the passive copy to complete
- need to stop / start any application before and after the automated / continues restore.  (need to execute actions after/before the passive copy is used for recovery)

There are probably more things I haven't mention that would benefit from having the option to use post/pre hooks.   I also noticed that configuring them in a passive template is silently ignored at this moment.

At the end, the goal would just be to make sure that actions that depend on each other are able to signal when started/done using the hooks like the 'normal' backup does but for the passive backup.   Once the passive copy completes to DEV barman, we launch a restore hook, restore the dev database(s), when done start the applications up.   Just as long as there is a hook to a script pretty much everything can be done.

Would such a patch be welcome ? 

ps: I tend to intermix recover/restore terminology often but find restore more accurate in this case

**Comment by mikewallace1979** [comment]
Hi @gplv2 - thanks for the detailed proposal. The passive backup feature was indeed introduced in order to provide a means of achieving geo-redundancy however as you point out there are potential uses beyond that use case.

There's no specific reason why hook scripts are not currently supported - they were simply not included when geo-redundancy was added and there has not been much work on the feature since then. However, it is likely this will continue to be the case - we do not currently have any enhancements planned for the passive backup feature and, while it will still be maintained, it is not an area of the product we are actively developing.

That said, we are always happy to accept patches for review and an implementation which does not introduce anything concerning from a maintainability point of view would certainly be considered for merging.

**Comment by gplv2** [comment]
I guess not.  I don't see myself working on it in the near future, I've been working with barman for 5 years but switched project and comvault is the company standard unfortunately.  So I won't really have a means to work on this .

I do think it's a feature that makes barman complete, many people want to restore prod data to other environments and barman is ideally placed to facilitate this.  But I get that it's not a priority.
