### ISSUE TITLE
Remove pgespresso support

### ISSUE THREAD

**Issue by mikewallace1979** [EnterpriseDB/barman#601]
pgespresso is not required by any supported PostgreSQL versions so should be removed in a future Barman release.

**Comment by didiermichel** [comment]
Postgresql < 10 is not supported anymore.

We should also consider cleaning code related to unsupported PG versions (pgespresso being one of them).

**Comment by didiermichel** [comment]
Notice that pg_backup_api will be impacted by this change (pgespresso)

**Comment by didiermichel** [comment]
Actual status is pg_espresso removed and PG < 9.6 cleaned.

**Comment by didiermichel** [comment]
I suggest we remove PG < 10 in a future version. So we can close this Issue.
