### ISSUE TITLE
Drop python2 support

### ISSUE THREAD

**Issue by mikewallace1979** [EnterpriseDB/barman#608]
We'd need to update our packaging so that barman can run on python3 on supported platforms.

The first step is to figure out if this is even possible - are the python3 versions of the libraries we need already available in OS packages? If not can we package them without too much trouble or are there lots of transitive deps to worry about?

**Comment by mikewallace1979** [comment]
Platforms for which we currently package using python2:
* EL/CentOS 7
* SLES 12
* ~~Debian 9~~ (this is no longer supported)

The SLES 12 situation is as follows:
* `python3-*` packages are available but the range of packages is much smaller than for `python2`. Also the python3 version is 3.4.
* `python36-*` packages are also available however the range of packages is even smaller still.

I don't think it's worth dropping python2 if we just end up moving to also-unsupported python 3.4. We must therefore see which dependencies are available for python 3.6.

Packages we need for Barman Server:
|package|available?|repo?|
|-|-|-|
|python36-setuptools|yes|SLES12-SP5-Updates|
|python36-psycopg2|No||
|python36-argcomplete|No||
|python36-dateutil|No||

Additional packages are required for Barman Cloud however these are typically installed from PyPI rather than through OS packages. We will not consider these for now since python2 packages for these are either not available or not recent enough on SLES 12.

So as a minimum we need to create python36 packages for psycopg2 and argcomplete and python36-dateutil.

Let's see how many transitive deps exist and whether they're available as OS packages for SLES 12.

* python36-psycopg2
  * I don't think there are any python dependencies here.
  * Packaging is a bit of a pain because it's architecture dependent (we'll need to build a ppc64le package as well as x86_64).
* python36-argcomplete
  * Depends on importlib-metadata - this has transitive deps: more-itertools typing_extensions zipp.
  * No packages available for SLES12 for this or its deps. Packages available for tumbleweed but that doesn't help us.
* python36-dateutil
  * No further deps.
  * No packages available for SLES12.
 
So we'd need to publish the following packages for SLES12 in order to package barman with python 3.6:

* python36-psycopg2 (x86_64)
* python36-psycopg2 (ppc64le)
* python36-argcomplete (noarch)
* python36-importlib-metadata (noarch)
* python36-more-itertools (noarch)
* python36-typing_extensions (noarch)
* python36-zipp (noarch)
* python36-dateutil (noarch)

**Comment by martinmarques** [comment]
We dropped support in Barman 3.5
