### ISSUE TITLE
Unable to run cron backups

### ISSUE THREAD

**Issue by danimasa** [EnterpriseDB/barman#632]
When I start the server I'm able to generate backups and all occurs ok but when I schedule using cron the backup gets stucked.

In the log the following messages appear:
`barman.server INFO: Another archive-wal process is already running on server pg-0. Skipping to the next server`

What could being causing archive-wal to get stucked?

**Comment by mikewallace1979** [comment]
@danimasa It's hard to say what's going on from that log message alone since there are few different reasons why you might be seeing it - the most likely reasons are:

1. There is another Barman process running (typically this would be Barman's own `barman cron` job which handles various maintenance tasks such as WAL archiving), or:
2. There are some dangling lock files left by a previous Barman process which crashed and didn't get a chance to clean up after itself.

A few other questions which might help understand what's going on here:

* Are you seeing this message every time `barman backup` runs?
* What are the current contents of `barman_lock_directory` (defaults to `/var/run/barman`)?
* What does the rest of the log file look like for the backup which is not progressing?
* What does the full `barman backup` output look like for the backup which is not progressing?
* Which `backup_method` are you using - postgres or rsync?

**Comment by danimasa** [comment]
@mikewallace1979 about the reasons you list:

1. I tried to increase the `barman cron` period from 1 minute to 5 minutes in order to minimize the interference with other process but it did not resolve the problem;
2. Even if I remove the dangling lock files after a while the error starts appearing again.

About the questions you asked:

- When I start the server the `barman backup` runs normal but the cron triggered backups do not run.
- The contents of `barman_lock_directory`: `.pg-0-archive-wal.lock  .pg-0-backup.lock  .pg-0-cron.lock  .pg-0-receive-wal.lock  .pg-0-xlogdb.lock  pg-0`
- barman logs:
```
2022-08-02 16:45:02,197 [1187] barman.server INFO: Creating physical replication slot 'barman' on server 'pg-0'
2022-08-02 16:45:02,199 [1187] barman.server ERROR: Replication slot 'barman' already exists
2022-08-02 16:45:02,495 [1188] barman.server INFO: Another archive-wal process is already running on server pg-0. Skipping to the next server
2022-08-02 16:45:55,867 [77] barman.hooks WARNING: barman-cloud-wal-archive -j --endpoint-url ${AWS_ENDPOINT} s3://pg-backup-teste/ pg-0 returned 2
Output details:
usage: barman-cloud-wal-archive [-V] [--help] [-v | -q] [-z | -j] [-t]
                                [--cloud-provider {aws-s3,azure-blob-storage}]
                                [--endpoint-url ENDPOINT_URL] [-P PROFILE]
                                [-e ENCRYPTION]
                                [--encryption-scope ENCRYPTION_SCOPE]
                                destination_url server_name [wal_path]
barman-cloud-wal-archive: error: the following arguments are required: server_name
```
- `barman backup` logs:
```
ERROR: Impossible to start the backup. Check the log for more details, or run 'barman check pg-0'
```
- I'm using _postgres_ `backup_method`

I perceived a problem with `barman-cloud-wal-archive` but didn't found why it keeps showing the server_name is missing.

**Comment by mikewallace1979** [comment]
Thanks for sharing the information - I suspect the stuck backups are related to the `barman-cloud-wal-archive` failure.

The most likely reason you see `error: the following arguments are required: server_name` is that the `AWS_ENDPOINT` environment variable is not set - this would cause `s3://pg-backup-teste` to be parsed as the `--endpoint-url` and `pg-0` to be parsed as the destination url leaving no positional argument for the server name.

Check whether `AWS_ENDPOINT` is set in the environment in which cron executes `barman backup` and `barman cron`. If it's not set when cron executes barman but is set when you run `barman backup` manually then that would explain why it works in the manual case but not under cron.

**Comment by danimasa** [comment]
I corrected the problem with `barman-cloud-wal-archive`, now the problem starts appearing again. The barman log looks like that:

```
Another archive-wal process is already running on server pg-0. Skipping to the next server
Another archive-wal process is already running on server pg-0. Skipping to the next server
Another archive-wal process is already running on server pg-0. Skipping to the next server
Another archive-wal process is already running on server pg-0. Skipping to the next server
Another archive-wal process is already running on server pg-0. Skipping to the next server
Another archive-wal process is already running on server pg-0. Skipping to the next server
Another archive-wal process is already running on server pg-0. Skipping to the next server
Another archive-wal process is already running on server pg-0. Skipping to the next server
...
```

If I try to run `barman backup` that is the following log:

```
Starting backup using postgres method for server pg-0 in /var/lib/barman/pg-0/base/20220804T102439
Backup start at LSN: 1/47000060 (000000030000000100000047, 00000060)
Starting backup copy via pg_basebackup for 20220804T102439
WARNING: pg_basebackup does not copy the PostgreSQL configuration files that reside outside PGDATA. Please manually backup the following files:
        /opt/bitnami/postgresql/conf/postgresql.conf
        /opt/bitnami/postgresql/conf/pg_hba.conf

Copy done (time: 39 seconds)
Finalising the backup.
This is the first backup for server pg-0
WAL segments preceding the current backup have been found:
        000000030000000100000046 from server pg-0 has been removed
Backup size: 1.4 GiB
Backup end at LSN: 1/49000000 (000000030000000100000048, 00000000)
Backup completed (start time: 2022-08-04 10:24:39.959760, elapsed time: 41 seconds)
Waiting for the WAL file 000000030000000100000048 from server 'pg-0'
Another archive-wal process is already running on server pg-0. Skipping to the next server
Another archive-wal process is already running on server pg-0. Skipping to the next server
Another archive-wal process is already running on server pg-0. Skipping to the next server
...
```

**Comment by mikewallace1979** [comment]
I would guess that you have some dangling lock files originating from when the `barman-cloud-wal-archive` call was failing.

Check the timestamp on the `.pg-0-archive-wal.lock` lock file and try manually deleting it.

**Comment by danimasa** [comment]
I found the problem, researching the log files I found a line with an AWS authentication error. It's because the cron didn't recognize the environment variables. After putting the environment variables directly in the cron file It starts to work correctly.
Thanks.
