### ISSUE TITLE
flake8-copyright not compatible with flake8>=5.0.0

### ISSUE THREAD

**Issue by mikewallace1979** [EnterpriseDB/barman#635]
See https://github.com/savoirfairelinux/flake8-copyright/issues/18

Unclear if there's going to be a resolution here so we may need to figure out an alternative.

**Comment by didiermichel** [comment]
This one is fifed, but there is another issue with flake8-mock: https://github.com/aleGpereira/flake8-mock/issues/10 related to flake8 5.0.X versions

Maybe we freeze flake8=4.0.1 until all is more stable?
