### ISSUE TITLE
Barman backup fails with error: ERROR: Backup failed issuing stop backup command.

### ISSUE THREAD

**Issue by mrudula09attili** [EnterpriseDB/barman#645]
Hello Team,

Greetings!

One of our Database backup is failing and I did try couple of time and even changing it from full to incremental backup. Still no luck and the backup seems to fail every time.

Starting backup using rsync-exclusive method for server pgsql-host in <location>/20220810T144825
Backup start at LSN: 4D8/BE000028 (00000001000004D8000000BE, 00000028)
Starting backup copy via rsync/SSH for 20220810T144825 (4 jobs)
Copy done (time: 15 hours, 16 minutes, 56 seconds)
Asking PostgreSQL server to finalize the backup.
ERROR: Backup failed issuing stop backup command.
DETAILS: Cannot terminate exclusive backup. You might have to manually execute pg_stop_backup on your PostgreSQL server

Attaching the barman  diagnose output.

Thanks,
Mrudula
[diagnose_barman.pdf](https://github.com/EnterpriseDB/barman/files/9307686/diagnose_barman.pdf)

**Comment by martinmarques** [comment]
Did you check your postgres server logs around the time of the backup, particularly the error from running `pg_stop_backup()`?

**Comment by mrudula09attili** [comment]
Hello Martin,

Thanks for your quick response, yes I did check below is what I see

< 2022-08-10 14:45:09.698 BST >ERROR:  exclusive backup not in progress
< 2022-08-10 14:45:09.698 BST >STATEMENT:  SELECT location, (pg_walfile_name_offset(location)).*, now() AS timestamp FROM pg_stop_backup() AS location

Thanks,
Sri Attili

**Comment by martinmarques** [comment]
Can you try using concurrent backups? Exclusive backups have been deprecated for some time, and they'll be removed in PostgreSQL 15. Just set the following you your barman configuration and try taking a backup again:
```
backup_options = concurrent_backup
```
Also, which version of barman is this, and has there been an upgrade of barman or any other piece of software used (postgres, etc.)?

**Comment by mrudula09attili** [comment]
Hello Martin,

Thank you so much for the update. The backup is successful after making the changes to backup_options.

Also just to let you know, I have set this parameter in the host conf file where as the default in barman.conf is exclusive and backups for all other hosts was successful.

Is there somewhere I could find the difference between exclusive backups and Concurrent backups?

Our current barman version is 2.7 and we haven't upgraded it recently.

Thanks,
Sri Attili

**Comment by martinmarques** [comment]
2.7 is extremely old (3 years old). You should think about upgrading ASAP. There have been a lot of bugs fixed since then.

Regardin exclusive vs. concurrent backups, you can find some information here: https://www.postgresql.org/docs/current/continuous-archiving.html
