### ISSUE TITLE
Is there a good interface GUI for barman?

### ISSUE THREAD

**Issue by hermesalvesbr** [EnterpriseDB/barman#662]
I have 8 databases of my clients to back up and check if the copy is not corrupted. Would the barman help me with this?

If not, could you point me to a **panel** that would facilitate the management of database backups?

**Comment by mikewallace1979** [comment]
@hermesalvesbr There is no dedicated GUI for Barman however it can integrate with existing monitoring solutions such as Nagios (via the [check-barman](https://github.com/hamann/check-barman) plugin or Prometheus (via [prometheus-barman-exporter](https://github.com/marcinhlybin/prometheus-barman-exporter). The Prometheus exporter would allow [this Grafana dashboard](https://grafana.com/grafana/dashboards/13918-barman-exporter/) to be used.

Note that these are provided by the community and not directly supported by the Barman project.
