### ISSUE TITLE
PostgreSQL Data directory: /var/lib/postgresql/data but postgresql in a container

### ISSUE THREAD

**Issue by BoltMaud** [EnterpriseDB/barman#683]
Hello, 

I have two machines **pg-host** and **barman-host**. My postgres is running in a docker container. Everything seems to work except the WAL shipping.

> Barman version 3.2.0.

When running, 
$**barman-host**: barman check pghost 
everything is working properly except `WAL archive: FAILED (please make sure WAL shipping is setup)`.

My postgres database runs in a docker container, and the following command works fine on the host machine:
$**pg-host**:  barman-wal-archive IP hostname mountpath/pg_wal/000000000000000EXAMPLE>  ✅

My archive_command is : 
archive_command = 'barman-wal-archive barman-wal-archive IP hostname mountpath/%p'
However when I run 
$**barman-host**: barman switch-wal --archive --archive-timeout 60 pghost
I obtain : `ERROR: The WAL file 000000000000000EXAMPLE has not been received in 60 seconds`

The only strange line that I have found so far is `PostgreSQL Data directory: /var/lib/postgresql/data` when running :
$**barman-host**: barman status pghost. 
This path works only in the container. Do you have idea if this path is used ? can I modify it such that I can use the mounted path ? 

Many thanks,

**Comment by mikewallace1979** [comment]
Hi @BoltMaud - the value `/var/lib/postgresql/data` returned by `barman status` is the name of the PGDATA directory of the PostgreSQL server. Barman retrieves this using the query `SHOW data_directory;`. If you wanted to change the value of this path to match your mounted path you would need to change the value of the `data_directory` setting in your PostgreSQL configuration file on the PostgreSQL host.

The other thing to note is that when PostgreSQL runs `archive_command`, the current working directory will be the PGDATA directory. Because `%p` is a path relative to that directory you can use `archive_command = 'barman-wal-archive IP hostname %p'` as your `archive_command`.

If `barman switch-wal` is still failing to complete, take a look in the PostgreSQL logs on your PostgreSQL host for lines with the message `archive command failed`. This should include the exit status and any output of the failed `barman-wal-archive` command as executed by PostgreSQL.

**Comment by mikewallace1979** [comment]
Usually `write to closed file` happens when there's a problem with the SSH connection.

When you tested the `barman-wal-archive` command on pg-host were you the same unix user that runs PostgreSQL?

**Comment by BoltMaud** [comment]
Yes, the unix user is the same for PostgreSQL.
Now, I tried with a PostgreSQL directly on the host (there is no container anymore)... same problem but not the same error. It is more clear that there is an ssh error: `Host key verification failed.` but I can connect to the backup from the pg-host and the opposite too. 
Is it normal that " user= db=" are empty in PostgreSQL logs ? 
`2022-11-03 09:23:37.697 UTC [3478102] user= db= FATAL:  archive command failed with exit code 255`

**Comment by mikewallace1979** [comment]
If the user and database are included in `log_line_prefix` in postgresql config then it is normal for them to be empty in the `archive_command` logs.

The exit code of 255 is surprising - do you still have `archive_command` configured to use `barman-wal-archive` or are you using something else like `rsync` now?

**Comment by BoltMaud** [comment]
Indeed, I have changed to rync since it was not working.

**Comment by BoltMaud** [comment]
I think that I found a new key: 
`ERROR: Error executing ssh: [Errno 13] Permission denied: 'PATH/pg_wal/000000010000000000000001'`
Only systemd-coredump can access to the wal file...

**Comment by BoltMaud** [comment]
Ok! It seems that barman does not use the user I want. 

I can run the `archive_command` on my terminal with my user root, it works. I have set this root user in the two config files : `/etc/barman.d/pghost.conf` and `/etc/barman.conf`. However it seems that barman tries to use `postgres` user instead of root. I thought that because when I log as postgres and run the archive_command, I obtain the same `write to closed file` error. 

Then I have added "whoami" and it confirmed that I am not root but postgres.... I wonder why. Any idea ?

**Comment by mikewallace1979** [comment]
`archive_command` is executed by PostgreSQL itself, so the user account it will run under is the same as the one PostgreSQL runs under - on most PostgreSQL packages for most systems that's the `postgres` user.

Usually the `barman_user` should be left as the default `barman` (assuming you installed Barman from an rpm or deb package and not from source). In that case `archive_command` would run as the `postgres` user on the PostgreSQL host and make an SSH connection to the barman host as the `barman` user. The `postgres` user on the PostgreSQL host would therefore need an SSH key in `${HOME}/.ssh` which could be used to log in to the barman host as the barman user.

**Comment by BoltMaud** [comment]
Okey ! Great ! It's working with those users. Thank you for the answers 🤗
