### ISSUE TITLE
Correct backup postgres via streaming in kubernetes

### ISSUE THREAD

**Issue by Dexus** [EnterpriseDB/barman#71]
Hello does it give a complete example setup for postgres and barman to backup?

We have kubernetes in use and would like to backup our postgres with a sidecar container with barman. Have someone hints or examples for us?

Regards, Josef

EDIT: we use a postgres 9.5

**Comment by timbunce** [comment]
Perhaps https://hub.docker.com/r/postdock/barman/ would be of interest. (I've not used it.)

**Comment by amenonsen** [comment]
As part of an effort to pick up maintenance of Barman, I'm closing this and many other old open issues in this repository.
