### ISSUE TITLE
Database subdirectory missing after restore, despite database being shown existent?

### ISSUE THREAD

**Issue by MHenn1g** [EnterpriseDB/barman#723]
We have a simple barman streaming setup, one host (barman) for barman, one host (pg-srv-0) for PostgreSQL.
The usual backup / restore scenarios work fine, continuously running transactions, restore to a specific point in time, all works as expected, except for the following scenario and maybe you could hint us to where our misconception lies.

****
**Environment**

**barman version:** barman-3.2.0-1.el8.noarch
**epas version:** edb-as14-server-core-14.6.0-1.rhel8.x86_64
**host:** rhel 8: Linux 4.18.0-425.3.1.el8.x86_64 #1 SMP Fri Sep 30 11:45:06 EDT 2022 x86_64 x86_64 x86_64 GNU/Linux
**filesystem:** ext4 - has_journal ext_attr resize_inode dir_index filetype needs_recovery extent 64bit flex_bg sparse_s uper large_file huge_file dir_nlink extra_isize metadata_csum

****
**Preparation**
Streaming backup was configured as well as continuous archiving
``` 
pg-srv-0> sudo cat $PG_DATA/postgresql.conf|grep archive_comma 
archive_command = 'barman-wal-archive 10.10.147.17 main-14 %p'


barman> cat /etc/barman.d/main-14-streaming.conf 
[main-14]
description = "PostgreSQL Database (Streaming-Only)" path_prefix = /usr/edb/edb-14/bin
conninfo = host=10.10.147.16 port=6240 user=barman dbname=edb passfile=/var/lib/barman/.pgpass sslmode=verify-
ca sslrootcert=/opt/postgres/certs/ca_certificate.crt
streaming_conninfo = host=10.10.147.16 port=6240 user=streaming_barman passfile=/var/lib/barman/.pgpass sslmode=verify -ca sslrootcert=/opt/postgres/certs/ca_certificate.crt
backup_method = postgres recovery_options = get-wal archiver = on
streaming_archiver = on backup_options = concurrent_backup
streaming_archiver_name = barman slot_name = barman
create_slot = auto immediate_checkpoint = true minimum_redundancy = 1 last_backup_maximum_age = 1 WEEKS path_prefix = /usr/edb/as14/bin/

barman> sudo -i -u $BARMAN_USER barman check main-14
Server main-14: PostgreSQL: OK
superuser or standard user with backup privileges: OK PostgreSQL streaming: OK
wal_level: OK
replication slot: OK
directories: OK
retention policy settings: OK
backup maximum age: OK (interval provided: 7 days, latest backup age: 6 seconds)
backup minimum size: OK (862.1 MiB)
wal maximum age: OK (no last_wal_maximum_age provided)
wal size: OK (0 B)
compression settings: OK
failed backups: OK (there are 0 failed backups)
minimum redundancy requirements: OK (have 1 backups, expected at least 1) pg_basebackup: OK
pg_basebackup compatible: OK
pg_basebackup supports tablespaces mapping: OK
systemid coherence: OK
pg_receivexlog: OK
pg_receivexlog compatible: OK
receive-wal running: OK
archive_mode: OK
archive_command: OK
continuous archiving: OK
archiver errors: OK
``` 

We prepare a test database d_test
``` 
pg-srv-0> sudo -i -u $PG_USER psql -p $PG_PORT -U $PG_USER -d $PG_DATABASE <<SQL
CREATE DATABASE d_test;
\c d_test;
CREATE TABLE t_test (
    id        varchar(40),
    modtime   timestamp DEFAULT current_timestamp
);
SQL
``` 
****

**Backup**
We take a backup
``` 
barman> sudo -i -u $BARMAN_USER barman backup main-14 --wait
barman> sudo -i -u $BARMAN_USER barman list-backup main-14
main-14 20230106T110517 - Fri Jan  6 10:05:19 2023 - Size: 71.4 MiB - WAL Size: 18.7 KiB
``` 
****
**Killing the database**
We select the current timestamp, drop the database and wait a few seconds to stream the changes
``` 
pg-srv-0> sudo -i -u $PG_USER psql -p $PG_PORT -U $PG_USER -d $PG_DATABASE <<SQL 
SELECT CURRENT_TIMESTAMP;
DROP DATABASE d_test;
SELECT pg_sleep(2);
SQL

----
OUTPUT
----
       current_timestamp       
-------------------------------
 2023-01-06 10:05:43.280141+00
(1 row)

DROP DATABASE
 pg_sleep 
----------
 
(1 row)
----


# now the server is killed and cleaned
pg-srv-0> sudo kill -9 $(ps -ef|grep edb-postmaster|grep -v grep|awk '{print $2}')
pg-srv-0> sudo rm -rf $PG_DATA $PG_WAL 
pg-srv-0> sudo mkdir $PG_DATA $PG_WAL
pg-srv-0> sudo chown $PG_USER: $PG_DATA $PG_WAL
``` 

****

**The restore**
The restore is performed to the timestamp right before the database was dropped
``` 
barman> sudo -i -u $BARMAN_USER barman recover --remote-ssh-command "ssh $PG_USER@$IP_PG_SRV_0" --target-time="2023-01-06 10:05:43.280141+00" --get-wal --target-action="promote" main-14 20230106T110517 $PG_DATA
Starting remote restore for server main-14 using backup 20230106T110517
Destination directory: /opt/postgres/as14/data
Remote command: ssh enterprisedb@10.10.147.16
Doing PITR. Recovery target time: '2023-01-06 10:05:43.280141+00:00'
Copying the base backup.
Generating recovery configuration
Identify dangerous settings in destination directory.

IMPORTANT
These settings have been modified to prevent data losses

postgresql.conf line 107: archive_command = false

WARNING
You are required to review the following options as potentially dangerous

postgresql.conf line 849: ssl_ca_file = '/opt/postgres/certs/ca_certificate.crt'
postgresql.conf line 850: ssl_cert_file = '/opt/postgres/certs/server.crt'
postgresql.conf line 851: ssl_key_file = '/opt/postgres/certs/server.key'

WARNING: 'get-wal' is in the specified 'recovery_options'.
Before you start up the PostgreSQL server, please review the postgresql.auto.conf file
inside the target directory. Make sure that 'restore_command' can be executed by the PostgreSQL user.

Recovery completed (start time: 2023-01-06 11:07:09.749693+01:00, elapsed time: 4 seconds)
Your PostgreSQL server has been successfully prepared for recovery!
``` 
From the output, everything seems fine so far
So we restart postgres and check the database
``` 
pg-srv-0> sudo systemctl restart edb-as-14
pg-srv-0> sudo -i -u $PG_USER psql -p $PG_PORT -U $PG_USER -d $PG_DATABASE <<SQL
\list
SQL
                                           List of databases
   Name    |    Owner     | Encoding |   Collate   |    Ctype    | ICU |       Access privileges       
-----------+--------------+----------+-------------+-------------+-----+-------------------------------
 d_test    | enterprisedb | UTF8     | en_US.UTF-8 | en_US.UTF-8 |     | 
 edb       | enterprisedb | UTF8     | en_US.UTF-8 | en_US.UTF-8 |     | enterprisedb=CTc/enterprisedb+
           |              |          |             |             |     | repuser=c/enterprisedb       +
           |              |          |             |             |     | barman=c/enterprisedb
 postgres  | enterprisedb | UTF8     | en_US.UTF-8 | en_US.UTF-8 |     | enterprisedb=CTc/enterprisedb
 template0 | enterprisedb | UTF8     | en_US.UTF-8 | en_US.UTF-8 |     | enterprisedb=CTc/enterprisedb
 template1 | enterprisedb | UTF8     | en_US.UTF-8 | en_US.UTF-8 |     | enterprisedb=CTc/enterprisedb
(5 rows)
``` 

The restore was done to the time right before d_test was deleted
The database seems to be there, so ... nothing to worry?

****

**The problem**
Not quite alright, because if we try to connect to the database this happens
``` 
sudo -i -u $PG_USER psql -p $PG_PORT -U $PG_USER -d d_test 
connection to server on socket "/tmp/.s.PGSQL.6240" failed: FATAL:  database "d_test" does not exist
DETAIL:  The database subdirectory "base/16474" is missing.
``` 

From the barman log the restore seems to be handled fine
``` 
# Barman log
    barman.recovery_executor INFO: Starting remote restore for server main-14 using backup 20230106T110517
    barman.recovery_executor INFO: Destination directory: /opt/postgres/as14/data
    barman.recovery_executor INFO: Remote command: ssh enterprisedb@10.10.147.16
    barman.recovery_executor INFO: Doing PITR. Recovery target time: '2023-01-06 10:05:43.280141+00:00'
    barman.recovery_executor WARNING: Unable to retrieve safe horizon time for smart rsync copy: The /opt/postgres/as14/data/.barman-recover.info file does not exist
    barman.recovery_executor INFO: Copying the base backup.
    barman.copy_controller INFO: Copy started (safe before None)
    barman.copy_controller INFO: Copy step 1 of 4: [global] analyze PGDATA directory: /var/lib/barman/main-14/base/20230106T110517/data/
    RsyncPgData INFO: drwxr-xr-x 6 2023/01/06 11:05:59 .
    RsyncPgData INFO: drwx------ 4096 2023/01/06 11:05:19 .
    RsyncPgData INFO: -rw-rw-r-- 941 2023/01/06 11:05:17 .barman-recover.info
    RsyncPgData INFO: -rw------- 3 2023/01/06 11:05:17 PG_VERSION
    [...]
    barman.copy_controller INFO: Copy step 3 of 4: [bucket 0] finished (duration: 1 second) copy safe files from PGDATA directory: /var/lib/barman/main-14/base/20230106T110517/data/
    barman.copy_controller INFO: Copy step 4 of 4: [bucket 0] starting copy files with checksum from PGDATA directory: /var/lib/barman/main-14/base/20230106T110517/data/
    barman.copy_controller INFO: Copy step 4 of 4: [bucket 0] finished (duration: less than one second) copy files with checksum from PGDATA directory: /var/lib/barman/main-14/base/20230106T110517/data/
    barman.copy_controller INFO: Copy finished (safe before None)
    barman.recovery_executor INFO: Generating recovery configuration
    barman.recovery_executor INFO: Identify dangerous settings in destination directory.
    barman.server ERROR: WAL file '00000009.history' not found in server 'main-14' (SSH host: 10.10.147.16)
    barman.server INFO: Sending WAL '00000008.history' for server 'main-14' to standard output (SSH host: 10.10.147.16)
    barman.server INFO: Sending WAL '00000008000000000000000A' for server 'main-14' to standard output (SSH host: 10.10.147.16)
    barman.server INFO: Sending WAL '00000008000000000000000B' for server 'main-14' to standard output (SSH host: 10.10.147.16)
    barman.server INFO: Sending WAL '00000008000000000000000C' for server 'main-14' to standard output (SSH host: 10.10.147.16)
    barman.server ERROR: WAL file '00000009.history' not found in server 'main-14' (SSH host: 10.10.147.16)
    barman.server INFO: Sending WAL '00000008.history' for server 'main-14' to standard output (SSH host: 10.10.147.16)
``` 

From the Postgres log the restore seems to be handled fine
``` 
# Postgres log
    LOG:  starting point-in-time recovery to 2023-01-06 10:05:43.280141+00
    LOG:  restored log file "00000008.history" from archive
    FATAL:  the database system is starting up
    LOG:  restored log file "00000008000000000000000A" from archive
    LOG:  redo starts at 0/A000028
    LOG:  consistent recovery state reached at 0/A000100
    LOG:  database system is ready to accept read-only connections
    LOG:  edb_wait_states collector started
    LOG:  autoprewarm successfully prewarmed 1195 of 1195 previously-loaded blocks
    LOG:  restored log file "00000008000000000000000B" from archive
    LOG:  restored log file "00000008000000000000000C" from archive
    LOG:  recovery stopping before commit of transaction 1775, time 2023-01-06 10:05:43.313885+00
    LOG:  redo done at 0/C001140 system usage: CPU: user: 0.00 s, system: 0.01 s, elapsed: 1.41 s
    LOG:  last completed transaction was at log time 2023-01-06 10:05:42.904965+00
``` 

Everything seems to have reached a consistent state, however it says the database does not exist.

If the restore state is as consistent as the log says, then depending on the restore time the database "d_test" should either 

- be missing completely
- be fully present

But it should not be in this "in between" state

So it seems some kind of inconsistency occured during the restore, which is not mentioned in the logs.
As mentioned above, this only happens in this "drop database" scenario, normal PITRs seem to work fine.

Therefore we are on the hunt for clues, what could lead to this kind of skew or if you just should not recover so close to a drop :D

**Comment by r-chauhan16** [comment]
According to the information provided above, you have used a timestamp after the deletion of the database. But in "\list" command it shows the database name. Could you let me know if there is no discrepancy in the provided data above?

You have restored the database to the below timestamp which is 2 seconds (pg_sleep(2)) after dropping the database.
`2023-01-06 10:05:43.280141+00`

So, ideally, in your restore, you should not see the "d_test" database.

**Comment by MHenn1g** [comment]
Hi Ravi,
thank you for your feedback.
In this case i cropped the output of the commands to make them more
readable, therefore a bit of confusion.
The commands were executed in the order shown above:

SELECT CURRENT_TIMESTAMP;
DROP DATABASE d_test;
SELECT pg_sleep(2);

The commands were executed in the order shown above:
So the timestamp given was basically a few ms before the database drop.
Afterwards came the 2s sleep to allow for WAL streaming to the Barman
server.

I adapted the output to make it more clear.





Am Fr., 6. Jan. 2023 um 14:29 Uhr schrieb Ravi Chauhan <
***@***.***>:

**Comment by amenonsen** [comment]
Could you show us the `barman show-backup` output for the backup that you restored, please?

**Comment by MHenn1g** [comment]
@amenonsen of course, here you go
```
sudo -i -u $BARMAN_USER barman show-backup main-14 20230106T110517
Backup 20230106T110517:
  Server Name            : main-14
  System Id              : 7185460974427351873
  Status                 : DONE
  PostgreSQL Version     : 140006
  PGDATA directory       : /opt/postgres/as14/data

  Base backup information:
    Disk usage           : 71.4 MiB (71.4 MiB with WALs)
    Incremental size     : 71.4 MiB (-0.00%)
    Timeline             : 8
    Begin WAL            : 00000008000000000000000A
    End WAL              : 00000008000000000000000B
    WAL number           : 2
    WAL compression ratio: 99.90%
    Begin time           : 2023-01-06 10:05:17.310214+00:00
    End time             : 2023-01-06 10:05:19.945570+00:00
    Copy time            : 2 seconds
    Estimated throughput : 27.5 MiB/s
    Begin Offset         : 40
    End Offset           : 736
    Begin LSN           : 0/A000028
    End LSN             : 0/B0002E0

  WAL information:
    No of files          : 1
    Disk usage           : 18.7 KiB
    WAL rate             : 350.02/hour
    Compression ratio    : 99.89%
    Last available       : 00000008000000000000000C

  Catalog information:
    Retention Policy     : VALID
    Previous Backup      : 20230106T105621
    Next Backup          : - (this is the latest base backup)
```

**Comment by amenonsen** [comment]
Thanks. I'll try to reproduce this problem and see if I can understand what's going on. I may need to ask you for more information as I go along.

**Comment by amenonsen** [comment]
So I think you're seeing a consequence of the fact that DROP DATABASE is not a fully transactional action. (If you try to run "BEGIN; DROP DATABASE …", you'll get an error that "DROP DATABASE cannot run inside a transaction block".) The update to the catalogs is transactional, but the removal of files from the filesystem is not. Your use of recovery_target_time to a timestamp immediately before the DROP DATABASE appears to put you at a point where the database has been removed, but you're in the middle of a transaction that would have completed the catalog changes, but you stopped before it was completed. 

Note that the time at which Postgres stops recovery when you use recovery_target_time is determined by the timestamps encountered in the WAL during replay that are attached to COMMIT/ABORT records, not any other records in between. This is why the timestamp in the "LOG:  recovery stopping before commit of transaction 1775, time 2023-01-06 10:05:43.313885+00" message is not exactly the same as the one you selected. In other words, the detection of whether recovery has passed the requested timestamp or not happens only at a transaction boundary.

I think you would not see this behaviour if you had any other transaction between selecting the timestamp and dropping the database. Likewise, if recovery had gone past this point (i.e., the skipped COMMIT), you would not see the entry in the catalog for the already-dropped database.

In such a case, when you're trying to recover from a mistakenly dropped database, we would recommend either recovering to a specific LSN, if known, or using an earlier time/setting recovery_target_action=pause and going forward to identify the exact LSN to recover to. You could still restore from your existing backup using this method and get back your database, but you would have to use an earlier timestamp corresponding to a _prior_ COMMIT record.

If you can paste pg_waldump output for the WAL segment in question, we can see more details about the exact records involved during recovery.

**Comment by MHenn1g** [comment]
Hi @amenonsen thank you for your detailed feedback.
You are right, if I execute another transaction between the timestamp selection and the database drop, the catalog is clean, however the database is non-existent, although the restore time is before the drop database command.
We will simply follow your advice and utilize the specific LSN to recover to.
Thanks for confirming, that this behaviour was to be expected :)
