### ISSUE TITLE
Postgresql 9.6 is supported or not ?

### ISSUE THREAD

**Issue by dblugeon** [EnterpriseDB/barman#735]
Hello,
I have a question. In the release notes 3.0, it writes :
https://github.com/EnterpriseDB/barman/blob/9bae7e391c0a2d196881c237555fa49ed7033a36/NEWS#L109-L111

But in the manual, we have 
https://github.com/EnterpriseDB/barman/blob/4f139b8c0f42e4c6772960b97c630f7a534d6186/doc/manual/15-system_requirements.en.md?plain=1#L23

What's is the state of support postgresql 9.6 in the barman's current version ?

**Comment by didiermichel** [comment]
Hello @dbglugeon,
Thank you for your pointing out this Documentation issue. We will update the documentation to clarify this.

Officially barman 3.0.0 dropped PostgreSQL 9.6 support.
It is strongly advised to update PostgreSQL to a newer version for Barman >=  3.0.0.
Nevertheless barman (3.0.0 and 3.1.0 ) will still handle PostgreSQL 9.6 . But not test where run against this PostgreSQL version.

**Comment by dblugeon** [comment]
Thanks you for your précisions and the update of the docs.
