### ISSUE TITLE
barman 3.3.0 - inconsistent behaviour of --name option in barman backup

### ISSUE THREAD

**Issue by epolkerman** [EnterpriseDB/barman#748]
Barman version 3.3.0
Rocky Linux 8 x86_64
python3 version 3.6

After taking a backup with barman without --name option, a new backup with option --name was taken:
barman backup --immediate-checkpoint --name namedbackup ssh-pg-master
Starting backup using rsync-concurrent method for server ssh-pg-master in /var/pgpure/barman/ssh-pg-master/base/20230210T125342
Backup start at LSN: 0/B2000028 (0000000100000000000000B2, 00000028)
Starting backup copy via rsync/SSH for 20230210T125342
Copy done (time: 2 seconds)
Asking PostgreSQL server to finalize the backup.
Backup size: 537.1 MiB. Actual size on disk: 196.5 KiB (-99.96% deduplication ratio).
Backup end at LSN: 0/B2000138 (0000000100000000000000B2, 00000138)
Backup completed (start time: 2023-02-10 12:53:43.358381, elapsed time: 9 seconds)
Processing xlog segments from streaming for ssh-pg-master
	0000000100000000000000B1
	0000000100000000000000B2
Processing xlog segments from file archival for ssh-pg-master
	0000000100000000000000B1
	0000000100000000000000B2
	0000000100000000000000B2.00000028.backup

The given name is shown in the list-backup output:
barman list-backup ssh-pg-master
ssh-pg-master 20230210T125342 'namedbackup' - Fri Feb 10 12:53:47 2023 - Size: 537.1 MiB - WAL Size: 0 B
ssh-pg-master 20230210T124306 - Fri Feb 10 12:43:20 2023 - Size: 537.1 MiB - WAL Size: 32.3 KiB

And backup information can be retrieved using the backup name:
barman show-backup ssh-pg-master namedbackup
Backup 20230210T125342:
  Backup Name            : namedbackup
  Server Name            : ssh-pg-master
  System Id              : 7198163089661158200
  Status                 : DONE
  PostgreSQL Version     : 150001
  PGDATA directory       : /var/pgpure/postgres/15/data

  Base backup information:
    Disk usage           : 537.1 MiB (537.1 MiB with WALs)
    Incremental size     : 196.5 KiB (-99.96%)
    Timeline             : 1
    Begin WAL            : 0000000100000000000000B2
    End WAL              : 0000000100000000000000B2
    WAL number           : 1
    WAL compression ratio: 99.90%
    Begin time           : 2023-02-10 12:53:43.094993+01:00
    End time             : 2023-02-10 12:53:47.283449+01:00
    Copy time            : 2 seconds + 1 second startup
    Estimated throughput : 83.7 KiB/s
    Begin Offset         : 40
    End Offset           : 312
    Begin LSN           : 0/B2000028
    End LSN             : 0/B2000138

  WAL information:
    No of files          : 0
    Disk usage           : 0 B
    Last available       : 0000000100000000000000B2

  Catalog information:
    Retention Policy     : VALID
    Previous Backup      : 20230210T124306
    Next Backup          : - (this is the latest base backup)

Deleted the backup with the given name:
barman delete ssh-pg-master namedbackup
Deleting backup 20230210T125342 for server ssh-pg-master
Deleted backup 20230210T125342 (start time: Fri Feb 10 13:51:52 2023, elapsed time: less than one second)

So far so good.... made a new backup with option --name (see attached file barman.log):
barman backup --wait --immediate-checkpoint --name namedbackup2 ssh-pg-master
The backup itself ends successfully

Now when a list of the backups is retrieved, the name is not used?!?! (See attached file barman_log-list-backup.log):
barman list-backup ssh-pg-master
ssh-pg-master 20230210T145444 - Fri Feb 10 14:54:50 2023 - Size: 537.1 MiB - WAL Size: 16.0 KiB
ssh-pg-master 20230210T124306 - Fri Feb 10 12:43:20 2023 - Size: 537.1 MiB - WAL Size: 370.2 KiB

It is also not possible to use the given backup name in e.g. show-backup command (see attached file barman_log-show-backup.log):
barman show-backup ssh-pg-master namedbackup2
ERROR: Unknown backup 'namedbackup2' for server 'ssh-pg-master'

[barman.log](https://github.com/EnterpriseDB/barman/files/10708501/barman.log)
[barman_log_list-backup.log](https://github.com/EnterpriseDB/barman/files/10708502/barman_log_list-backup.log)
[barman_log_show-backup.log](https://github.com/EnterpriseDB/barman/files/10708503/barman_log_show-backup.log)

**Comment by mikewallace1979** [comment]
This certainly does look inconsistent - would you be able to provide the output of `barman diagnose` so we can see the metadata for the two remaining backups?

**Comment by mikewallace1979** [comment]
Ok I've been able to reproduce this - the difference is the use of the `--wait` option. When it is used, the name does not get written to the backup metadata.

We'll fix this bug in the next release.
