### ISSUE TITLE
Support for backup via xz 

### ISSUE THREAD

**Issue by rouba002** [EnterpriseDB/barman#754]
Hi

I would like to see even basic support for some other archivers, namely XZ (https://tukaani.org/xz/) in WAL and maybe for the backups as well.
For large amount of WALs having extra space saved would be a nice benefit.

**Comment by mikewallace1979** [comment]
Hi @rouba002 - agreed it would be a nice enhancement if Barman had native support for `xz` compression.

You can achieve the same result with a [custom compressor](https://docs.pgbarman.org/release/3.4.0/#wal-compression) by setting `compression = custom` and then setting `custom_compression_filter`, `custom_decompression_filter` and `custom_compression_magic` to appropriate values, for example:

```
compression = custom
custom_compression_filter = xz
custom_decompression_filter = xz -d
custom_compression_magic = 0xFD377A585A00
```

For backups, we would need `pg_basebackup`/PostgreSQL to support `xz` - currently `gzip` compression can be used with all versions of PostgreSQL, and depending on the version and how it was built, `lz4` and `zstd` compression may also be available. Any available compression [can be used by Barman](https://docs.pgbarman.org/release/3.4.0/#backup-compression) however `xz` is not supported by any current PostgreSQL versions.

**Comment by martinmarques** [comment]
Support for xz WAL compression was added in Barman 3.12 yesterday. We won't be doing Backup compression in Barman so having xz compression for the Backup should be a Postgres feature to be added to pg_basebackup
