### ISSUE TITLE
FEATURE REQUEST: Google Cloud Storage (GCS) as backing store

### ISSUE THREAD

**Issue by bdurrow** [EnterpriseDB/barman#78]
I saw that you were looking for sponsorship to add S3 storage.  I am not interested in S3 storage but I am interested in Google Cloud Storage (GCS).  Do you know enough about the scope of work required to have a conversation about implementing this and the level of sponsorship that would be required?

**Comment by KellerFuchs** [comment]
Not being with 2nd Quandrant, I would not know how much they would want for implementing this, but I might have a stab at implementing uploads to object stores (in my case, likely S3), as that would be pretty helpful for what I'm doing at <https://hashbang.sh>.

Assuming I can find the time/energy to contribute this, adding a GCS backend would be pretty easy.

**Comment by amenonsen** [comment]
As part of an effort to pick up maintenance of Barman, I'm closing this and many other old open issues in this repository.
