### ISSUE TITLE
barman-cloud-backup-delete will never delete more than 1000 WALs against S3 (and compatible) object stores

### ISSUE THREAD

**Issue by mikewallace1979** [EnterpriseDB/barman#780]
The catalog of WAL segments used to select WALs for deletion after a backup is deleted is obtained using the boto3  `list_objects_v2` API call. This returns up to 1000 keys and a continuation token if more keys are available.

Barman [does not currently use that continuation token](https://github.com/EnterpriseDB/barman/blob/16ea407ee6279244a4731cfb5055943520eac1a6/barman/cloud_providers/aws_s3.py#L233-L259), so it will only ever consider up to 1000 WALs as candidates for deletion when deleting against S3.

This means that if more than 1000 WALs are generated between backups, WALs will accumulate at a faster rate than they can be deleted, so the archive will grow in size until WALs are removed via some other means.

This does not apply to the deletion of WAL segments stored on Azure Blob Storage because we use the [`walk_blobs`](https://learn.microsoft.com/en-us/python/api/azure-storage-blob/azure.storage.blob.containerclient?view=azure-python#azure-storage-blob-containerclient-walk-blobs) generator which handles paging transparently.

It may apply to deletion of WAL segments stored on GCS - if so a separate issue should be filed.

**Comment by ozen** [comment]
Seems fixed by https://github.com/EnterpriseDB/barman/commit/3b1efa18167a248ca1014a0db1779198439bd0d6
