### ISSUE TITLE
barman check has errors "receive-wal running: FAILED (See the Barman log file for more details)"

### ISSUE THREAD

**Issue by mrudula09attili** [EnterpriseDB/barman#799]
Hello Team,

 AS there was a new storage to migrate the barman backups to, I have changed the barman home location and reinitiated the barman checks.

I see errors for few hosts as below:

receive-wal running: FAILED (See the Barman log file for more details)

I tried to stop the receive-wal for the particular server and still getting the same issue.

Thanks,
Sri Attili

**Comment by mikewallace1979** [comment]
> receive-wal running: FAILED (See the Barman log file for more details)

Are you able to share any of the content of the log file here?

What output do you get if you run `barman receive-wal <SERVER>` manually?

**Comment by mrudula09attili** [comment]
bash-4.2$ barman receive-wal pg_server
Starting receive-wal for server pg_server
pg_server: pg_receivewal: starting log streaming at 13D/1A000000 (timeline 3)
pg_server: pg_receivewal: error: unexpected termination of replication stream: ERROR:  requested WAL segment 000000030000013D0000001A has already been removed
pg_server: pg_receivewal: error: disconnected
ERROR: ArchiverFailure:pg_receivexlog terminated with error code: 1

**Comment by mrudula09attili** [comment]
Though I have stopped and rsync the files from source to barman streaming location still it dint work.

I have reset the receive-wal now and trying my luck

**Comment by mrudula09attili** [comment]
Yes, this worked.

barman receive-wal --reset <server>
barman receive-wal <server>

This cleared the error.
I am running a backup now as I have reset the receive-wal
