### ISSUE TITLE
PostgreSQL upgrade

### ISSUE THREAD

**Issue by florentx** [EnterpriseDB/barman#8]
Could we have a F.A.Q entry about PostgreSQL major upgrades?

We are on the way to upgrade some server from 9.1 to 9.4, and I've found no hint how to be safe on the Barman side.

Found this similar question on SF : http://sourceforge.net/p/pgbarman/tickets/34/

**Comment by amenonsen** [comment]
As part of an effort to pick up maintenance of Barman, I'm closing this and many other old open issues in this repository.
