### ISSUE TITLE
Configuration structure change

### ISSUE THREAD

**Issue by krisavi** [EnterpriseDB/barman#804]
Why and when did the configuration files structure change. I did not notice anything about it in change logs. It used to be: `/etc/barman/barman.conf` and `/etc/barman/conf.d/*.conf` but now it is `/etc/barman.conf` and `/etc/barman.d/*.conf`

CentOS 7 after long time staying on version 2.17 suddenly found 3.5.0 package in repositories and kind of broke all backups with location change. Luckily test environment only, but unexpected and breaking change.

It was a lot cleaner with barman subfolder and letting me do config backups easily by copying to filename containing date. With new format it would make a lot of mess in /etc/.

**Comment by mikewallace1979** [comment]
Hi @krisavi - can you confirm the repositories these Barman 2.17 and 3.5.0 packages came from?

**Comment by krisavi** [comment]
Oh yeah, I believe it was from epel to pgdg... 

So that makes sense why it changed default location and moved old config to .rpmsave. 2 packages have defined different config file structure and when it switched from one repo to another because package name matched, it caused the mess for me. :(

**Comment by mikewallace1979** [comment]
Ok that seems to explain things - those packages in EPEL are built by the [Fedora project](https://koji.fedoraproject.org/koji/packageinfo?packageID=17651) and, as far as I can tell, have consistently used the `/etc/barman/barman.conf` `/etc/barman/conf.d/*.conf` layout. The PGDG packages have consistently used the other layout.

It's an unfortunate source of confusion but at least we understand it now.

**Comment by mikewallace1979** [comment]
I just merged #816 which adds an explanation of the differing configuration file layout to the Barman docs.
