### ISSUE TITLE
backup_compression_level = 0 is unsupported

### ISSUE THREAD

**Issue by kraynopp** [EnterpriseDB/barman#815]
I need to make backup without compression in tar format and I set backup_compression_level = 0 in barman.conf. But barman refuses to use this value of parameter. I see following in log file:

barman.cli ERROR: backup_compression_level 0 unsupported by pg_basebackup compression gzip

But it is mistake, pg_basebackup supports value --compress=0, I tried to launch pg_basebackup with parameters --format=tar --gzip --compress=0 and it works fine, so this limitation is artifical. I suppose it is hardcoded here:

https://github.com/EnterpriseDB/barman/blob/master/barman/compression.py#L578

Could you be so kind to fix this issue and allow to make backups in tar format without compression?

**Comment by kraynopp** [comment]
Could you be so kind to give any answer?

**Comment by mikewallace1979** [comment]
Thanks for reporting this issue and sorry we didn't acknowledge it earlier. I agree it looks like a bug - we'll get it fixed in an upcoming release.

**Comment by didiermichel** [comment]
Documentation can be found [here](https://docs.pgbarman.org/release/3.9.0/#compression-level)
