### ISSUE TITLE
Cannot recover using python >=3.8 on macOS

### ISSUE THREAD

**Issue by mikewallace1979** [EnterpriseDB/barman#838]
Recovery currently fails when running Barman on Python 3.11 on macOS.

Originally reported on the [mailing list](https://groups.google.com/g/pgbarman/c/mS5xfpfuctI/m/ghaI2_4RAgAJ?utm_medium=email&utm_source=footer&pli=1) and reproducible by creating a python 3.11 virtualenv and attempting to recover a backup:

```
$ barman recover mt-primary 20210705T100000 /tmp/recovered
Starting local restore for server mt-primary using backup 20210705T100000
Destination directory: /tmp/recovered
        16616, foo, /tmp/tablespace
Copying the base backup.
EXCEPTION: Can't pickle local object 'Command.make_logging_handler.<locals>.handler'
See log file for more details.
```

This is not an issue using earlier versions of python on macOS and it also does not appear to be an issue with python 3.11 on non macOS systems.

---

Update: After further testing this is an issue all the way back to python 3.8 on macOS.

**Comment by ARCICT** [comment]
Came across the following links. I taught it might help to resolve the issue.

The possible root cause of the issue:
https://medium.com/devopss-hole/python-multiprocessing-pickle-issue-e2d35ccf96a9

And maybe a solution can be found here: 
https://stackoverflow.com/questions/72766345/attributeerror-cant-pickle-local-object-in-multiprocessing

**Comment by ARCICT** [comment]
Info in the light of the upcoming python 3.12 release:

Look for multiprocessing in  https://docs.python.org/3.12/whatsnew/3.12.html

**Comment by mikewallace1979** [comment]
@ARCICT Thanks for looking into this - I think you are correct about the possible root cause, given the recovery code uses [multiprocessing.Pool.imap_unordered](https://github.com/EnterpriseDB/barman/blob/cb42b10e04afcd7ac727d61704e28078d04fbde8/barman/copy_controller.py#L571-L582) to spawn copy jobs, and that the issue only affects macOS on Python versions >= 3.8.

For confirmation I tried setting `multiprocessing.set_start_method("fork")` in Barman and this allows recovery to complete.

We'll need a bit of time to figure out the best solution and, going by the Python 3.12 release notes (thanks again for the heads-up about that one), it looks like we're going to need to solve it if we want Barman to continue working under Linux on Python 12 and later.

**Comment by ARCICT** [comment]
Mike,
-a python novices question. Where can we set/patch 'multiprocessing.set_start_method("fork")' ? we would like to build with the last version of python and be able to restore

- thought these might be of intrest ( at least to us ;-) )
          https://superfastpython.com/multiprocessing-start-method/
          https://superfastpython.com/multiprocessing-in-python/
Marc

**Comment by mikewallace1979** [comment]
Hi @ARCICT - I added a `set_start_method` in `barman.cli.main`, like this:

```
diff --git a/barman/cli.py b/barman/cli.py
index 2b0fcef9..14e9fb0d 100644
--- a/barman/cli.py
+++ b/barman/cli.py
@@ -2110,6 +2110,9 @@ def main():
     """
     The main method of Barman
     """
+    import multiprocessing
+
+    multiprocessing.set_start_method("fork")
     # noinspection PyBroadException
     try:
         argcomplete.autocomplete(p)
```

I'm hesitant to propose this as the long term solution because of the comments about the safety of `fork` which I haven't had a chance to read up on yet - it might be better to change the code run under multiprocessing so that it can be pickled, allowing it to work with `spawn`. For now the above patch should at least allow `barman recover` to complete.

**Comment by ARCICT** [comment]
@Mike,
Thanks for the info.
I agree that this is neither a good nor longterm solution. But at least it allows us to use the latest python version and still be able to use the restore function.
I read somewhere ( and I can't find the link) that a possible work around is be to set "cores 1" . . . which means that no multiprocessing will be used. Neither a longterm solution;-)
We 'll do some restores in this setup and see how fast we come across issues.

Regarding the good longterm solution we are looking at the python wizards :-)
Marc

**Comment by gcalacoci** [comment]
@ARCICT I've created a PR that should solve the issue of Pickle and macOS:

https://github.com/EnterpriseDB/barman/pull/843

can you please check if is working as expected for you? With this patch, I've been able to backup and restore using rsync on macOS using Python 3.8.11 and should work with the newer versions

**Comment by ARCICT** [comment]
@Giulio Works like a charm !
Many thanks (to all) for the swift respons & fix !
