### ISSUE TITLE
barman backup can not finish, the backup status always is STARTED

### ISSUE THREAD

**Issue by toplinuxsir** [EnterpriseDB/barman#85]
barman list-backup :
changchun 20170211T050003 - STARTED
changchun 20170204T050003 - Sat Feb  4 05:00:02 2017 - Size: 2.9 GiB - WAL Size: 1.7 GiB
changchun 20170128T050003 - Sat Jan 28 05:00:02 2017 - Size: 2.9 GiB - WAL Size: 256.0 MiB
The first backup start from three days ago, but the normal backup should finish in one hour ,
barman check ouput:
  	PostgreSQL: OK
	superuser: OK
	PostgreSQL streaming: OK
	wal_level: OK
	replication slot: OK
	directories: OK
	retention policy settings: OK
	backup maximum age: OK (no last_backup_maximum_age provided)
	compression settings: OK
	failed backups: OK (there are 0 failed backups)
	minimum redundancy requirements: OK (have 7 backups, expected at least 2)
	pg_basebackup: OK
	pg_basebackup compatible: OK
	pg_basebackup supports tablespaces mapping: OK
	archive_mode: OK
	archive_command: OK
	continuous archiving: OK
	pg_receivexlog: OK
	pg_receivexlog compatible: OK
	receive-wal running: OK
	archiver errors: OK

barman status output:
     	Description: Changchun Postgresql Database (Streaming-Only)
	Active: True
	Disabled: False
	PostgreSQL version: 9.4.10
	pgespresso extension: Not available
	Current data size: 2.9 GiB
	PostgreSQL Data directory: /s1/postgres/data
	Current WAL segment: 000000010000000900000006
	PostgreSQL 'archive_command' setting: test ! -f /s1/postgres/archive/%f && cp %p /s1/postgres/archive/%f
	Last archived WAL: 000000010000000900000005, at Tue Feb 14 13:50:32 2017
	Failures of WAL archiver: 0
	Server WAL archiving rate: 0.11/hour
	Retention policies: enforced (mode: auto, retention: RECOVERY WINDOW OF 7 WEEKS, WAL retention: MAIN)
	No. of available backups: 7
	First available backup: 20161224T050003
	Last available backup: 20170204T050003
	Minimum redundancy requirements: satisfied (7/2)

**Comment by gbartolini** [comment]
Please provide us with `barman diagnose`. Keep in mind that we discourage local installations of Barman and we do not support them in community forums. Question: why do you use streaming backup but then you use archive_command instead of WAL streaming?

**Comment by MikkelPorse** [comment]
I have this problem using barman 2.5 and PostgreSQL 11.1, Ubuntu 18.04
I use streaming exclusively,
barman status is all OKs, but claiming 0 backups.
I issued one "barman backup [pg]", it copied all files without incident - just never got around to completing the backup it seems.

Postgres cluster is pretty vanilla, no plugins or extensions, but one database is localized to da_DK.UTF-8

barman diagnose
```json
{
    "global": {
        "config": {
            "bandwidth_limit": "0",
            "barman_home": "/backup",
            "barman_user": "barman",
            "configuration_files_directory": "/etc/barman.d",
            "errors_list": [],
            "immediate_checkpoint": "true",
            "log_file": "/var/log/barman/barman.log",
            "log_level": "DEBUG"
        },
        "system_info": {
            "barman_ver": "2.5",
            "kernel_ver": "Linux postgres_barman 4.15.0-39-generic #42-Ubuntu SMP Tue Oct 23 15:48:01 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux",
            "python_ver": "",
            "release": "Distributor ID:\tUbuntu\nDescription:\tUbuntu 18.04.1 LTS\nRelease:\t18.04\nCodename:\tbionic",
            "rsync_ver": "rsync  version 3.1.2  protocol version 31",
            "ssh_ver": ""
        }
    },
    "servers": {
        "[pg]": {
            "backups": {
                "20181115T130641": {
                    "backup_id": "20181115T130641",
                    "backup_label": null,
                    "begin_offset": 96,
                    "begin_time": "Thu Nov 15 13:06:41 2018",
                    "begin_wal": "000000010000026D000000C3",
                    "begin_xlog": "26D/C3000060",
                    "config_file": "/etc/postgresql/11/main/postgresql.conf",
                    "copy_stats": null,
                    "deduplicated_size": null,
                    "end_offset": null,
                    "end_time": null,
                    "end_wal": null,
                    "end_xlog": null,
                    "error": null,
                    "hba_file": "/etc/postgresql/11/main/pg_hba.conf",
                    "ident_file": "/etc/postgresql/11/main/pg_ident.conf",
                    "included_files": null,
                    "mode": "postgres",
                    "pgdata": "/postgresdata/11/main",
                    "server_name": "[pg]",
                    "size": null,
                    "status": "STARTED",
                    "tablespaces": null,
                    "timeline": 1,
                    "version": 110001,
                    "xlog_segment_size": 16777216
                }
            },
            "config": {
                "active": true,
                "archiver": false,
                "archiver_batch_size": 0,
                "backup_directory": "/backup/[pg]",
                "backup_method": "postgres",
                "backup_options": "concurrent_backup",
                "bandwidth_limit": 0,
                "barman_home": "/backup",
                "barman_lock_directory": "/backup",
                "basebackup_retry_sleep": 30,
                "basebackup_retry_times": 0,
                "basebackups_directory": "/backup/[pg]/base",
                "check_timeout": 30,
                "compression": null,
                "conninfo": "host=[pg] user=barman dbname=postgres",
                "custom_compression_filter": null,
                "custom_decompression_filter": null,
                "description": "Lectio-pg2 - Postgres udv.",
                "disabled": false,
                "errors_directory": "/backup/[pg]/errors",
                "immediate_checkpoint": true,
                "incoming_wals_directory": "/backup/[pg]/incoming",
                "last_backup_maximum_age": null,
                "max_incoming_wals_queue": null,
                "minimum_redundancy": 0,
                "msg_list": [],
                "name": "[pg]",
                "network_compression": false,
                "parallel_jobs": 1,
                "path_prefix": null,
                "post_archive_retry_script": null,
                "post_archive_script": null,
                "post_backup_retry_script": null,
                "post_backup_script": null,
                "post_delete_retry_script": null,
                "post_delete_script": null,
                "post_recovery_retry_script": null,
                "post_recovery_script": null,
                "post_wal_delete_retry_script": null,
                "post_wal_delete_script": null,
                "pre_archive_retry_script": null,
                "pre_archive_script": null,
                "pre_backup_retry_script": null,
                "pre_backup_script": null,
                "pre_delete_retry_script": null,
                "pre_delete_script": null,
                "pre_recovery_retry_script": null,
                "pre_recovery_script": null,
                "pre_wal_delete_retry_script": null,
                "pre_wal_delete_script": null,
                "recovery_options": "",
                "retention_policy": null,
                "retention_policy_mode": "auto",
                "reuse_backup": null,
                "slot_name": "barman",
                "ssh_command": null,
                "streaming_archiver": true,
                "streaming_archiver_batch_size": 0,
                "streaming_archiver_name": "barman_receive_wal",
                "streaming_backup_name": "barman_streaming_backup",
                "streaming_conninfo": "host=[pg] user=streaming_barman",
                "streaming_wals_directory": "/backup/[pg]/streaming",
                "tablespace_bandwidth_limit": null,
                "wal_retention_policy": "main",
                "wals_directory": "/backup/[pg]/wals"
            },
            "status": {
                "config_file": "/etc/postgresql/11/main/postgresql.conf",
                "connection_error": null,
                "current_size": 28532934333.0,
                "current_xlog": "000000010000026D000000C6",
                "data_directory": "/postgresdata/11/main",
                "hba_file": "/etc/postgresql/11/main/pg_hba.conf",
                "ident_file": "/etc/postgresql/11/main/pg_ident.conf",
                "is_in_recovery": false,
                "is_superuser": true,
                "pg_basebackup_bwlimit": true,
                "pg_basebackup_compatible": true,
                "pg_basebackup_installed": true,
                "pg_basebackup_path": "/usr/bin/pg_basebackup",
                "pg_basebackup_tbls_mapping": true,
                "pg_basebackup_version": "11.1-1.pgdg18.04+1)",
                "pg_receivexlog_compatible": true,
                "pg_receivexlog_installed": true,
                "pg_receivexlog_path": "/usr/bin/pg_receivewal",
                "pg_receivexlog_supports_slots": true,
                "pg_receivexlog_synchronous": false,
                "pg_receivexlog_version": "11.1-1.pgdg18.04+1)",
                "pgespresso_installed": false,
                "replication_slot": [
                    "barman",
                    true,
                    "26D/C6000000"
                ],
                "replication_slot_support": true,
                "server_txt_version": "11.1",
                "streaming": true,
                "streaming_supported": true,
                "synchronous_standby_names": [
                    ""
                ],
                "systemid": "6616555765954001532",
                "timeline": 1,
                "wal_level": "replica",
                "xlogpos": "26D/C60001E8"
            },
            "wals": {
                "last_archived_wal_per_timeline": {
                    "00000001": {
                        "compression": null,
                        "name": "000000010000026D000000C5",
                        "size": 16777216,
                        "time": 1542293703.3247108
                    }
                }
            }
        }
    }
}

**Comment by mnencia** [comment]
@MikkelPorse this is a different issue. You use a bad server name that ends up confusing the tools. Please change `[[pg]]` to `[pg]` in your barman configuration.

**Comment by MikkelPorse** [comment]
No, [pg] is just a substitution of the actual name.

**Comment by MikkelPorse** [comment]
solved my little headache. The problem was archive_wal = on   in postgresql.conf but with no archive_command.  pg_basebackup just stood there waiting for the archival to complete, which of course it never would. (yes, too much messing about in postgresql.conf)

I just ran pg_basebackup manually, and got the error right there in the terminal.

**Comment by wlzch** [comment]
This also happened to me. The status is always STARTED and never completes no matter how long I waited. For my case, I am using wal streaming rather than archive command.

This is my barman diagnose
```
{
    "global": {
        "config": {
            "barman_home": "/var/lib/barman", 
            "barman_user": "barman", 
            "compression": "gzip", 
            "configuration_files_directory": "/etc/barman.d", 
            "errors_list": [], 
            "last_backup_maximum_age": "3 DAYS", 
            "log_file": "/var/log/barman/barman.log", 
            "log_level": "INFO", 
            "minimum_redundancy": "3", 
            "retention_policy": "RECOVERY WINDOW OF 2 WEEKS"
        }, 
        "system_info": {
            "barman_ver": "2.5", 
            "kernel_ver": "Linux backup 4.4.0-117-generic #141-Ubuntu SMP Tue Mar 13 11:58:07 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux", 
            "python_ver": "", 
            "release": "LSB Version:\tcore-9.20160110ubuntu0.2-amd64:core-9.20160110ubuntu0.2-noarch:security-9.20160110ubuntu0.2-amd64:security-9.20160110ubuntu0.2-noarch\nDistributor ID:\tUbuntu\nDescription:\tUbuntu 16.04.4 LTS\nRelease:\t16.04\nCodename:\txenial", 
            "rsync_ver": "rsync  version 3.1.1  protocol version 31", 
            "ssh_ver": ""
        }
    }, 
    "servers": {
        "pg": {
            "backups": {
                "20181207T150652": {
                    "backup_id": "20181207T150652", 
                    "backup_label": null, 
                    "begin_offset": 12128168, 
                    "begin_time": "Fri Dec  7 15:06:51 2018", 
                    "begin_wal": "000000010000000B00000030", 
                    "begin_xlog": "B/30B90FA8", 
                    "config_file": "/etc/postgresql/9.4/main/postgresql.conf", 
                    "copy_stats": null, 
                    "deduplicated_size": null, 
                    "end_offset": null, 
                    "end_time": null, 
                    "end_wal": null, 
                    "end_xlog": null, 
                    "error": null, 
                    "hba_file": "/etc/postgresql/9.4/main/pg_hba.conf", 
                    "ident_file": "/etc/postgresql/9.4/main/pg_ident.conf", 
                    "included_files": null, 
                    "mode": "postgres", 
                    "pgdata": "/var/lib/postgresql/9.4/main", 
                    "server_name": "pg", 
                    "size": null, 
                    "status": "STARTED", 
                    "tablespaces": null, 
                    "timeline": 1, 
                    "version": 90418, 
                    "xlog_segment_size": 16777216
                }
            }, 
            "config": {
                "active": true, 
                "archiver": false, 
                "archiver_batch_size": 0, 
                "backup_directory": "/var/lib/barman/pg", 
                "backup_method": "postgres", 
                "backup_options": "concurrent_backup", 
                "bandwidth_limit": null, 
                "barman_home": "/var/lib/barman", 
                "barman_lock_directory": "/var/lib/barman", 
                "basebackup_retry_sleep": 30, 
                "basebackup_retry_times": 0, 
                "basebackups_directory": "/var/lib/barman/pg/base", 
                "check_timeout": 30, 
                "compression": "gzip", 
                "conninfo": "host=pg user=barman dbname=somedb", 
                "custom_compression_filter": null, 
                "custom_decompression_filter": null, 
                "description": "somedb", 
                "disabled": false, 
                "errors_directory": "/var/lib/barman/pg/errors", 
                "immediate_checkpoint": false, 
                "incoming_wals_directory": "/var/lib/barman/pg/incoming", 
                "last_backup_maximum_age": "3 days", 
                "max_incoming_wals_queue": null, 
                "minimum_redundancy": 3, 
                "msg_list": [], 
                "name": "pg", 
                "network_compression": false, 
                "parallel_jobs": 1, 
                "path_prefix": null, 
                "post_archive_retry_script": null, 
                "post_archive_script": null, 
                "post_backup_retry_script": null, 
                "post_backup_script": "/var/lib/barman/report.sh", 
                "post_delete_retry_script": null, 
                "post_delete_script": null, 
                "post_recovery_retry_script": null, 
                "post_recovery_script": null, 
                "post_wal_delete_retry_script": null, 
                "post_wal_delete_script": null, 
                "pre_archive_retry_script": null, 
                "pre_archive_script": null, 
                "pre_backup_retry_script": null, 
                "pre_backup_script": null, 
                "pre_delete_retry_script": null, 
                "pre_delete_script": null, 
                "pre_recovery_retry_script": null, 
                "pre_recovery_script": null, 
                "pre_wal_delete_retry_script": null, 
                "pre_wal_delete_script": null, 
                "recovery_options": "", 
                "retention_policy": "window 2 w", 
                "retention_policy_mode": "auto", 
                "reuse_backup": null, 
                "slot_name": "barman", 
                "ssh_command": null, 
                "streaming_archiver": true, 
                "streaming_archiver_batch_size": 0, 
                "streaming_archiver_name": "barman_receive_wal", 
                "streaming_backup_name": "barman_streaming_backup", 
                "streaming_conninfo": "host=pg user=streaming_barman dbname=somedb", 
                "streaming_wals_directory": "/var/lib/barman/pg/streaming", 
                "tablespace_bandwidth_limit": null, 
                "wal_retention_policy": "simple-wal 2 w", 
                "wals_directory": "/var/lib/barman/pg/wals"
            }, 
            "status": {
                "config_file": "/etc/postgresql/9.4/main/postgresql.conf", 
                "connection_error": null, 
                "current_size": 5216777052.0, 
                "current_xlog": "000000010000000B00000037", 
                "data_directory": "/var/lib/postgresql/9.4/main", 
                "hba_file": "/etc/postgresql/9.4/main/pg_hba.conf", 
                "ident_file": "/etc/postgresql/9.4/main/pg_ident.conf", 
                "is_in_recovery": false, 
                "is_superuser": true, 
                "pg_basebackup_bwlimit": true, 
                "pg_basebackup_compatible": true, 
                "pg_basebackup_installed": true, 
                "pg_basebackup_path": "/usr/bin/pg_basebackup", 
                "pg_basebackup_tbls_mapping": true, 
                "pg_basebackup_version": "9.5.14", 
                "pg_receivexlog_compatible": true, 
                "pg_receivexlog_installed": true, 
                "pg_receivexlog_path": "/usr/bin/pg_receivexlog", 
                "pg_receivexlog_supports_slots": true, 
                "pg_receivexlog_synchronous": true, 
                "pg_receivexlog_version": "9.5.14", 
                "pgespresso_installed": false, 
                "replication_slot": [
                    "barman", 
                    true, 
                    "B/374178F8"
                ], 
                "replication_slot_support": true, 
                "server_txt_version": "9.4.18", 
                "streaming": true, 
                "streaming_supported": true, 
                "synchronous_standby_names": [
                    "barman_receive_wal"
                ], 
                "systemid": "6557130237786012721", 
                "timeline": 1, 
                "wal_level": "hot_standby", 
                "xlogpos": "B/374178F8"
            }, 
            "wals": {
                "last_archived_wal_per_timeline": {
                    "00000001": {
                        "compression": "gzip", 
                        "name": "000000010000000B00000036", 
                        "size": 5455915, 
                        "time": 1544253844.503785
                    }
                }
            }
        }
    }
}
```

**Comment by GaryNg9** [comment]
This also happened to me.I have no clue about this issue.The backup status is always STARTES，but never finished,
This is my barman diagnose
```
{
    "global": {
        "config": {
            "barman_home": "/home/barman", 
            "barman_user": "barman", 
            "configuration_files_directory": "/etc/barman.d", 
            "errors_list": [], 
            "log_file": "/var/log/barman/barman.log", 
            "log_level": "INFO"
        }, 
        "system_info": {
            "barman_ver": "2.6", 
            "kernel_ver": "Linux pgstudy-unknown66374.i.nease.net 3.16.0-4-amd64 #1 SMP Debian 3.16.43-2+deb8u2 (2017-06-26) x86_64 GNU/Linux", 
            "python_ver": "", 
            "release": "Distributor ID:\tDebian\nDescription:\tDebian GNU/Linux 8.9 (jessie)\nRelease:\t8.9\nCodename:\tjessie", 
            "rsync_ver": "rsync  version 3.1.1  protocol version 31", 
            "ssh_ver": ""
        }
    }, 
    "servers": {
        "pg-node2": {
            "backups": {
                "20190215T161337": {
                    "backup_id": "20190215T161337", 
                    "backup_label": null, 
                    "begin_offset": 10200, 
                    "begin_time": "Fri Feb 15 16:13:37 2019", 
                    "begin_wal": "00000015000001A0000000AB", 
                    "begin_xlog": "1A0/AB0027D8", 
                    "config_file": "/home/postgres/pgsql/data/postgresql.conf", 
                    "copy_stats": null, 
                    "deduplicated_size": null, 
                    "end_offset": null, 
                    "end_time": null, 
                    "end_wal": null, 
                    "end_xlog": null, 
                    "error": null, 
                    "hba_file": "/home/postgres/pgsql/data/pg_hba.conf", 
                    "ident_file": "/home/postgres/pgsql/data/pg_ident.conf", 
                    "included_files": null, 
                    "mode": "postgres", 
                    "pgdata": "/home/postgres/pgsql/data", 
                    "server_name": "pg-node2", 
                    "size": null, 
                    "status": "STARTED", 
                    "tablespaces": null, 
                    "timeline": 21, 
                    "version": 100004, 
                    "xlog_segment_size": 16777216
                }
            }, 
            "config": {
                "active": true, 
                "archiver": false, 
                "archiver_batch_size": 0, 
                "backup_directory": "/home/barman/pg-node2", 
                "backup_method": "postgres", 
                "backup_options": "concurrent_backup", 
                "bandwidth_limit": null, 
                "barman_home": "/home/barman", 
                "barman_lock_directory": "/home/barman", 
                "basebackup_retry_sleep": 30, 
                "basebackup_retry_times": 0, 
                "basebackups_directory": "/home/barman/pg-node2/base", 
                "check_timeout": 30, 
                "compression": null, 
                "conninfo": "host=pg-node2 user=barman dbname=postgres", 
                "custom_compression_filter": null, 
                "custom_decompression_filter": null, 
                "description": "pg-node2 PostgreSQL Database", 
                "disabled": false, 
                "errors_directory": "/home/barman/pg-node2/errors", 
                "immediate_checkpoint": false, 
                "incoming_wals_directory": "/home/barman/pg-node2/incoming", 
                "last_backup_maximum_age": null, 
                "max_incoming_wals_queue": null, 
                "minimum_redundancy": 0, 
                "msg_list": [], 
                "name": "pg-node2", 
                "network_compression": false, 
                "parallel_jobs": 1, 
                "path_prefix": null, 
                "post_archive_retry_script": null, 
                "post_archive_script": null, 
                "post_backup_retry_script": null, 
                "post_backup_script": null, 
                "post_delete_retry_script": null, 
                "post_delete_script": null, 
                "post_recovery_retry_script": null, 
                "post_recovery_script": null, 
                "post_wal_delete_retry_script": null, 
                "post_wal_delete_script": null, 
                "pre_archive_retry_script": null, 
                "pre_archive_script": null, 
                "pre_backup_retry_script": null, 
                "pre_backup_script": null, 
                "pre_delete_retry_script": null, 
                "pre_delete_script": null, 
                "pre_recovery_retry_script": null, 
                "pre_recovery_script": null, 
                "pre_wal_delete_retry_script": null, 
                "pre_wal_delete_script": null, 
                "primary_ssh_command": null, 
                "recovery_options": "", 
                "retention_policy": null, 
                "retention_policy_mode": "auto", 
                "reuse_backup": null, 
                "slot_name": "barman", 
                "ssh_command": null, 
                "streaming_archiver": true, 
                "streaming_archiver_batch_size": 0, 
                "streaming_archiver_name": "barman_receive_wal", 
                "streaming_backup_name": "barman_streaming_backup", 
                "streaming_conninfo": "host=pg-node2 user=replication dbname=postgres", 
                "streaming_wals_directory": "/home/barman/pg-node2/streaming", 
                "tablespace_bandwidth_limit": null, 
                "wal_retention_policy": "main", 
                "wals_directory": "/home/barman/pg-node2/wals"
            }, 
            "status": {
                "config_file": "/home/postgres/pgsql/data/postgresql.conf", 
                "connection_error": null, 
                "current_size": 1146127664.0, 
                "current_xlog": "00000015000001A0000000AD", 
                "data_directory": "/home/postgres/pgsql/data", 
                "hba_file": "/home/postgres/pgsql/data/pg_hba.conf", 
                "ident_file": "/home/postgres/pgsql/data/pg_ident.conf", 
                "is_in_recovery": false, 
                "is_superuser": true, 
                "pg_basebackup_bwlimit": true, 
                "pg_basebackup_compatible": true, 
                "pg_basebackup_installed": true, 
                "pg_basebackup_path": "/home/postgres/pgsql/bin/pg_basebackup", 
                "pg_basebackup_tbls_mapping": true, 
                "pg_basebackup_version": "10.4", 
                "pg_receivexlog_compatible": true, 
                "pg_receivexlog_installed": true, 
                "pg_receivexlog_path": "/home/postgres/pgsql/bin/pg_receivewal", 
                "pg_receivexlog_supports_slots": true, 
                "pg_receivexlog_synchronous": true, 
                "pg_receivexlog_version": "10.4", 
                "pgespresso_installed": false, 
                "replication_slot": [
                    "barman", 
                    true, 
                    "1A0/AD004948"
                ], 
                "replication_slot_support": true, 
                "server_txt_version": "10.4", 
                "streaming": true, 
                "streaming_supported": true, 
                "synchronous_standby_names": [
                    "barman_receive_wal"
                ], 
                "systemid": "6576136841139283511", 
                "timeline": 21, 
                "wal_level": "replica", 
                "xlogpos": "1A0/AD004948"
            }, 
            "wals": {
                "last_archived_wal_per_timeline": {
                    "00000015": {
                        "compression": null, 
                        "name": "00000015000001A0000000AC", 
                        "size": 16777216, 
                        "time": 1550218419.8923275
                    }
                }
            }
        }
    }
}

```

**Comment by cjchang1688** [comment]
@wlzch Has this issue been solved?

**Comment by wlzch** [comment]
Apparently, the issue in my case was because the whole data directory was very big, much bigger than the DB size. So I just waited until it finished (It took several hours).

**Comment by Amixp** [comment]
My problem is this too
On barman: barman list-backup .... 
p-db02 20200421T231002 - STARTED
in log:
2020-04-22 04:55:27,784 [818] barman.wal_archiver INFO: No xlog segments found from streaming for p-db02.
2020-04-22 04:55:27,886 [818] barman.wal_archiver INFO: No xlog segments found from streaming for p-db02.
2020-04-22 04:55:27,988 [818] barman.wal_archiver INFO: No xlog segments found from streaming for p-db02.

On slave pg: pg_active:
RUNNING QUERIES:
16645  postgres            barman      10***.8    0.0  0.0    0.00B    0.00B 344:17.37  Y    N      idle in trans   SELECT pg_is_in_recovery()

Diagnose:
{
    "global": {
        "config": {
            "barman_home": "/var/lib/barman", 
            "barman_user": "barman", 
            "configuration_files_directory": "/etc/barman.d", 
            "errors_list": [], 
            "log_file": "/var/log/barman/barman.log", 
            "log_level": "INFO", 
            "retention_policy": "REDUNDANCY 5"
        }, 
        "system_info": {
            "barman_ver": "2.10", 
            "kernel_ver": "Linux p-db-backup01.unix.local 3.10.0-957.10.1.el7.x86_64 #1 SMP Thu Feb 7 07:12:53 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux", 
            "python_ver": "", 
            "release": "LSB Version:\t:core-4.1-amd64:core-4.1-noarch\nDistributor ID:\tRedHatEnterpriseServer\nDescription:\tRed Hat Enterprise Linux Server release 7.6 (Maipo)\nRelease:\t7.6\nCodename:\tMaipo", 
            "rsync_ver": "rsync  version 3.1.2  protocol version 31", 
            "ssh_ver": "", 
            "timestamp": "Wed Apr 22 04:48:47 2020"
        }
    }, 
servers
       "p-db02": {
            "backups": {
                "20200416T231001": {
                    "backup_id": "20200416T231001", 
                    "backup_label": null, 
                    "begin_offset": 33160, 
                    "begin_time": "Thu Apr 16 23:10:01 2020", 
                    "begin_wal": "0000000600000012000000E3", 
                    "begin_xlog": "12/E3008188", 
                    "config_file": "/var/lib/pgsql/11/data/postgresql.conf", 
                    "copy_stats": {
                        "copy_time": 79.918296, 
                        "total_time": 79.918296
                    }, 
                    "deduplicated_size": 2461846596, 
                    "end_offset": 119912, 
                    "end_time": "Thu Apr 16 23:11:21 2020", 
                    "end_wal": "0000000600000012000000E3", 
                    "end_xlog": "12/E301D468", 
                    "error": null, 
                    "hba_file": "/var/lib/pgsql/11/data/pg_hba.conf", 
                    "ident_file": "/var/lib/pgsql/11/data/pg_ident.conf", 
                    "included_files": null, 
                    "mode": "postgres", 
                    "pgdata": "/var/lib/pgsql/11/data", 
                    "server_name": "p-db02", 
                    "size": 2461846596, 
                    "status": "DONE", 
                    "systemid": "6681601371065020703", 
                    "tablespaces": null, 
                    "timeline": 6, 
                    "version": 110002, 
                    "xlog_segment_size": 16777216
                }, 
       "p-db02": {
            "backups": {
                "20200421T231002": {
                    "backup_id": "20200421T231002", 
                    "backup_label": null, 
                    "begin_offset": null, 
                    "begin_time": "Tue Apr 21 23:10:02 2020", 
                    "begin_wal": null, 
                    "begin_xlog": "13/6013798", 
                    "config_file": "/var/lib/pgsql/11/data/postgresql.conf", 
                    "copy_stats": null, 
                    "deduplicated_size": null, 
                    "end_offset": null, 
                    "end_time": null, 
                    "end_wal": null, 
                    "end_xlog": null, 
                    "error": null, 
                    "hba_file": "/var/lib/pgsql/11/data/pg_hba.conf", 
                    "ident_file": "/var/lib/pgsql/11/data/pg_ident.conf", 
                    "included_files": null, 
                    "mode": "postgres", 
                    "pgdata": "/var/lib/pgsql/11/data", 
                    "server_name": "p-db02", 
                    "size": null, 
                    "status": "STARTED", 
                    "systemid": "6681601371065020703", 
                    "tablespaces": null, 
                    "timeline": null, 
                    "version": 110002, 
                    "xlog_segment_size": 16777216
                }
            }, 
            "config": {
                "active": true, 
                "archiver": false, 
                "archiver_batch_size": 0, 
                "backup_directory": "/var/lib/barman/p-db02", 
                "backup_method": "postgres", 
                "backup_options": "concurrent_backup", 
                "bandwidth_limit": null, 
                "barman_home": "/var/lib/barman", 
                "barman_lock_directory": "/var/lib/barman", 
                "basebackup_retry_sleep": 30, 
                "basebackup_retry_times": 0, 
                "basebackups_directory": "/var/lib/barman/p-db02/base", 
                "check_timeout": 30, 
                "compression": null, 
                "conninfo": "host=10.*.*.35 user=barman dbname=postgres", 
                "create_slot": "manual", 
                "custom_compression_filter": null, 
                "custom_decompression_filter": null, 
                "description": "p-db02 - SlaveDB", 
                "disabled": false, 
                "errors_directory": "/var/lib/barman/p-db02/errors", 
                "immediate_checkpoint": true, 
                "incoming_wals_directory": "/var/lib/barman/p-db02/incoming", 
                "last_backup_maximum_age": null, 
                "max_incoming_wals_queue": null, 
                "minimum_redundancy": 0, 
                "msg_list": [], 
                "name": "p-db02", 
                "network_compression": false, 
                "parallel_jobs": 1, 
                "path_prefix": "/usr/pgsql-11/bin", 
                "post_archive_retry_script": null, 
                "post_archive_script": null, 
                "post_backup_retry_script": null, 
                "post_backup_script": null, 
                "post_delete_retry_script": null, 
                "post_delete_script": null, 
                "post_recovery_retry_script": null, 
                "post_recovery_script": null, 
                "post_wal_delete_retry_script": null, 
                "post_wal_delete_script": null, 
                "pre_archive_retry_script": null, 
                "pre_archive_script": null, 
                "pre_backup_retry_script": null, 
               "pre_backup_script": null, 
                "pre_delete_retry_script": null, 
                "pre_delete_script": null, 
                "pre_recovery_retry_script": null, 
                "pre_recovery_script": null, 
                "pre_wal_delete_retry_script": null, 
                "pre_wal_delete_script": null, 
                "primary_ssh_command": null, 
                "recovery_options": "", 
                "retention_policy": "redundancy 5 b", 
                "retention_policy_mode": "auto", 
                "reuse_backup": null, 
                "slot_name": "brbackup_dmhdbstb", 
                "ssh_command": null, 
                "streaming_archiver": true, 
                "streaming_archiver_batch_size": 0, 
                "streaming_archiver_name": "barman_receive_wal", 
                "streaming_backup_name": "barman_streaming_backup", 
                "streaming_conninfo": "host=10.*.*.35 user=streaming_barman", 
                "streaming_wals_directory": "/var/lib/barman/p-db02/streaming", 
                "tablespace_bandwidth_limit": null, 
                "wal_retention_policy": "simple-wal 5 b", 
                "wals_directory": "/var/lib/barman/p-db02/wals"
            }, 
            "status": {
                "archive_timeout": 0, 
                "checkpoint_timeout": 300, 
                "config_file": "/var/lib/pgsql/11/data/postgresql.conf", 
                "connection_error": null, 
                "current_lsn": "13/63D09C0", 
                "current_size": 240123975.0, 
                "current_xlog": null, 
                "data_checksums": "on", 
                "data_directory": "/var/lib/pgsql/11/data", 
                "hba_file": "/var/lib/pgsql/11/data/pg_hba.conf", 
                "hot_standby": "on", 
                "ident_file": "/var/lib/pgsql/11/data/pg_ident.conf", 
                "is_in_recovery": true, 
                "is_superuser": true, 
                "max_replication_slots": "10", 
                "max_wal_senders": "10", 
                "pg_basebackup_bwlimit": true, 
                "pg_basebackup_compatible": true, 
                "pg_basebackup_installed": true, 
                "pg_basebackup_path": "/usr/pgsql-11/bin/pg_basebackup", 
                "pg_basebackup_tbls_mapping": true, 
                "pg_basebackup_version": "11.2", 
                "pg_receivexlog_compatible": true, 
                "pg_receivexlog_installed": true, 
                "pg_receivexlog_path": "/usr/pgsql-11/bin/pg_receivewal", 
                "pg_receivexlog_supports_slots": true, 
                "pg_receivexlog_synchronous": false, 
                "pg_receivexlog_version": "11.2", 
                "pgespresso_installed": false, 
                "postgres_systemid": "6681601371065020703", 
                "replication_slot": [
                    "brbackup_dmhdbstb", 
                    true, 
                    "13/6000000"
                ], 
                "replication_slot_support": true, 
                "server_txt_version": "11.2", 
                "streaming": true, 
                "streaming_supported": true, 
                "streaming_systemid": "6681601371065020703", 
                "synchronous_standby_names": [
                    ""
                ], 
                "timeline": 6, 
                "wal_compression": "off", 
                "wal_level": "replica", 
                "xlog_segment_size": 16777216, 
             "xlogpos": "13/63D09C0"
            }, 
            "wals": {
                "last_archived_wal_per_timeline": {
                    "00000006": {
                        "compression": null, 
                        "name": "000000060000001300000005", 
                        "size": 16777216, 
                        "time": 1587499311.2876043
                    }
                }
            }
        },

**Comment by amenonsen** [comment]
As part of an effort to pick up maintenance of Barman, I'm closing this and many other old open issues in this repository.
