### ISSUE TITLE
[feature] add Zstd support to cloud cli tools

### ISSUE THREAD

**Issue by Jean-Daniel** [EnterpriseDB/barman#850]
It would be helpful to have `zstd` support in tools like `barman-cloud-backup` and `barman-cloud-wal-archive` which are used by `CloudNativePG` for instance.

Being able to reduce CPU usage or increase compression efficiency would be very welcome, especially when working with large databases.

**Comment by mikewallace1979** [comment]
@Jean-Daniel agreed - we're actively looking into improving compression performance in the cloud cli tools and zstd support is one of the options

**Comment by martinmarques** [comment]
This was added in Barman 3.12 yesterday
