### ISSUE TITLE
RPM package update on Fedora 38 removes the configuration file /etc/barman.conf

### ISSUE THREAD

**Issue by mbalmer** [EnterpriseDB/barman#859]
Whenever the barman rpm package is updated on Fedora 38, it renames /etc/barman.conf to etc/barman.conf.rpmsave and adds a new file /etc/barman.conf.rpmnew.

I.e. it removes the running configuration and barman subsequently no longer works.

Please fix the RPM packages accordingly, this has hit me many times already.

**Comment by martinmarques** [comment]
Where are you getting the barman rpm packages from? Depending on which rpm repository you are using you'd need to contact the packager. If it was downloaded from PGDG, you can use the PGDG redmine issue tracker. If it's Fedora (I believe that the barman package is provided via EPEL), use the RedHat bugzilla.

Could you send us the output of `rpm -qi barman`? That should have the needed information on who is providing the package.

**Comment by mbalmer** [comment]
> Am 22.10.2023 um 11:01 schrieb Martín Marqués ***@***.***>:
> 
> 
> Where are you getting the barman rpm packages from? Depending on which rpm repository you are using you'd need to contact the packager. If it was downloaded from PGDG, you can use the PGDG redmine issue tracker. If it's Fedora (I believe that the barman package is provided via EPEL), use the RedHat bugzilla.
> Could you send us the output of rpm -qi barman? That should have the needed information on who is providing the package.
According to the rpm -qi barman it is indeed packaged by the Fedora project:

Name        : barman
Version     : 3.9.0
Release     : 1.fc38
Architecture: noarch
Install Date: Do 19 Okt 2023 06:38:06
Group       : Unspecified
Size        : 26244
License     : GPLv3
Signature   : RSA/SHA256, Di 10 Okt 2023 10:57:58, Key ID 809a8d7ceb10b464
Source RPM  : barman-3.9.0-1.fc38.src.rpm
Build Date  : Di 10 Okt 2023 10:51:57
Build Host  : buildvm-ppc64le-29.iad2.fedoraproject.org
Packager    : Fedora Project
Vendor      : Fedora Project
URL         : http://www.pgbarman.org/
Bug URL     : https://bugz.fedoraproject.org/barman
Summary     : Backup and Recovery Manager for PostgreSQL
Description :
Barman (Backup and Recovery Manager) is an open-source administration tool for
disaster recovery of PostgreSQL servers written in Python.

It allows your organization to perform remote backups of multiple servers in
business critical environments to reduce risk and help DBAs during the recovery
phase.

**Comment by martinmarques** [comment]
You have the "Bug URL" in the info output. I would open a ticket there. This is a packaging issue, which we don't have control over.
