### ISSUE TITLE
E-Mail to info@pgbarman.org bounces

### ISSUE THREAD

**Issue by mbalmer** [EnterpriseDB/barman#860]
E-mail to info@pgbarman.org bounces with the followin error message:

Address not found

Your message wasn't delivered to gabriele.bartolini@2ndquadrant.it because the address couldn't be found, or is unable to receive mail.

Your message wasn't delivered to [gabriele.bartolini@2ndquadrant.it](mailto:gabriele.bartolini@2ndquadrant.it) because the address couldn't be found, or is unable to receive mail.

Probably a misconfiguration

**Comment by martinmarques** [comment]
Thanks for reporting this. We've already brought this up to our IT department and will direct those email to the correct alias that lands with the developers, or whoever is responsible for receiving those messages.

**Comment by mikewallace1979** [comment]
This has now been updated so e-mails to `info@pgbarman.org` will no longer bounce. Thanks again for reporting the issue.
