### ISSUE TITLE
sdist is missing tests

### ISSUE THREAD

**Issue by mtelka** [EnterpriseDB/barman#866]
The sdist package at PyPI is missing tests.  Please add tests to sdist to make downstream testing easier.  Thank you.

**Comment by mikewallace1979** [comment]
Hi @mtelka - thanks for reporting the issue. Do you have a specific problem which is solved by the inclusion of the tests in the sdist?

We have no plan to add those for the moment and it is a change that is going to have a non-small impact in our distribution and testing pipeline.

**Comment by mtelka** [comment]
I'm working on `barman` package update for OpenIndiana.  During packaging we run tests to make sure everything is okay.  If tests are included in sdist then the process is fully automatic.  If we need to switch to github tarball to get tests then some manual work is needed.  So not having tests in sdist is just an inconvenience for us.

The other issue with github tarballs is that they could [change](https://github.blog/2023-02-21-update-on-the-future-stability-of-source-code-archives-and-hashes/) as time goes and this breaks build reproducibility so we always prefer to use sdists where possible.

Thank you.
