### ISSUE TITLE
Backing up Windos works, but restore fails due to UNIX assumptions

### ISSUE THREAD

**Issue by einhverfr** [EnterpriseDB/barman#892]
Backing up on Windows sorks fine aside from the problems documented in a past bug report.  Restore however fails rather catastrophically.

The problem I encountered was "Could not execute remote command ssh ...."  When focusing on the logs, the 'true' command failed, as it would in Windows.  This would have happened via  call to fs.ping().  Reviewing the file (fs.py) found that all of the calls in this map to UNIX commands but there are no Windows equivalents.  In this regard, this means that while you can back up a Windows database, you cannot restore it with Barman.  Therefore one has to come up with a manual process of copying files, extracting WAL segments, etc.

**Comment by martinmarques** [comment]
This is properly documented: 
```
Remote recovery is not supported for Windows servers, so you must recover your cluster locally in the Barman server and then copy all the files on a Windows server or use a folder shared between the PostgreSQL server and the Barman server.
```

The docs also mention that `This feature is still experimental`.

There are no plans to add support for Windows.
