### ISSUE TITLE
After update to BARMAN 3.10 getting a WARNING: Discarding configuration file: .barman.auto.conf (not a file)

### ISSUE THREAD

**Issue by meyerink** [EnterpriseDB/barman#900]
I am running BARMAN on Red Hat Enterprise Linux Server release 7.9 (Maipo) and just updated to barman-3.10.0-1.el7.noarch. After that update we are getting this WARNING continually in our barman log.

barman.config WARNING: Discarding configuration file: .barman.auto.conf (not a file)

Was something new introduced that I may have needed to reconfigure? I could not locate a .barman.auto.conf file anywhere...

Troy Meyerink
Database Administrator

**Comment by martinmarques** [comment]
This seems like a legitimate issue. We'll look at it, but in short, this is related to the new feature introduced in 3.10 related to configuration models

**Comment by gcalacoci** [comment]
@meyerink Thanks for pointing this out, we changed a couple of things in the barman configuration as @martinmarques pointed out, and after a quick assessment, we see that the message is misleading.
We are looking at the issue and we are going to re-work the piece of code to output more clear messages (and possibly less alarming 😉 )
In the meantime, ignore that message, is not your fault.
