### ISSUE TITLE
Consider migrating from snappy to cramjam

### ISSUE THREAD

**Issue by ptribble** [EnterpriseDB/barman#905]
The python-snappy module, as of 0.7.1, is now a shim for cramjam.

It might make sense to use cramjam directly; as a benefit, you get a number of other compression mechanisms for free, including zstd.

(One downside is that cramjam requires rust, and therefore isn't available on platforms that rust doesn't support, so the old method might be worth keeping as a fallback for users on those platforms.)

**Comment by martinmarques** [comment]
Hi, we've been looking into replacements for snappy for some time now. We haven't discarded any options, but haven't either taken any direction.
We'll keep this opened, given that it is something we are considering addressing

**Comment by jmealo** [comment]
This issue is still referenced in the `postgres-containers` repository for CNPG.

**Comment by martinmarques** [comment]
> This issue is still referenced in the `postgres-containers` repository for CNPG.

Can you be more specific on where it's referenced? The issue was resolved from barman side, unless there's some other issue related to snappy/cramjam

**Comment by remkolems** [comment]
> > This issue is still referenced in the `postgres-containers` repository for CNPG.
> 
> Can you be more specific on where it's referenced? The issue was resolved from barman side, unless there's some other issue related to snappy/cramjam

To be complete.

Among others:
https://github.com/cloudnative-pg/postgres-containers/blob/c5e248a87d2fe1a7254e4757736550ed1b317583/Debian/17/bookworm/Dockerfile#L48

and issue has been created about it this: https://github.com/cloudnative-pg/postgres-containers/issues/117

**Comment by martinmarques** [comment]
I think you should bring this up to the CNPG team.
