### ISSUE TITLE
How can I set parameter statement_timeout in barman backup configuration file ？

### ISSUE THREAD

**Issue by Myshiner** [EnterpriseDB/barman#915]
I got some errors like that "DETAILS: pg_start_backup(): canceling statement due to statement timeout" in backup log file and then backup task failded. so i wonder if i can set the postgresql database parameter "statement_timeout" in backup config file .

**Comment by Myshiner** [comment]
![image](https://github.com/EnterpriseDB/barman/assets/48242833/739fd43d-3146-4258-af7d-1e16a11544bf)

**Comment by martinmarques** [comment]
You should start by checking here: https://www.postgresql.org/docs/16/libpq-connect.html#LIBPQ-CONNSTRING

**Comment by barthisrael** [comment]
For the record, you can use `options` in the connection string, e.g.:

```console
$ psql "host=localhost user=postgres options='-c statement_timeout=10'"
psql (17beta1)
Type "help" for help.

postgres=# SHOW statement_timeout ;
 statement_timeout
-------------------
 10ms
(1 row)
```

**Comment by gonzalemario** [comment]
@Myshiner do you need anything else from us?

**Comment by joeauty** [comment]
For those having this problem, it is a little confusing but the -d flag for the `barman-cloud-backup` script supports a connection string, so you can include the statement_timeout there like the following, omitting all other authentication flags:

`-d "host=localhost user=postgres dbname=yourdb options='-c statement_timeout=0'"`
