### ISSUE TITLE
Backup path change

### ISSUE THREAD

**Issue by maheshetty20** [EnterpriseDB/barman#919]
Hello experts,
I need assistance to adjust our backup setup. 

At the moment, our Barman backups are stored at the mount point: /srv/barman. 

I would like to transition to a new mount point, specifically: /mnt/eu02_gb_cam_barman_backup.

Here's the current configuration I'm working with:
cat /etc/barman.conf 
[barman] 
barman_home = /srv/barman 
barman_user = barman 
log_file = /var/log/barman/barman.log 
compression = gzip 
last_backup_maximum_age = 10 DAYS 
backup_options = exclusive_backup 
minimum_redundancy = 1 
retention_policy = RECOVERY WINDOWS OF 4 WEEKS 
retention_policy_mode = auto 
wal_retention_policy = main 
reuse_backup = link 
configuration_files_directory = /srv/barman.conf.d 
archiver = on 

Could you guide me on how to accomplish this transition? Is it sufficient to modify the "barman_home" parameter, or are there additional adjustments required?

**Comment by martinmarques** [comment]
Sorry for missing this. I suggest using the barman google groups for general questions like the above.

https://groups.google.com/g/pgbarman
