### ISSUE TITLE
Barman sometimes backup failed with database keycloak

### ISSUE THREAD

**Issue by cuong-max** [EnterpriseDB/barman#948]
Hi all,

My issue is that barman execute backup failed when i start backup database of keycloak

Environments: `Barman version 3.8.0`

Command execute backup: `barman barman backup keycloak --wait`

See the logs:

```
pg_basebackup error:
pg_basebackup: initiating base backup , waiting for checkpoint to complete
pg_basebackup: checkpoint completed
pg_basebackup: error: could not read COPY data: server closed the connection unexpectedly
This probably means the server terminated abnormally before or while processing the request.
```

Any suggestions to fix this ?

Thanks a lot

**Comment by martinmarques** [comment]
I suppose you solved this, in which case it would be nice to have the outcome here for others who might have this problem.

In any case, the error shows that the server closed the connection. You should check what happened on the Postgres side.
